<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en">
<head>
<?php include "musicfamily.org/../scripts/header.html"; ?>
<a id="rightbox " href="https://discord.gg/cq6zmQX"></a>
<p>Welcome to <b>G00F's Not a Wiki</b> Realm Grinder <font face="Comic sans MS" size="3">"G00FBALL"</font> style without all the wiki adverts.
<p><b><a target="_blank" href="https://discord.gg/cq6zmQX">Realm Grinder Chat on Discord</a></b></p>
<p><b><a target="_blank" href="http://www.kongregate.com/forums/8945-realm-grinder">Realm Grinder Forum on Kongregate</a></b></p>
<p><b><a target="_blank" href="https://steamcommunity.com/sharedfiles/filedetails/?id=1118498519">In-Depth Guide to R0 Starting Realm Grinder</a></b> by bookboy</p>
<p>If you have any suggestions or find any errors send a message to <a target="_blank" href="http://www.kongregate.com/accounts/Igorogi/"><b>Igorogi</b></a> or <a target="_blank" href="http://www.kongregate.com/accounts/G00FBALL/"><b>G00FBALL</b></a> and please include links to where you got the information.</p>

<p>A lot of the information on this site comes from the players in room 2 and the members of the <b><a target="_blank" href="https://discord.gg/cq6zmQX">Realm Grinder Chat on Discord</a></b></p>
<p>This site contains information you need to know to help you play <a target="_blank" href="http://www.kongregate.com/games/DivineGames/realm-grinder"><b>Realm Grinder</b></a>, an incremental/idle game by <a target="_blank"target="_blank" href="http://www.divinegames.it/"><b>DivineGames</b></a> and hosted on <a target="_blank"target="_blank" href="http://www.kongregate.com/"><b>Kongregate</b>.</a>
<p>Now available on <a target="_blank"target="_blank" href="http://store.steampowered.com/app/610080/Realm_Grinder/"><b>Steam</b></a>, <a target="_blank"target="_blank" href="https://play.google.com/store/apps/details?id=com.kongregate.mobile.realmgrinder.google&hl=en/"><b>Android</b></a>, and <a target="_blank"target="_blank" href="https://itunes.apple.com/us/app/realm-grinder/id1110149506?mt=8/"><b>iOS</b></a>.
<p><b>About The Game</b>
<p>Realm Grinder was first published on May 19, 2015. Since then, there has been many expansions and updates - the game is constantly evolving.</p>
<p>Realm Grinder puts you in the role of a good or evil monarch, managing buildings, upgrades, and politics in order to create a large, powerful, and - most importantly - rich Realm.</a>
<p>The game belongs to the idle/incremental genre, meaning you will have to click (at least in the beginning), buy buildings and upgrades, cast spells and make other strategic choices with the ultimate goal of gaining more and more coins. There is no fixed end to the game, as you can always sell all your properties by abdicating to gain Gems, which will in turn help you generate even more coins. Abdications are one kind of soft reset, when you become even richer, you will be able to start a new life by Reincarnating, an other kind of soft reset that allows you to gain other bonuses that will further speed up your next life as monarch.
<p>Realm Grinder is the first of its kind to introduce a significant level of replayability by giving the player choices that will change their play style. You will be given goals and to reach these goals, the choice to join different factions of mythic creatures. Ranging from good Fairies, evil Goblins, to neutral Titans, each faction have their own resource (Faction Coins) obtained randomly by clicking the background. Each focuses on different mechanics, ranging from improving low tier buildings to massive spell-casting capabilities. As you play and learn, it will be yours to find out how to best reach these different goals.</p>
<p><img src="http://musicfamily.org/realm/Factions/picks/FactionGrid.png" usemap="#FactionGrid-map">

<map name="FactionGrid-map">
    <area target="_self" research="Fairy<p>Fairies focus on the small and common things and make them magically powerful. <p>Affiliating yourself with the Fairy faction will hugely improve the output of lower tier buildings. <p>Part of the Good Vanilla Factions, the Fairies can cheaply build the 3 first Tier buildings, thus boosting perks based on amount of buildings, and help get some of the building trophy series. <p>With their spell upgrade, they can magically multiply the amount of assistants, which combined with other perks can become a very strong asset." href="http://musicfamily.org/realm/FairyFaction/" coords="6,8,58,59" shape="rect">
    <area target="_self" research="Elf<p>Elves are masters of efficiency and expertise, taking the best results from every single action. <p>Affiliating yourself with the Elves faction will dramatically boost your clicking rewards while forsaking passive production. <p>Part of the Good Vanilla Factions, the Elven Faction increase click reward and the chance to find faction coins. <p>They can help you to get the Click and Faction coins trophies series. Their spell upgrade will relieve you from the necessity of manual clicking and let you aim for the Treasure Trophies series while idling." href="http://musicfamily.org/realm/ElfFaction/" coords="66,7,115,59" shape="rect">
    <area target="_self" research="Angel<p>Angels' ability with magic is unparalleled as they have the innate power to infuse mana into everything they touch. <p>Affiliating yourself with the Angels faction will grant you nearly unlimited spell power and the ability to take advantage of it directly. <p>Part of the Good Vanilla Factions, Angels empower mana and spells, and thus can help when aiming for the mana and spell trophy series. <p>Their Bloodline increases mana regeneration based on spells cast this game." href="http://musicfamily.org/realm/AngelFaction/" coords="124,10,173,59" shape="rect">
    <area target="_self" research="Goblin<p>The sly Goblins excel at making the best possible deals and bargains. <p>Affiliating yourself with the Goblins faction will vastly increase the potential of your Tax Collection spell. <p>Part of the Evil Vanilla Factions, the Goblin's asset is the ability to empower the Tax collection spell, therefore boosting both their production and the production of Faction Coins. <p>Their Bloodline will be valuable when aiming for all the building trophy series." href="http://musicfamily.org/realm/GoblinFaction/" coords="180,8,232,59" shape="rect">
    <area target="_self" research="Undead<p>Undeads are resilient and tireless, but most importantly, they can't die. <p>Affiliating yourself with the Undead faction will grant you a steady flow of production which increases drastically as time passes. <p>Part of the Evil Vanilla Factions, the Undead become more powerful with time. <p>Their Heritage and Bloodline give assistants based on playtime and reincarnations and is more frequently used in late games." href="http://musicfamily.org/realm/UndeadFaction/" coords="241,10,290,59" shape="rect">
    <area target="_self" research="Demon<p>The mighty and fearless Demons cannot bother with petty trifles, they only care for greatness and power. <p>Affiliating yourself with the Demons faction will hugely improve the output of higher tier buildings. <p>Part of the Evil Vanilla Factions, the Demons are related to increasing production of highest tier buildings and have perks based on the amount of trophies unlocked. <p>Their Bloodline boosts the production bonus of gems based on how much time you spent with the Evil alignment this reincarnation." href="http://musicfamily.org/realm/DemonFaction/" coords="298,10,348,59" shape="rect">
    <area target="_self" research="Titan<p>Titans were an ancient race of giant creatures with godlike powers and millennial knowledge. <p>Affiliating yourself with the Titans faction means big numbers: they will boost every aspect of your economy to unimaginable values <p>Part of the Neutral Faction and the first Neutral Faction to be unlocked as the requirements are the lowest. <p> Both the Titans' Bloodline and Heritage boost your production based on how many Royal Exchanges you have purchased in this abdication. <p>Their Faction spell is based on luck and can become very powerful." href="http://musicfamily.org/realm/TitanFaction/" coords="6,72,57,121" shape="rect">
    <area target="_self" research="Druid<p>The wise Druids of old were a group of people from all races who strove to maintain world balance with mystical discipline and powerful magic. <p>Affiliating yourself with the Druids faction will boost your magic capabilities and reward balancing of all things. <p>Part of the Neutral Faction, the Druids feature a considerably nice Heritage that increases max mana, and their bloodline increase mana regeneration based on your max mana. <p>Their final Challenge reward extends their spell to affect more buildings." href="http://musicfamily.org/realm/DruidFaction/" coords="66,71,117,122" shape="rect">
    <area target="_self" research="Faceless<p>Little is known about the Faceless, but it is said they did not possess individual minds, instead they were all connected to a central consciousness which governed all their choices and behaviours. <p>Affiliating yourself to the Faceless Faction will boost your production based on your past choices while giving progressively better bonuses. <p>Part of the Neutral Faction, the Faceless feature perks that becomes stronger with time. <p>Their Heritage is based on the highest amount of buildings owned in the current reincarnation, and thus can easily be improved by doing a goblin-line run." href="http://musicfamily.org/realm/FacelessFaction/" coords="124,71,175,122" shape="rect">
    <area target="_self" research="Dwarf<p>The Dwarves make the best masons, artisans and blacksmiths in all the realms. Their creations will outlast anything made by other races... except for beer, that is. <p>Part of the Prestige Faction, the Dwarf Faction appears in addition to a good faction and enables the player to use all the 2 faction spells and 18 upgrades and from both the Good and Dwarf factions. <p> The dwarf faction focus on boosting production based on how many times you excavated this reincarnation. <p>The Dwarf faction cannot be combined with Evil or Neutral Factions, nor is there Research Tree for Dwarfs." href="http://musicfamily.org/realm/DwarfFaction/" href="/realm/DwarfFaction" coords="182,71,231,122" shape="rect">
    <area target="_self" research="Drow<p>The Drows believe that any crime can go unpunished if nobody notices you did it. They value and praise perfect executions, and will reward those who plan accordingly. <p>Part of the Prestige Faction, the Drow Faction appears in addition to an Evil faction, this enables the player to use all the 2 faction spells and 18 upgrades and from both the Evil and Drow factions. <p> The Drow faction focus on boosting offline production, and boosting production based on offline production. <p>The Drow faction cannot be combined with Good or Neutral Factions, nor is there Research Tree for Drow." href="http://musicfamily.org/realm/DrowFaction/" coords="239,72,290,121" shape="rect">
    <area target="_self" research="Dragon<p>The Dragon is the mightiest, most imposing creature of all the realms. None may stand a chance alone against a Dragon, not even the firecest of heroes. They usually care little for the lower creatures, but you have piqued their interest. <p>The Dragon Faction appears in addition to an Neutral faction, this enables the player to use all the 2 faction spells and 18 upgrades and from both the Neutral and Dragon factions. <p>The Dragon faction cannot be combined with Good or Evil. <p>Unlocking the Dragon faction requires 46 Reincarnations and can be done by completing a series of quests  " href="http://musicfamily.org/realm/DragonFaction/" coords="297,70,348,123" shape="rect">
    <area target="_self" research="Archon<p>The Archon value loyalty and any systematic and efficient plan of action. Affiliating with them will increase your ability to boost your production immensely over long periods of time." href="/realm/ArchonFaction" coords="7,134,59,186" shape="rect">
    <area target="_self" research="Djinn<p>A magical race of ephemeral and elusive beings, unbound by natural rules but instead commanding them. Affiliating with them will grant you the ability to manipulate random outcomes to your advantage." href="/realm/DjinnFaction" coords="66,134,116,185" shape="rect">
    <area target="_self" research="Makers<p>The legendary old race which is said to have created the world, their watchful eye aims to keep all forces in check. Affiliating with them will increase your ability to dominate all your resources." href="/realm/MakersFaction" coords="124,133,176,185" shape="rect">
    <area target="_self" research="Mercenaries<p>When a mercenary crosses your path, there's only one thing that can save your life: offer him more money than he can get by killing you. <p>If you gain the favor of the mercenaries, you will be able to combine the power of all races at once.<p>Available in all alignments, The Mercenaries can combine the power of the existing factions: Lets you choose 2 spells and 3x4 faction upgrades enabling you to create a custom cross-faction build. <p>Unlocking the Mercenaries Requires 3 reincarnations and can be done in different game plays." href="http://musicfamily.org/realm/MercenaryFaction/" coords="182,133,233,184" shape="rect">
</map>
<?php include "musicfamily.org/../scripts/footer.html"; ?>
