<link rel="shortcut icon" href="http://musicfamily.org/realm/Factions/picks/favicon.ico" >
<body>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en">
<?php include "../scripts/header.html"; ?>
<link rel="stylesheet" href="http://musicfamily.org/realm/scripts/rtree.css" /></link>

<a href="http://musicfamily.org/realm/ResearchFacilities/"><b>Mobile Text Version</b></a>







<p>A complete list of all research <b>hover</b> over them to see what they are.
<img src="http://musicfamily.org/realm/Factions/picks/Researchtree.png" usemap="#Researchtree-map">
<map name="Researchtree-map">
<area target="" research="Spellcraft<p>Delve into the arcane mysteries of Spellcraft, discovering new ways to produce and use mana. <p> Increases: Fairy, Faceless, and Drow production.<p>Pointing to this ingame will tell you how many slots are available also tells you your total research points." coords="47,39,109,99" shape="rect">
<area target="" research="S1 - For Fairy - Spell Name: Enchanting <p> Cost: 750 Qag (7.5E125) <p> Effect: Increase the production of Enchanted Fields based on mana produced. <p> Formula: round(0.75 * x^0.6)%, where x is your Mana Produced (This Game) stat." coords="30,109,75,155" shape="rect">
<area target="" research="S10 - For Angel - Spell Name: Channeling. <p> Requirement: 2000 Heaven's Gate. (This Game) <p> Cost: 28.83 Uqag (2.883E127) <p> Effect: Increase the production of all other buildings by 110% per Heaven's Domain you own." coords="83,109,130,153" shape="rect">
<area target="" research="S30 - For Any - Spell Name: Vacuumancy <p> Requirement: Have 4000 Mana. (This Game) <p> Cost: 95.88 Dqag (9.588E130) <p> Effect: Increase maximum mana and mana regeneration rate based on time spent in this game. <p> Formula: Max Mana:floor(25 * x), Mana Regeneration:floor(75 * x^0.4) / 10, where x is your Playtime (This Game) stat in hours." coords="27,162,75,211" shape="rect">
<area target="" research="S50 - For Goblin - Spell Name: Conjuration <p> Requirement: Have 6000 mana(as Fairy) (This Game)<p> Cost: 318.8 Tqag (3.188E134) <p> Effect: Each time you cast a spell you also cast free Tax Collections based on the amount of Goblin Banks you own. <p> Formula: floor(x /650), where x is the number of Goblin Banks you own." coords="83,164,133,210" shape="rect">
<area target="" research="S105 - For Any - Spell Name: Mysticism <p> Requirement: 600 Researches  (Total)<p> Cost: 1.544 Spqag (1.544E144) <p> Effect: Increase mana regeneration based on the amount of research made. <p> Formula: floor(x^0.5), where x is number of researches made." coords="28,217,74,264" shape="rect">
<area target="" research="S135 - For Any - Spell Name: Augmentation <p> Requirement: 5000 Unique Buildings(as Fairy) (This Game)<p> Cost: 296 Ocqag (2.96E149) <p> Effect: Increase the production of Unique Buildings based on maximum mana. <p> Formula: round(2 * x^0.8)%, where x is your maximum mana." coords="84,218,130,264" shape="rect">
<area target="" research="S150 - For Any - Spell Name: Pyromancy <p> Requirement: Research Inflame (D10) &amp; Fusion (A105) <p> Cost: 129.6 Noqag (1.296E152) <p> Effect: Increase the production of the two highest building tiers based on your mana regeneration. <p> Formula: round(4 * x^1.3)%, where x is your Mana per Second stat." coords="27,273,75,318" shape="rect">
<area target="" research="S175 - For Elf - Spell Name: Empowered Luck <p> Requirement: Research Blessing (D1) & Augmentation (S135) <p> Cost: 3.273 UQig (3.273E156) <p> Effect: Increase production of buildings by 36,000% for 20 seconds each time you trigger Elven Luck and increase the chance to trigger it by 24%." coords="83,274,130,319" shape="rect">
<area target="" research="S180 - For Fairy - Spell Name: Incantation <p> Requirement: Research Enchanting (S1) & Mysticism (S105) <p> Cost: 3.273 UQig (3.273E156) <p> Effect: Increase mana regeneration based on the number of assistants you own.<p><b>Formula</b>: floor(13 * x^0.55) / 10, where x is the number of assistants you have." coords="28,328,76,375" shape="rect">
<area target="" research="S200 - For Any - Spell Name: Cryomancy <p> Requirement: Research Conjuration (S50) and Refraction (A55) <p> Cost: 82.65 DQig (8.265E160) <p> Effect: Increase the production of all buildings based on your current mana (the less mana, the better bonus). <p> Formula: round(x^1.75)%, where x is percentage of current mana." coords="84,329,130,374" shape="rect">
<area target="" research="S215 - For Any - Spell Name: Projection <p> Requirement: 300 Spiritual Surge (Total), Research Channeling (S10) &amp; Incantation (S175) <p> Cost: 36.16 TQig (3.616E163) <p> Effect: Increase Spiritual Surge effect by 150% per other active spell." coords="28,385,76,428" shape="rect">
<area target="" research="S225 - For Undead - Spell Name: Necromancy <p> Requirement: Research Resurrection (D175) &amp; Cryomancy (S200) <p> Cost: 2.087 QaQig (2.087E165) <p> Effect: Increase the production of assistants based on the amount of Necropolises you own. <p> <p> Formula: round(5 * x^0.75)%, where x is the number of Necropolises you own." coords="84,382,131,430" shape="rect">
<area target="" research="S250 - For Any - Spell Name: Aeromancy <p> Requirement: Research Weather Control (D225) &amp; Explosives (A150) <p> Cost: 52 QiQig (5.27E169) <p> Effect: Increase the production of Unique Buildings based on mana produced in this game. <p> Formula: round(0.5 * x^0.58)%, where x is your Mana Produced (This Game) stat." coords="27,439,76,486" shape="rect">
<area target="" research="S251 - For Faceless - Spell Name: Assimilation <p> Requirement: Play as Faceless <p> Cost: 79.05 QiQig (7.905E169) <p> Effect: Increase the production of Sunken Cities based on time spent affiliated with factions different than the Faceless. <p> Formula: round(0.3 * x^0.7)%, where x is total time spent as non-Faceless factions." coords="84,437,131,484" shape="rect">
<area target="" research="S270 - For Any - Spell Name: Runecarving <p> Requirement: 500,000 clicks (This game) <p> Cost: 175.2 SxQig (1.752E173) <p> Effect: Increase the production of all buildings except the most productive one based on maximum mana. While offline, affects all buildings. <p> Formula: round(x^0.9)%, where x is your maximum mana." coords="28,494,76,540" shape="rect">
<area target="" research="S300 - For Titan - Spell Name: Chain Lightning <p> Requirement: 25 Brainwaves (Faceless)(This R) <p> Cost: 33 OcQig (3.36E178) <p> Effect: While Lightning Strike is active, all non-target buildings have their production increased based on the amount of Lightning Strikes cast in this game. <p> Formula: round(120 * x^0.8)%, where x is your Lightning Strikes cast (This Game) stat." coords="84,494,131,542" shape="rect">
<area target="" research="S305 - For Any - Spell Name: Mesmerization <p> Requirement: 5 days as Faceless(Total across all R) <p> Cost: 225.2 OcQig (2.252E179) <p> Effect: Increase the production of all buildings by a fraction of your offline production bonus. <p> Formula: 0.25 * ln(1 + x)^5.3%, where x is your (pre-Ascension) offline production bonus as a multiplier." coords="28,548,76,596" shape="rect">
<area target="" research="S330 - For Any - Spell Name: Reverberation <p> Requirement: Research Cryomancy (A200) &amp; Weather Control (D225) <p> Cost: 6.443 Sxg (6.443E183) <p> Effect: Increase the production of all buildings based on the number of active spells you have. You must have at least 3 active spells to generate a bonus. <p> Formula: 375 * 2^x%, where x is the number of spells currently active." coords="84,549,131,596" shape="rect">
<area target="" research="S375 - For Faceless - Spell Name: Illusion <p> Requirement: Research Reverberation (S330) &amp; Mesmerization (S305) <p> Cost: 541 DSxg (5.41E191) <p> Effect: Brainwave also provides progressively more assistants over its duration. <p> Formula: floor(x^2), where x is how many minutes the spell has been active." coords="27,604,76,650" shape="rect">
<area target="" research="S400 - For Any - Spell Name Capacity <p> Requirement: Research Projection (S215) &amp; Incantation (S175) <p> Cost: 13.66 QaSxg (1.366E196) <p>Effect: Increase maximum mana based on the highest amount of spells cast in a single game. <p> Formula: floor(22 * x^0.32), where x is your Spell Cast (Max) stat." coords="83,604,130,652" shape="rect">
<area target="" research="S435 - For Drow - Spell Name: Spellbinding <p> Requirement: 4h Combo Strike Cast Time (This Game)<p> Cost: 1.989e213 <p> Effect: Passively grants the effects from Call to Arms while offline." coords="28,657,77,706" shape="rect">
<area target="" research="S460 - For Any - Spell Name: Focus <p> Requirement: 25000 spells cast (This game) <p> Cost: 5.023 SpSxg (5,023E206) <p>Effect: Increase the production of all buildings based on the times you cast your faction spell in this game. <p> Formula: 15 * x^0.8%, where x is Faction Spells Cast This Game (Vanilla + Prestige spell count)." coords="84,658,130,706" shape="rect">
<area target="" research="S500 - For Any - Spell Name: Heirlooms <p> Requirement: 40 Artifacts (as Drow) <p> Cost: 5.554 Spg (5,554E213) <p> Effect: Each artifact you discover increases maximum mana by 100." coords="27,712,77,761" shape="rect">
<area target="" research="S545 - For Any - Spell Name: Hierarchy <p> Requirement: 10M (1E7) mana produced (This Game)<p> Cost: 466.3 DSpq (4.663E221) <p> Effect: Increase the production of buildings based on mana produced in this game, depending on their tiers. Gives better bonuses for lower tiers. <p> Formula: (0.1 * x^0.45 * T^2)%, where x is Mana Produced (This Game) stat, and T is the building tier, starting at 11 for Farms and decreasing to 1 for Halls of Legends." coords="84,713,130,761" shape="rect">
<area target="" research="S590 - For Fairy,Dwarf - Spell Name: Trickery <p> Requirement: 200 Dwarf Exchanges (as Dwairy) (This Game), Research Mysticism(S105) & Illusion (S375) <p> Cost: 39.16 QiSpg (3.916E229) <p> Effect: Increase the production of Neutral buildings based on maximum Mana. <p> Formula: 0.5 * x^1.05%, where x is Maximum Mana." coords="27,768,76,817" shape="rect">
<area target="" research="Craftsmanship<p>Learn how to use tools and experience to improve your production by mastering Craftsmanship. <p> Increases Elven, Titan, and Dwarven production.<p>Pointing to this ingame will tell you how many slots are available also tells you your total research points." coords="159,36,227,101" shape="rect">
<area target="" research="C1 - For Elf - Spell Name: Dummy Targets <p> Cost: 750 Qag (7.5E125) <p> Effect: Increase Elven Training Grounds production based on the amount of Faction Coins you found. <p> Formula: round(1.3 * ln^3(1+ x))%, where x is your Faction Coins Gained (This Game) stat." coords="143,108,190,157" shape="rect">
<area target="" research="C10 - For Fairy - Spell Name: Cultivation <p> Requirement: 2500 Farms <p> Cost: 28.83 Uqag (2.883E127) <p> Effect: Increases production of Blacksmith and Inn by 60% per Enchanted field that you have." coords="199,109,245,155" shape="rect">
<area target="" research="C25 - For Angel - Spell Name: Light Condenser <p> Requirement: 12,000 Spells cast(Total) <p> Cost: 12.63 Dqag (1.263E130) <p> Effect: Increase mana regeneration based on the amount of spells cast. <p> Formula: floor(10 * x^0.3) / 10, where x is your Spells Cast (This Game) stat." coords="144,164,191,210" shape="rect">
<area target="" research="C50 - For Demon - Spell Name: Refining <p> Requirement: 1 B (1E9) Faction Coins(as Elf) <p> Cost: 318.8 Tgag (3.188E134) <p> Effect: Increase the production of Infernal Realms based on the amount of Demon Coins you found in this Game. <p> Formula: round(0.8 * ln^3(1 + x))%, where x is your Demon Coins Gained (This Game) stat." coords="199,163,247,211" shape="rect">
<area target="" research="C80 - For Any - Spell Name: Apprenticeship <p> Requirement: 16,000 Good and Evil buildings <p> Cost: 61.13 Qiqag (6.113E139) <p> Effect: Increase the production of Neutral buildings based on the amount of Good and Evil buildings. <p> Formula: round(x^0.8)%, where x is the number of Good and Evil Buildings you own." coords="143,218,190,264" shape="rect">
<area target="" research="C105 - For Any - Spell Name: Woodcraft <p> Requirement: 25,000 clicks(This Game) <p> Cost: 1.544 Spqag (1.544E144) <p> Effect: Increase the chance to find Faction Coins based on the amount of Unique Buildings you own. <p> Formula: floor(1.5 * x^0.85)%, where x is the number of Unique Buildings you own." coords="199,219,246,265" shape="rect">
<area target="" research="C120 - For Any - Spell Name: Socketing <p> Requirement: 200,000 clicks(This Game) <p> Cost: 676 Spqag (6.76E146) <p> Effect: Increase clicking reward based on the amount of gems you own. <p> Formula: round(20 * log(1 + x))%, where x is your current number of gems." coords="144,273,191,321" shape="rect">
<area target="" research="C135 - For Any - Spell Name: Reinforcing <p> Requirement: 250,000 clicks(This Game, as Elf) <p> Cost: 296 Ocqag (2.96E149) <p> Effect: Increase the production of all buildings based on your total number of clicks. <p> Formula: (ln(1 + x))^2.75%, where x is your Treasure Clicks (Total) stat." coords="198,274,246,319" shape="rect">
<area target="" research="C150 - For Any - Spell Name: Tinkering <p> Requirement: Research Recycling (E10) &amp; Reinforcing (C135) <p> Cost: 129.6 Noqag (1.296E152) <p> Effect: Increase the production of all buildings based on the amount of research made. <p> Formula: round(125 * x^0.38)%, where x is number of researches made." coords="144,326,191,374" shape="rect">
<area target="" research="C175 - For Goblin - Spell Name: Gemcutting <p> Requirement: Research Refining (C50) &amp; Socketing (C120) <p> Cost: 3.273 Uqig (3.273E156) <p> Effect: Increase the production bonus from gems based on the number of buildings you own. <p> Formula: floor(x / 2000)%, where x is your Buildings Owned (This Game) stat." coords="198,329,246,375" shape="rect">
<area target="" research="C200 - For Any - Spell Name: Journeymen <p> Requirement: Research Apprenticeship (C80) &amp; Bartering (E50). <p> Cost: 82.65 Dqig (8.265E160) <p> Effect: Increase the production of Unique Buildings based on total time spent as that faction. <p> Formula: round(0.125 * x^0.7)%, where x is your Time Spent as that faction stat." coords="144,383,190,431" shape="rect">
<area target="" research="C225 - For Elf - Spell Name: Automatons <p> Requirement: Research Dummy Targets (C1) &amp; Vivification (A120). <p> Cost: 2.087 Qaqig (2.087E165) <p> Effect: Each Elven Training Grounds counts as 200 buildings for Call to Arms purposes." coords="198,383,246,430" shape="rect">
<area target="" research="C250 - For Any - Spell Name: Magnetism <p> Requirement: Research Tinkering (C150) &amp; Critical Strike (W225). <p> Cost: 52.7 Qiqig (5.27E169) <p> Effect: Increase the chance to find faction coins based on total time spent offline. (in minutes) <p> Formula: floor(2 * x^0.95), where x is your Time Spent Offline (Total) in minutes stat." coords="144,438,190,485" shape="rect">
<area target="" research="C251 - For Titan - Spell Name: Architecture <p> Requirement: Play as Titan <p> Cost: 79.05 QiQig (79.05E168) <p> Effect: Increase the production of Olympian Halls based on the amount of buildings you own. <p> Formula: round(0.5 * x^0.8)%, where x is your Buildings Owned (This Game) stat." coords="198,437,246,485" shape="rect">
<area target="" research="C300 - For Druid - Spell Name: Weighting <p> Requirement: 650 Lightning Strikes <p> Cost: 33.6 OcQig (33.6E177) <p> Effect: Increase Grand Balance multiplier by x20 when hitting Stonehenge Circles. Also increase its multiplier for every target based on maximum mana. <p> Formula: round((1.5 * ln(1 + x))^2)%, where x is your maximum mana." coords="144,493,191,541" shape="rect">
<area target="" research="C305 - For Any - Spell Name: Golemcraft <p> Requirement: 5 days as Titans(Total across all R) <p> Cost: 255.2 OcQig (2.552E179) <p> Effect: Gain additional assistants based on your total time spent offline (in hours). <p> Formula: floor(2 * x^0.5), where x is your Time Spent Offline (Total) stat." coords="198,493,248,541" shape="rect">
<area target="" research="C330 - For Any - Spell Name: Overload <p> Requirement: Research Aeromancy (A250) &amp; Critical Strike (W225) <p> Cost: 6.443 Sxg (6.443E183) <p> Effect: Increase clicking reward based on the amount of research made. <p> Formula: round(145 * x^0.38)%, where x is researches made." coords="144,548,190,595" shape="rect">
<area target="" research="C340 - For Any Neutral - Spell Name: Gem Duster <p> Requirement: 800 Gem Grinders,Research Sifting (E260) &amp; Surveyorship (E290) <p> Cost: 371.5 Sxg (3.715E185) <p> Effect: Increase production bonus from gems based on the amount of Rubies you collected. (Multiplicative) <p> Formula: floor(10 * x), where x is your Rubies Gained (All Time) stat." coords="199,547,246,596" shape="rect">
<area target="" research="C375 - For Titan - Spell Name: Lightning Rod <p> Requirement: Research Chain Lightning (S300) &amp; Overload (C330) <p> Cost: 541 DSxg (5.41E191) <p> Effect: Olympian Halls are always hit by Lightning Strike in addition to the primary target. Olympian Halls can no longer be a primary target." coords="143,603,190,650" shape="rect">
<area target="" research="C400 - For Any - Spell Name: Gravitation <p> Requirement: Research Magnetism (C250) &amp; Weighting (C300) <p> Cost: 13.66 QaSxg (1.366E196) <p> Effect: Increase the chance to find Faction Coins based on the amount of Faction Coins found in this game. <p> Formula: floor(2 * ln(1+ x)^2.75)%, where x is your Faction Coins Gained (This Game) stat." coords="198,604,246,648" shape="rect">
<area target="" research="C405 - For Dwarf - Spell Name Metallurgy <p> Requirement: Underground Research upgrade <p> Cost: 103.7 QaSxg (1.037E197) <p> Effect: Increase Dwarven Forges based on the Dwarven Forges you own. <p> Formula: 45 * x^0.825%, where x is the number of Dwarven Forges you own." coords="143,657,191,706" shape="rect">
<area target="" research="C460 - For Any (Prestige Neutral) - Spell Name: Distribution <p> Requirement: 1M Clicks (this game) <p> Cost: 502.3 SpSxg (5.023E206) <p> Effect: Increase the production of non-unique buildings based on the amount of clicks you made in this game. <p> Formula: 35 * x^0.5%, where x is your Treasure Clicks (This Game) stat." coords="198,657,245,706" shape="rect">
<area target="" research="C500 - For Any - Spell Name: Minecrafting <p> Requirement: 3250 excavations (as Dwarf) <p> Cost: 5.554Spg (5.554E213) <p> Effect: Increases production bonus from gems based on the amount of excavations you made. <p> Formula: 3 * x^0.35%, where x is the amount of Excavations you made." coords="144,713,190,760" shape="rect">
<area target="" research="C520 - For Dwarf - Spell Name: Blacksmithing <p> Requirement: Research Reinforcing (C135) &amp; Metallurgy (C405) <p> Cost: 18.47 USpg (1.847E217) <p> Effect: Increase clicking reward for Diamond Pickaxe based on the amount of Dwarvin Forges you own. <p> Effect: Also increase Faction Coin find chance bonus of Diamond Pickaxe based on the amount of Dwarvin Forges you own. <p> Formula: Clicking Reward:2.5 * x^0.3%, Diamond Pickaxe:20 * x^0.4%; where x is the number of Dwarven Forges you own." coords="198,714,245,761" shape="rect">
<area target="" research="C590 - For Elf,Dwarf - Spell Name: Alloys <p> Requirement: 200 Dwarf Exchanges (as Dwelf), Research Fusion(A105) and Blacksmithing(C520) <p> Cost: 39.16 QiSpg (3.916E229) <p> Effect: Increase clicking reward based on your chance to find faction coins and autoclicks the treasure 10 times per second. <p> Formula: 0.85 * x^1.05%, where x is your Current Chance to find Faction Coins." coords="144,768,191,816" shape="rect">
<area target="" research="Divine<p>Harness the power of the eternals, increasing your spell affinity and bestowing Divine power on all your productivity. <p> Increases Angel, Faceless, and Dwarven production.<p>Pointing to this ingame will tell you how many slots are available also tells you your total research points." coords="276,36,344,102" shape="rect">
<area target="" research="D1 - For Angel - Spell Name: Blessing <p> Cost: 750 Qag (7.50E125) <p> Effect: Increase the production of Heaven's Domains based on total time spent with at least one active spell. <p> Formula: round(2.5 * x^0.8)%, where x is total time spent with at least one active spell." coords="258,107,306,155" shape="rect">
<area target="" research="D10 - For Demon - Spell Name: Inflame <p> Requirement: 2,000 Infernal Realms <p> Cost: 28.83 Uqag (2.883E127) <p> Effect: Increase the production of all other buildings by 110% per Infernal Realm you own." coords="314,106,361,155" shape="rect">
<area target="" research="D25 - For Undead - Spell Name: Cursing <p> Requirement: Play 8 hours Offline(as Undead) <p> Cost: 12.63 Dqag (1.263E130) <p> Effect: Increase the production of all buildings based on your offline production bonus. <p> Formula: round(0.5 * x0.3)%, where x is your offline production bonus." coords="258,163,306,210" shape="rect">
<area target="" research="D50 - For Elf - Spell Name: Hallowing <p> Requirement: 15,000 Good Buildings(as Angel) <p> Cost: 318.8 Tqag (3.188E134) <p> Effect: Increase your chance to find Faction Coins based on the amount of Elven Training Grounds you own. <p> Formula: floor(5 * x^0.85)%, where x is the number of Elven Training Grounds you own." coords="314,164,361,210" shape="rect">
<area target="" research="D55 - For Any - Spell Name: Transfixion <p> Requirement: Produce 3 M (3E6) Mana(This Game) <p> Cost: 2.421 Qaqag (2.421E135) <p> Effect: Increase clicking reward based on spell cast in this game. <p> Formula: round(3.5 * x^0.8)%, where x is your Spells Cast (This Game) stat." coords="259,220,306,265" shape="rect">
<area target="" research="D135 - For Any - Spell Name: Illumination <p> Requirement: 250 m/s Mana Regen(as Angel) <p> Cost: 296 Ocqag (2.96E149) <p> Effect: Increases mana regeneration based on the amount of gems you own. <p> Formula: floor(10 * ln(1 + x) / 7.5) / 10, where x is amount of gems you own." coords="314,218,361,265" shape="rect">
<area target="" research="D150 - For Any - Spell Name: Retribution <p> Requirement: Research Betrayal (W120) &amp; Transfixion (D55). <p> Cost: 129.6 Noqag (1.296E152) <p> Effect: Increase chance to find faction coins based on the amount of research made. <p> Formula: floor(0.2 * x^1.2), where x is the amount of research made." coords="259,275,305,317" shape="rect">
<area target="" research="D175 - For Angel - Spell Name: Resurrection <p> Requirement: Research Blessing (D1) &amp; Refraction (A55) <p> Cost: 3.273 Uqig (3.273E156) <p> Effect: You gain additional assistants based on the amount of God's hands cast. <p> Formula: floor(0.45 * (3x)^0.6), where x is God's Hands Cast This Game." coords="313,274,361,322" shape="rect">
<area target="" research="D200 - For Any - Spell Name: Transcendence <p> Requirement: Research Resurrection (D175) &amp; Illumination (D135) <p> Cost: 82.65 Dqig (8.265E160) <p> Effect: Decrease the cost of all spells by 20% and increase their duration by 20%." coords="258,329,306,375" shape="rect">
<area target="" research="D205 - For Any Good - Spell Name: Communion <p> Requirement: 777 Holy Lights (Total),Research Gemcutting (C175) &amp; Illumination (D135) <p> Cost: 627.6 Dqig (6.276E161) <p> Effect: Increase Holy Light duration by 110 seconds." coords="314,329,360,376" shape="rect">
<area target="" research="D225 - For Fairy - Spell Name: Weather Control <p> Requirement: Research Light Condenser (C25) &amp; Vacuumancy (S30) <p> Cost: 2.087 Qaqig (2.087E165) <p> Effect:Increase the production of Enchanted Fields based on maximum mana. <p> Formula: floor(2.25 * x^0.8)%, where x is your maximum mana." coords="258,384,305,430" shape="rect">
<area target="" research="D245 - For Any - Spell Name: Soulrending <p> Requirement: 500 Spiritual Surge, Research Soulweaving (A175) &amp; Necromancy (S225) <p> Cost: 6.94Qiqig (6.94E168) <p> Effect: Reincarnations count twice for Spiritual Surge." coords="313,382,360,429" shape="rect">
<area target="" research="D250 - For Any - Spell Name: Demonology <p> Requirement: Research Transcendence (D200) &amp; Pyromancy (S150) <p> Cost: 52.7 Qiqig (5.27E169) <p> Effect: Gain additional assistants based on the amount of Faction Coins found in this game. <p> Formula: floor(ln^1.3(1 + x)), where x is your Faction Coins Gained (This Game) stat." coords="259,438,305,486" shape="rect">
<area target="" research="D260 - For Faceless - Spell Name: Mutation <p> Requirement: 3,000 Sunken Cities <p> Cost: 3.039 SxQig (3.039E171) <p> Effect: Increase the production of all other buildings by 95% per Sunken Cities you own." coords="314,439,361,485" shape="rect">
<area target="" research="D275 - For Druid - Spell Name: Meditation <p> Requirement: Have 10,000 Mana (as Druid) <p> Cost: 1.331 SpQig (1.331E174) <p> Effect: Increase mana regeneration based on your current mana. <p> Formula: round(50 - \frac{x}{2})%, where x is percentage of your current mana." coords="258,493,306,540" shape="rect">
<area target="" research="D290 - For Any - Spell Name: Transubstantiation <p> Requirement: 1 Rough Stone Artifact <p> Cost: 582.7 SpQig (5.827E176) <p> Effect: Each artifact you discover increases mana regeneration by 1 m/s." coords="313,494,360,541" shape="rect">
<area target="" research="D320 - For Any - Spell Name: Deliverance <p> Requirement: 350 m/s Mana Regen <p> Cost: 1.117 NoQig (1.117E180) <p> Effect: Increase assistants production based on mana regeneration. <p> Formula: round(20 * x^0.85)%, where x is your Mana per Second stat." coords="258,547,306,595" shape="rect">
<area target="" research="D330 - For Any - Spell Name: Eternity <p> Requirement: Research Offering (E275) &amp; Deliverance (D320) <p> Cost: 6.443 Sxg (6.443E183) <p> Effect: Double the duration of all faction spells." coords="314,547,360,595" shape="rect">
<area target="" research="D350 - For Titan - Spell Name: Descent <p> Requirement: Research Swarming (W250) &amp; Heroism (W330) <p> Cost: 21.42 USxg (2.142E187) <p> Effect: Gain additional assistants based on the amount of Olympian Halls you own. <p> Formula: floor(x^0.5), where x is the number of Olympian Halls you own." coords="258,604,306,650" shape="rect">
<area target="" research="D400 - For Any - Spell Name: Miracle <p> Requirement: Research Communion (D205) &amp; Transubstantiation (D290) <p> Cost: 13.66 QaSxg (1.366E196) <p> Effect: Increase the Production of a random building by x250. Target changes every 2 minutes. While offline, increase the production of all buildings by x75." coords="314,603,361,651" shape="rect">
<area target="" research="D435 - For Dwarf - Spell Name: Devotion <p> Requirement: 4h Diamond Pickaxe Cast Time (This Game) <p> Cost: 19.89 SxSxg (1.989E202) <p> Effect: Increase the production of Good buildings based on spells cast in this game. <p> Formula: 2.5 * x^0.85%, where x is your Spells Cast (This Game) stat." coords="257,659,305,706" shape="rect">
<area target="" research="D480 - For Any - Spell Name: Mercy <p> Requirement: 12h Spent as each Good, Evil and Neutral alignment (This Reincarnation) <p> Cost: 1.67 NoSxg (1.67E210) <p> Effect: Increase the production of all buildings based on the difference in time spent with the three alignments. A smaller difference produces a higher bonus. <p> Formula: 100000 * (min_time / max_time)^1.5%, where tmin and tmax are the shortest and longest Time Spent Being Alignment (Total) Stat." coords="314,657,361,704" shape="rect">
<area target="" research="D525 - For Good - Spell Name: Purity <p> Requirement: 1d12h as Good(Current R), Research Communion(D205) and Devotion(D435) <p> Cost: 140.2 USpg (1.402E218) <p> Effect: Increase Holy Light multiplier based on the amount of times you cast your faction spell in this game. <p> Formula: 300 * x^0.3%p, where x is your Faction Spells' Cast This Game (Vanilla + Prestige spell count) stat." coords="257,713,306,761" shape="rect">
<area target="" research="D560 - For Drow - Spell Name: Ritualism <p> Requirement: Research Necromancy(S225) and Heirlooms(S500)(as drow) <p> Cost: 204.2 TSpq (2.042E224) <p> Effect: Increase mana regeneration based on the amount of trophies you unlocked. <p> Formula: floor(0.7x) / 10, where x is the amount of Trophies Unlocked." coords="314,712,361,760" shape="rect">
<area target="" research="D590 - For Angel,Dwarf - Spell Name: Dispelling <p> Requirement: 200 Dwarf Exchanges as Dwangel, Research Shattering (W320) and Waste (A480) <p> Cost: 39.16 QiSpg (3.916E229) <p> Effect: Increase the production of Unique buildings based on mana regeneration. <p> Formula: 2.5 x^1.25%, where x is your Mana per Second stat." coords="258,768,306,817" shape="rect">
<area target="" research="Economics<p>Exploit your resources with Economics knowledge, taking maximum advantage of your properties and turning time into money. <p> Increases Goblin, Druid, and Dwarven production.<p>Pointing to this ingame will tell you how many slots are available also tells you your total research points." coords="389,36,457,102" shape="rect">
<area target="" research="E1 - For Goblin - Spell Name: Coinage <p> Cost: 750 Qag (7.50E125) <p> Effect: Increase the production of Goblin Banks based on the amount of buildings you own. <p> Formula: round(0.5 * x^0.8)%, where x is your Buildings Owned (This Game) stat." coords="374,109,420,155" shape="rect">
<area target="" research="E10 - For Undead - Spell Name: Recycling <p> Requirement: 2,000 Undercities <p> Cost: 28.83 Uqag (2.883E127) <p> Effect: Increase the production of all other buildings by 95% per Undercity you own." coords="428,108,476,155" shape="rect">
<area target="" research="E25 - For Elf - Spell Name: Commerce <p> Requirement: 100 M (1E8) Faction Coins<p>  Cost: 12.63 Dqag (1.263E130) <p> Effect: Gain additional assistants based on the amount of Royal Exchanges you purchased. <p> Formula: floor((1 + 6x)^0.5 - 1), where x is your Royal Exchanges Made stat." coords="373,161,420,210" shape="rect">
<area target="" research="E30 - For Any - Spell Name: Diplomacy <p> Requirement: 1000 Exchanges <p> Cost: 95.88 Dqag (9.588E130) <p> Effect: Increases Faction Coin find chance and Royal Exchange bonus based on time spent in this game. <p> Formula: Faction Coin Chance:floor(15 * x^1.05)% Royal Exchange bonus:floor(7 * x^0.6)%, where x is Playtime (This Game in hours)." coords="428,164,475,209" shape="rect">
<area target="" research="E50 - For Fairy - Spell Name: Bartering <p> Requirement: 1,000 Exchanges(as Goblin) <p> Cost: 318.8 Tqag (3.188E134) <p> Effect: Reduce Enchanted Field cost multiplier. Reduces cost multiplier by 0.035; with no other reductions applying, the multiplier will be 1.115 instead of 1.15." coords="373,218,421,265" shape="rect">
<area target="" research="E80 - For Any - Spell Name: Common Business <p> Requirement: 9,000 Neutral Buildings <p> Cost: 61.13 Qiqag (6.113E139) <p> Effect: Increase the production of Good and Evil buildings based on the amount of neutral buildings. <p> Formula: round((1.75 * x)^0.8)%, where x is the number of neutral buildings you own." coords="428,218,477,266" shape="rect">
<area target="" research="E135 - For Any - Spell Name: Bribing <p> Requirement: 28,000 Total Buildings(as Goblin) <p> Cost: 296 Ocqag (2.96E149) <p> Effect: Reduce the building cost multiplier for Unique Buildings. Reduces cost multiplier by 0.02; with no other reductions applying, the multiplier will be 1.13 instead of 1.15." coords="373,274,420,321" shape="rect">
<area target="" research="E145 - For Any - Spell Name: Royal Demand <p> Requirement: 5,000 Tax Collections (Total), Research Cultivation (C10) &amp; Woodcraft (C105) <p> Cost: 17.07 Noqag (1.707E151) <p> Effect: Increase Tax Collection reward by 30 seconds of production." coords="429,273,475,319" shape="rect">
<area target="" research="E150 - For Any - Spell Name: Investment <p> Requirement: Research Bribing (E135) &amp; Commerce (E25) <p> Cost: 129.6 Noqag (1.296E152) <p> Effect: Increase the production of all buildings based on the amount of gold you own. <p> Formula: round( (ln(1 + x)) ^1.25 )%, where x is the amount of gold you own." coords="373,330,420,374" shape="rect">
<area target="" research="E200 - For Any - Spell Name: Acquisition <p> Requirement: Research Investment (E150) &amp; Common Business (E80) <p> Cost: 82.65 Dqig (8.265E160) <p> Effect: Increase the production of all buildings based on your percentage of trophies unlocked. <p> Formula: round(0.0003 * (100 * x)^3.35), where x is trophiesunlocked / trophiesmax." coords="428,327,475,375" shape="rect">
<area target="" research="E225 - For Goblin - Spell Name: Forgery <p> Requirement: Research Coinage (E1) &amp; Gilding (A50) <p> Cost: 2.087 Qaqig (2.087E165) <p> Effect: Increase the production of Evil Buildings based on the amount of Goblin Banks you own. <p> Formula: round(10 * x^0.85)%, where x is the number of Goblin Banks you own." coords="373,383,421,428" shape="rect">
<area target="" research="E230 - For Demon - Spell Name: Coercion <p> Requirement: Research Exertion (W50) &amp; Diplomacy (E30) <p> Cost: 2.087 Qaqig (2.087E165) <p> Effect: Increase the production of Infernal Realms based on total time spent being Evil. <p> Formula: round(0.2 * x^0.7)%, where x is your Time Spent Being Evil (Total) stat." coords="428,383,476,431" shape="rect">
<area target="" research="E250 - For Any - Spell Name: Trade Routes <p> Requirement: Research Forgery (E225) &amp; Royal Demand (E145) <p> Cost: 52.7 Qiqig (5.27E169) <p> Effect: Increase mana regeneration based on the amount of Royal Exchanges you purchased. <p> Formula: floor(10 * x^0.5) / 10, where x is your Royal Exchanges Made stat." coords="374,438,421,485" shape="rect">
<area target="" research="E260 - For Druid - Spell Name: Sifting <p> Requirement: 3,000 Stonehenge Circles <p> Cost: 3.039 SxQig (3.039E171) <p> Effect: Increase the production of all other buildings by 80% per Stonehenge Circle you own." coords="429,438,475,485" shape="rect">
<area target="" research="E275 - For Titan - Spell Name: Offering <p> Requirement: 1,250 Royal Exchanges(as Titans) <p> Cost: 175.2 SxQig (1.752E173) <p> Effect: Increase mana regeneration based on your Royal Exchange Bonus. <p> Formula: floor(0.9 * x^0.95), where x is your Royal Exchange Bonus." coords="374,494,421,541" shape="rect">
<area target="" research="E290 - For Any - Spell Name: Surveyorship <p> Requirement: 7 Artifacts <p> Cost: 582.7 SpQig (5.827E176) <p> Effect: Reduce Excavation cost multiplier.Reduces cost multiplier by 0.025; with no other reductions applying, the multiplier will be 1.175 instead of 1.2." coords="429,493,476,539" shape="rect">
<area target="" research="E320 - For Any - Spell Name: Smuggling <p> Requirement: Have 2x Gems in Abdication Treasury <p> Cost: 1.117 NoQig (1.117E180) <p> Effect: Increase production bonus from gems based on the gems you have in your abdication treasury. <p> Formula: floor(0.45 * log(1+ x)), where x is the amount of gems you will gain upon abdication." coords="373,548,420,595" shape="rect">
<area target="" research="E330 - For Any - Spell Name: Collection <p> Requirement: Research Acquisition (E200) &amp; Forgery (E225a) <p> Cost: 6.443 Sxg (6.443E183) <p> Effect: Increase the production of all buildings based on the amount of artifacts you found. <p> Formula: round(50 * x^1.1)%, where x is the amount of artifacts found." coords="429,548,475,595" shape="rect">
<area target="" research="E350 - For Faceless - Spell Name: Repurpose <p> Requirement: Research Journeymen (C200) &amp; Adaptation (A330)(as Faceless) <p> Cost: 21.42 USxg (2.142E187) <p> Effect: Increase the production of all buildings based on the amount of Reincarnations you made. <p> Formula: round(2.5 * x^2.25)%, where x is the amount of times you reincarnated." coords="374,604,420,649" shape="rect">
<area target="" research="E400 - For Any - Spell Name: Conversion <p> Requirement: Research Philosopher's Stone (A250) &amp; Repurpose (E350). <p> Cost: 13.66 QaSxg (1.366E196) <p> Effect: Increase production bonus from Gems based on your Royal Exchange bonus. <p> Formula: floor(x^0.95)%, where x is your Royal Exchange Bonus." coords="428,604,475,649" shape="rect">
<area target="" research="E410 - For Dwarf - Spell Name: Marketing <p> Requirement: 5000 Blacksmiths <p> Cost: 787.7 QaSxg (7.877E197) <p> Effect: Increase production of all other buildings by 85% per Dwarven Forge you own." coords="373,656,421,705" shape="rect">
<area target="" research="E460 - For Any - Spell Name: Inflation <p> Requirement: 100B (1E11) Faction Coins <p> Cost: 502.3 SpSxg (5.023E206) <p> Effect: Increase Royal Exchange Bonus based on the amount of Faction Coins found in this game. <p> Formula: floor(3.5 * log(1 + x))%p, where x is your Faction Coins Gained (This Game) stat." coords="428,659,476,706" shape="rect">
<area target="" research="E480 - For Any - Spell Name: Undercutting <p> Requirement: 15000 max mana <p> Cost: 1.67 NoSxg (1.67E210) <p> Effect: Increase the production of non-unique buildings based on total spells cast. <p> Formula: 0.65 * x^0.65%, where x is your Spells Cast (Total) stat." coords="373,714,421,761" shape="rect">
<area target="" research="E495 - For Drow - Spell Name: Jewellery <p> Requirement: 12000 Unique Buildings (as Dwarf) <p> Cost: 731.4 NoSxg (7.314E212) <p> Effect: Increase the production bonus from gems based on the amount of Spider Sanctuaries you own. <p> Formula: x^0.8 / 20%p, where x is the number of Spider Sanctuaries you own." coords="429,713,477,762" shape="rect">
<area target="" research="E590 - For Goblin,Drow - Spell Name: Slavery <p> Requirement: 200 Drow Exchanges as Droblin, Research Automatons(C225) and Undercutting(E480) <p> Cost: 39.16 QiSpg (3.916 E229) <p> Effect: Gain additional assistants based on the amount of Evil buildings you own. <p> Formula: floor ((x / 300)1.05), where x is the number of Evil Buildings you own." coords="373,766,421,816" shape="rect">
<area target="" research="Alchemy<p>Tap the near-unlimited sources of Alchemy to improve your production and benefit from all your assets. <p> Increases Undead, Druid, and Drow production.<p>Pointing to this ingame will tell you how many slots are available also tells you your total research points." coords="504,36,573,102" shape="rect">
<area target="" research="A1 - For Undead - Spell Name: Plague <p> Cost: 750 Qag (7.50E125) <p> Effect: Increase the production of Undercities by 8% per assistant you own." coords="487,108,537,156" shape="rect">
<area target="" research="A10 - For Goblin - Spell Name: Transmutation <p> Requirement: 2250 Goblin Banks <p> Cost: 28.83 Uqag (2.883E127) <p> Effect: Increase the production of all other buildings by 85% per Goblin Bank you own." coords="544,108,590,154" shape="rect">
<area target="" research="A25 - For Demon - Spell Name: Deflagration <p> Requirement: 666 Hellfire Blasts (Total)<p> Cost: 12.63 Dqag (1.263E130) <p> Effect: Reduces Hellfire Blast duration by 16 seconds, reduces its mana cost by 200 and multiplies its effect by x7." coords="489,163,535,209" shape="rect">
<area target="" research="A30 - For Fairy - Spell Name: Delayed Reaction <p> Requirement: 750 Fairy Chanting (Total) <p> Cost: 12.63 Dqag (1.263E130) <p> Effect: Increases duration of Fairy Chanting based on the amount of Enchanted Fields, Inns and Blacksmiths you own and provides a progressively increasing bonus to the spell.<p>Formula: Production increase: floor(10 * ceil^1.5(t)); Duration increase: floor(x / 1500) seconds; where t is how long FC has been active in seconds, and x is the number of Farms, Inns, and Blacksmiths you own." coords="544,163,591,211" shape="rect">
<area target="" research="A50 - For Angel - Spell Name: Gilding <p> Requirement: 120 m/s Mana Regen(as Undead) <p> Cost: 318.8 Tqag (3.188E134) <p> Effect: Heaven's Domains further increase your mana regeneration rate. <p> Formula: 1.45 * x^0.45, where x is the number of Heaven's Domains you own." coords="487,219,537,266" shape="rect">
<area target="" research="A55 - For Any - Spell Name: Refraction <p> Requirement: Cast 25000 spells (This Game) Cost: 2.421 Qaqag (2.421E135) <p> Effect: Improve offline production based on spells cast. <p> Formula: round 3 * x^0.85%, where x is your Spells Cast (Total) stat." coords="543,217,590,266" shape="rect">
<area target="" research="A105 - For Any - Spell Name: Fusion <p> Requirement: 2750 Blacksmiths <p> Cost: 1.544 Spqag (1.544E144) <p> Effect: Increases the production of buildings based on the amount of Faction Coins found this game. <p> Formula: round(0.7 * ln^3(1 + x))%, where x is your Faction Coins Gained (This Game) stat." coords="489,274,536,320" shape="rect">
<area target="" research="A120 - For Any - Spell Name: Vivification <p> Requirement: Have 6500 mana <p> Cost: 676 Spqag (6.76E146) <p> Effect: Gain additional assistants based on max mana. <p> Formula: floor(x / 50), where x is your maximum mana.<p>Tip: Use Fairy with Faceless bloodline." coords="543,273,590,320" shape="rect">
<area target="" research="A135 - For Any - Spell Name: Decay <p> Requirement: 1 Day Total Play Time any Faction (Must be Undead to unlock once condition is met.)<p>Cost: 296 OcQag (9.6E149) <p> Effect: Increase the production on all buildings based on total time spent. <p> Formula: round(c * x^0.7)%, where x is your Playtime (Total) in seconds stat and c is 0.03(2^0.7), which is approximately 0.049." coords="488,327,536,375" shape="rect">
<area target="" research="A150 - For Any - Spell Name: Explosives <p> Requirement: Research (A25) Deflagration & (A30) Delayed Reaction <p> Cost: 129.6 Noqag (1.296E152) <p> Effect: Whenever you cast a spell, increase the production of your most productive building based on the amount of mana produced in this game for 20 seconds. If another spell is cast while this effect is active, it is restored to full duration. <p> Formula: round(0.7 * x^0.6)%, where x is your Mana Produced (Total) stat." coords="544,328,590,374" shape="rect">
<area target="" research="A175 - For Undead - Spell Name: Soulweaving <p> Requirement: Research Cursing (D25) &amp; Reinforcing (C135) <p> Cost: 3.273 Uqig (3.273E156) <p> Effect: Increase the production of all buildings based on the amount of times you Reincarnated. <p> Formula: round(2.5 * x^2.25)%, where x is the amount of times you reincarnated." coords="488,384,537,431" shape="rect">
<area target="" research="A200 - For Any - Spell Name: Corrosion <p> Requirement: Research Plague (A1) &amp; Decay (A135) <p> Cost: 82.65 Dqig (82.65E160) <p> Effect: Increase clicking reward based on time spent in this game. <p> Formula: round(c * x^0.75)%, where x is your Playtime (Total) in seconds stat and c is 0.07(2^0.75), which is approximately 0.118." coords="544,383,591,430" shape="rect">
<area target="" research="A250 - For Any - Spell Name: Philosopher's Stone <p> Requirement: Research Transmutation (A10) &amp; Empowered Luck (S175) <p> Cost: 52.7 Qiqig (5.27E169) <p> Effect: Increase production bonus from gems based on the amount of research made. <p> Formula: floor(x^0.9 / 25)%, where x is the amount of research made." coords="489,440,536,484" shape="rect">
<area target="" research="A251 - For Druid - Spell Name: Infusion <p> Requirement: Play as Druid <p> Cost: 79.05 QiQig (7.905E169) <p> Effect: Increase the production of Stonehenge Circles based on mana produced in this game. <p> Formula: round(0.75 * x ^0.6)%, where x is your Mana Produced (This Game) stat." coords="544,439,591,485" shape="rect">
<area target="" research="A270 - For Any - Spell Name: Synthesis <p> Requirement: 20 B (2E10) Faction Coins(This game) <p> Cost: 175.2 SxQig (1.752E173) <p> Effect: Increase mana regeneration based on the amount of Faction Coins found in this game. <p> Formula: floor(15 * ln(1 + x)) / 10, where x is your Faction Coins Gained (This Game) stat." coords="487,494,536,539" shape="rect">
<area target="" research="A300 - For Faceless - Spell Name: Creeping <p> Requirement: Produce 5M mana(This game, as Druid) <p> Cost: 33 OcQig (3.36E178) <p> Effect: Increase mana regeneration based on mana produced in this game. <p> Formula: floor(10 * (1.5 * ln(1 + x))) / 10, where x is your Mana Produced (This Game) stat." coords="544,494,591,540" shape="rect">
<area target="" research="A305 - For Any - Spell Name: Engraving <p> Requirement: 5 days as Druids (Total across all Rs)<p> Cost: 255.2 OcQig (2.552E179) <p> Effect: Increase your chance to find Faction Coins based on the amount of spells cast in this game. <p> Formula: floor(ln^{2.75} (1 + 2x))%, where x is your Spells Cast (This Game) stat., or approximately<p> Formula: floor((ln(x) + 0.69)^{2.75})%, where x is your Spells Cast (This Game) stat." coords="489,548,536,596" shape="rect">
<area target="" research="A330 - For Any - Spell Name: Adaptation <p> Requirement: Research Mutation (D260) &amp; Meditation (D275) <p> Cost: 6.443 Sxg (6.443E183) <p> Effect: Increase the production of all buildings based on time spent playing as other factions. <p> Formula: round(0.05 * x^0.7)%, where x is time spent as other factions." coords="544,550,591,595" shape="rect">
<area target="" research="A375 - For Druid - Spell Name: Transfusion <p> Requirement: Research Infusion (A251) &amp; Engraving (A305) <p> Cost: 541 DSxg (5.41E191) <p> Effect: Gain additional assistants based on mana produced this game. <p> Formula: floor(4.5 * ln(1 + x)), where x is your Mana Produced (This Game) stat." coords="487,601,536,651" shape="rect">
<area target="" research="A400 - For Any - Spell Name: Bloodspring <p> Requirement: Research Assimilation (S251) &amp; Transfusion (A375). <p> Cost: 13.66 QaSxg (1.366E196) <p> Effect: You get your faction's Bloodline effect for free. Bloodstream counts time spent with both factions. <b>NOTE</b>: Does not work with two Bloodlines of the same type." coords="544,602,591,651" shape="rect">
<area target="" research="A410 - For Drow - Spell Name: Poisons <p> Requirement: 4000 Sanctuaries Cost: 787.7 QaSxg (7.877E197) <p> Effect: Increase the production of all other buildings by 95% per Spider Sanctuary you own." coords="488,658,536,706" shape="rect">
<area target="" research="A480 - For Any - Spell Name: Waste <p> Requirement: 2000 Royal Exchanges <p> Cost: 1.67 NoSxg (1.67E210) <p> Effect: Increase offline production based on the amount of Royal Exchanges you purchased. <p> Formula: 80 * x^0.8%, where x is your Royal Exchanges Made stat." coords="544,658,590,706" shape="rect">
<area target="" research="A495 - For Dwarf - Spell Name: Elixirs <p> Requirement: 500 Base Assistants (as Drow) <p> Cost: 731.4 NoSxg (7.314E212) <p> Effect: Increase assistants production based on the amount of research made. <p> Formula: 120 * x^0.42%, where x is the Amount of Researches made." coords="488,713,537,761" shape="rect">
<area target="" research="A545 - For Any - Spell Name: Mineralogy <p> Requirement: 700 trophies <p> Cost: 466.3 DSpg (4.663E221) <p> Effect: Increase the production of all buildings based on the amount of rubies you own. <p> Formula: 10 * x^1.05%, where x is your Rubies Gained (All Time) stat." coords="544,713,591,762" shape="rect">
<area target="" research="A590 - For Undead,Drow - Spell Name: Hexing <p> Requirement: 200 Drow Exchanges as Drodead, Research Cursing (D25) and Poisons (A410) <p> Cost: 39.16 QiSpg (3.916E229) <p> Effect: Increase the production of all buildings based on mana produced and the percentage of offline time spent in this game. <p> Formula: 0.045 * x^0.45 * p%, where x is your Mana Produced (This Game) stat and p is the percentage of your Time Spent Offline for this game." coords="489,768,536,816" shape="rect">
<area target="" research="Warfare<p>Use strategical prowess and manpower tp manipulate the production system in your favor. <p> Increases: Demon, Titan, and Drow production.<p>Pointing to this ingame will tell you how many slots are available also tells you your total research points." coords="619,34,687,102" shape="rect">
<area target="" research="W1 - For Demon - Spell Name: Assault <p> Cost: 750 Qag (7.50E125) <p> Effect: Increase the production of Infernal Realms based on the amount of Hellfire Blasts cast in this game. <p> Formula: round(70 * x^0.55)%, where x is Hellfire Blasts Cast This Game." coords="604,108,650,156" shape="rect">
<area target="" research="W10 - For Elf - Spell Name: Dueling <p> Requirement: 2000 Warrior Barracks Cost: 28.83 Uqag (2.883E127) <p> Effect: Increase the production of all other buildings by 90% per Elven Training Grounds you own." coords="659,108,705,155" shape="rect">
<area target="" research="W25 - For Goblin - Spell Name: War Funds <p> Requirement: 1 Tqag (1E132) Coins Gained (This Game) <p> Cost: 12.63 Dqag (1.263E130) <p> Effect: Increase the production of all buildings based on the amount of Tax Collections cast in this game. <p> Formula: round(5 * x^0.6)%, where x is Tax Collections Cast This Game." coords="604,163,651,210" shape="rect">
<area target="" research="W50 - For Undead - Spell Name: Exertion <p> Requirement: 2 days of Evil Play Time, Note: Play as any Evil faction, but you must be Demon to unlock this. <p> Cost: 318.8 Tqag (3.188E134) <p> Effect: Increase faction coin find chance based on the number of Undercities you own. <p> Formula: (floor(6.5x^0.65))%, where x is the number of Undercities you own." coords="659,161,707,211" shape="rect">
<area target="" research="W120 - For Any - Spell Name: Betrayal <p> Requirement: 250 base assistants <p> Cost: 676 Spqag (6.76E146) <p> Effect: Increase the production of non-unique buildings based on the amount of assistants you own. <p> Formula: round(1.5 * x^1.5)%, where x is the amount of assistants you own." coords="604,217,650,265" shape="rect">
<area target="" research="W135 - For Any - Spell Name: Rampage <p> Requirement: 580 Trophies(as Demon) <p> Cost: 296 Ocqag (9.6E149) <p> Effect: Increase maximum mana based on the number of trophies you have unlocked. <p> Formula: floor(1.25x), where x is the amount of trophies unlocked." coords="659,217,706,265" shape="rect">
<area target="" research="W150 - For Any - Spell Name: Invasion <p> Requirement: Research War Funds (W25) &amp; Trophies (W135) <p> Cost: 129.6 Noqag (1.296E152) <p> Effect: Increase the production of all buildings based on the amount of assistants you own. <p> Formula: round(32 * x^0.75)%, where x is the amount of assistants you own." coords="604,273,651,320" shape="rect">
<area target="" research="W175 - For Demon - Spell Name: Overwhelm <p> Requirement: Research Assault (W1) &amp; Invasion (W150) <p> Cost: 3.273 Uqig (3.273E156) Effect: You gain additional assistants based on total amount of evil spells cast. <p>Formula: floor(0.75 * x^0.55), where x is the amount of evil spells cast." coords="659,272,706,321" shape="rect">
<area target="" research="W180 - For Any - Spell Name: Formation <p> Requirement: 1000 Call to Arms (Total) Research Dueling (W10) &amp; Exertion (W50) <p> Cost: 24.85 Uqig (2.485E157) <p> Effect: Each building counts 15 times for Call to Arms purposes." coords="603,327,651,376" shape="rect">
<area target="" research="W200 - For Any - Spell Name: Crusade <p> Requirement: Research Hallowing (D50) &amp; Formation (W180) <p> Cost: 82.65 Dqig (8.265E160) <p> Effect: Gain additional assistants based on total time spent as Good. <p> Formula: floor(0.065 * x^0.5), where x is your Time Spent Being Good (Total) stat." coords="658,328,706,376" shape="rect">
<area target="" research="W205 - For Any Evil - Spell Name: Berserking <p> Requirement: 850 Blood Frenzy, Research Rampage (W135) &amp; Retribution (D150) <p> Cost: 627.6 Dqig (6.276E161) <p> Effect:While Blood Frenzy is active, increase mana regeneration based on the amount of assistants you own.<p>Formula: floor(4.5 * x^0.95) / 10, where x is your Assistants stat." coords="604,383,651,431" shape="rect">
<area target="" research="W225 - For Angel - Spell Name: Critical Strike <p> Requirement: Research Dueling (W10) &amp; Transfixion (D55) Cost: 2.087 Qaqig (2.087E165) <p> Effect: Holy Light empowers Heaven’s Domains based on Holy Light activity time in this game. <p> Formula: 5 * x^0.65%, where x is Holy Light Active Time This Game in seconds." coords="659,382,706,430" shape="rect">
<area target="" research="W250 - For Any - Spell Name: Swarming <p> Requirement: Research Overwhelm (W175) &amp; Berserking (W205) <p> Cost: 52.7 Qiqig (5.27E169) <p> Effect: Gain additional assistants based on the amount of trophies you unlocked. <p> Formula: floor(x / 8), where x is the amount of trophies unlocked." coords="604,439,651,485" shape="rect">
<area target="" research="W260 - For Titan - Spell Name: Athletics <p> Requirement: 3,000 Olympian Halls <p> Cost: 3.039 SxQig (3.039E171) <p> Effect: Increase the production of all other buildings by 100% per Olympian Hall you own." coords="658,438,705,485" shape="rect">
<area target="" research="W275 - For Faceless - Spell Name: Domination <p> Requirement: 300 Base Assistants (as Faceless) <p> Cost: 1.331 SpQig (1.331E174) <p> Effect: Gain additional Faction Coins per second based on the highest amount of assistants you had in a single game. <p> Formula: floor(1.5 * x^1.15), where x is your Assistants (Max) stat." coords="603,495,651,539" shape="rect">
<area target="" research="W290 - For Any - Spell Name: Entrench <p> Requirement: 2,000 Excavations <p> Cost: 582.7 SpQig (5.827E176) <p> Effect: Increase the production of Unique buildings based on the amount of Excavations you made. <p> Formula: round(15 * x^0.8)%, where x is the amount of excavations made." coords="658,493,707,539" shape="rect">
<area target="" research="W320 - For Any - Spell Name: Shattering <p> Requirement: 2,750 Excavations <p> Cost: 1.117 NoQig (1.117E180) <p> Effect: Increase your clicking reward based on the amount of Excavations you made. <p> Formula: round(10 * x^0.75)%, where x is the amount of excavations made." coords="603,548,651,595" shape="rect">
<area target="" research="W330 - For Any - Spell Name: Heroism <p> Requirement: Research Crusade (W200) &amp; Athletics (W260). <p> Cost: 6.443 Sxg (6.443E183) <p> Effect: Increase your click reward based on the amount of trophies you unlocked. <p> Formula: round(2.5 * x)%, where x is the amount of trophies unlocked." coords="659,550,705,595" shape="rect">
<area target="" research="W350 - For Druid - Spell Name: Survival <p> Requirement: Research Creeping (A300) &amp; Synthesis (A270). <p> Cost: 21.42 USxg (2.142E187) <p> Effect: Increase the production of all other buildings based on the production of your Stonehenge Circles. <p> Formula: round(50 * log^1.3(1 + x))%, where x is the production of your Stonehenge Circles." coords="603,603,651,651" shape="rect">
<area target="" research="W400 - For Any - Spell Name: Siege <p> Requirement: Research Architecture (C251) &amp; Entrench (W290). <p> Cost: 13.66 QaSxg (1.366E196) <p> Effect: Each building in the three highest building tiers count as 2 buildings for all purposes. (All purposes in the build. Does not work for Trophies.)" coords="659,604,705,651" shape="rect">
<area target="" research="W405 - For Drow - Spell Name: Ambush <p> Requirement: Secret Underground upgrade (as Drow) <p> Cost: 103.7 QaSxg (1.037E197) <p> Effect: Increase the production of Spider Sanctuaries based on offline Bonus <p> Formula: 2.5 * x^0.225%, where x is Offline Production Bonus." coords="604,659,651,706" shape="rect">
<area target="" research="W520 - For Drow - Spell Name: Stalking <p> Requirement: Research Exertion (W50) and Ambush (W405) <p> Cost: 18.47 Uspg (1.847E217) <p> Effect: Gain 1 assistant for every 100 seconds of Combo Strike activity time. (This Game)" coords="657,659,706,704" shape="rect">
<area target="" research="W525 - For Any - Spell Name: Bloodlust <p> Requirement: 1d12h as Evil, Research Berserking (W205) and Spellcraft (S460) <p> Cost: 140.2 USpg (1.402E218) <p> Effect: Increase Blood Frenzy multiplier based on the amount of times you cast faction spell in this game. <p> Formula: 300 * floor(x^0.3)%p, where x is Faction Spells' Cast This Game (Vanilla + Prestige spell count)." coords="604,714,651,760" shape="rect">
<area target="" research="W560 - For Dwarf - Spell Name: Resilience <p> Requirement: Research Eternity (D330) and Mercy (D480) <p> Cost: 204.2 TSpg (2.042E224) <p> Effect: Increase clicking reward based on the amount of clicks made in this game. <p> Formula: 5 * x^0.45%, where x is your Treasure Clicks (This Game) stat." coords="660,713,706,761" shape="rect">
<area target="" research="W590 - For Demon,Drow - Spell Name: Torture <p>Requirement: 200 Drow Exchanges as Dromon, Research Soulrending (D245) and Stalking (W520) <p> Cost: 39.16 QiSpg (3.916E229) <p> Effect: Increase assistants production based on total time spent being Evil. <p> Formula: 8 * x^0.8%, where x is your Time Spent Being Evil stat." coords="603,767,650,815" shape="rect">
<area target="" research="S1275 - For Any - Spell Name: Sequence<p>Requirement: 60.000 spells cast.<p>Cost: 555.1 Dvg (5.551E71)<p>Effect: Reduce spell cost for higher spell tiers.<p>Formula: Reduces cost multiplier by 0.5; with no other reductions applying, the multiplier will be 1.5 instead of 2.</p>" coords="85,769,129,814" shape="rect">
<area target="" research="S1450 - For Neutral,Dragon - Spell Name: Spellstorm <p>Requirement: Research S435, C1325, Any Neutral,Dragon<p>Cost: 23.26 Sxvg (2.326E82)<p>Effect: Increase the production of Unique buildings based on the amount of active spells.<p>Formula: 10 * x^2, x is number of active spells, counting tiers.</p>" coords="31,822,77,869" shape="rect">
<area target="" research="S1500 - For Faceless,Dragon - Spell Name: Psionics<p>Requirement: 1000 Base Assistants, Research S545, E1325, Faceless,Dragon<p>Cost: 25 Spvg (2.52E85)<p>Effect: Increase the production of Unique Buildings based on the amount of assistants you own.<p>Formula: 3.75 * x^1.05, x is assistants.</p>" coords="85,822,131,868" shape="rect">
<area target="" research="C1300 - For Neutral,Dragon - Spell Name: Scintillation<p>Requirement: 30000 Max Mana, Any Neutral,Dragon (This game)<p>Cost: 18.27 Tvg (1.827E73)<p>Effect: Increase production bonus from gems based on maximum mana.<p>Formula: 2 * x^0.4, x is max mana" coords="199,767,244,815" shape="rect">
<area target="" research="C1325 - For Any - Spell Name: Plasmation<p>Requirement: 50m (50e6) Mana Produced (This game)<p>Cost: 601.6 Tvg (6.016E74)<p>Effect: Gain assistants based on mana produced in this game.<p>Formula: floor(1.25 * ln(1 + x)^2), x is mana produced (this game)." coords="144,823,191,868" shape="rect">
<area target="" research="C1500 - For Titan,Dragon - Spell Name: Gargantuaness<p>Requirement: 2500 Royal Exchanges Research E460, D1275 (As Titans)<p>Cost: 25 Spvg (2.52E85)<p>Effect: Increase the production of all buildings based on total time spent as Neutral.<p>Formula: (1.5 * x)^0.7, x is neutral time (this R) in minutes." coords="199,823,245,869" shape="rect">
<area target="" research="D1125 - For Neutral,Dragon - Spell Name: Oblation<p>Requirement: Any Neutral,Build Dragons' Unique Building<p>Cost: 436.2 Nod (4.362E62)<p>Effect: Increase the production of Wyrm's Den based on Faction Coin find chance.<p>Formula: 1.5 * x^0.5, x is faction coin find chance in percent." coords="315,769,359,814" shape="rect">
<area target="" research="D1275 - For Any - Spell Name: Solemnity<p>Requirement: 100000 Total Buildings<p>Cost: 555.1 Dvg (5.551E71)<p>Effect: Increase the production of each building by + 0.25.to Fixed(2) + % per building of the same type." coords="260,826,305,868" shape="rect">
<area target="" research="D1375 - For Any - Spell Name: Sanctification<p>Requirement: 24 hours spent as good<p>Cost: 651.9 Qavg (6.519E77)<p>Effect: Increase the production of Unique Buildings based on the amount of Non-Unique buildings you own.<p>Formula: 2 * x^0.55, x is non-unique building owned." coords="317,825,360,869" shape="rect">
<area target="" research="E1225 - For Neutral,Dragon - Spell Name: Hoarding<p>Requirement: 1T (1E12) Faction coins<p>Cost: 512.3 Uvg (5.123E68)<p>Effect: Reduce Ascension penalty for Royal Exchanges.<p>Formula: ((((((bonus per RE as %)^2(if E1225))*number of REs)/100)+1)^0.1." coords="431,769,475,812" shape="rect">
<area target="" research="E1325 - For Any - Spell Name: Intimidation<p>Requirement: 18000 Unique Buildings<p>Cost: 601.6 Tvg (6.016E74)<p>Effect: Reduce Royal Exchange cost multiplier.<p>Formula: Reduces multiplier by 0.025; with no other reductions applying, base multiplier is 1.1" coords="377,826,419,870" shape="rect">
<area target="" research="E1425 - For Any Neutral - Spell Name: Rarity<p>Requirement: 2592000(seconds) Time Spent (10 days with Titan, Druid and Faceless), Research A545, C1300<p>Cost: 706.4 Qivg (7.064E80)<p>Effect: Increase Gem Grinder bonus based on the amount of artifacts you found.<p>Formula: 1.5 * x^1.5, x is artifacts found. (multiplicative)" coords="431,825,475,869" shape="rect">
<area target="" research="A1200 - For Neutral,Dragon - Spell Name: Melting<p>Requirement: 5000 Iron Stronghold, Any Neutral Dragon<p>Cost: 15.56 Uvg (1.556E67)<p>Effect: Increase the production of all other buildings per Iron Strongholds owned by 0.35%<p>Formula: 0.35 * x, x is iron strongholds owned" coords="546,769,591,814" shape="rect">
<area target="" research="A1325 - For Any - Spell Name: Calefaction<p>Requirement: 5500 Excavations<p>Cost: 601.6 Tvg (6.016E74)<p>Effect: Increase mana regeneration based on the amount of excavations made.<p>Formula:  floor(0.25 * x) / 10, x is current excavations<p>Tip: E290 and end of R54." coords="491,825,535,870" shape="rect">
<area target="" research="A1500 - For Druid,Dragon - Spell Name: Sublimation<p>Requirement: (21600 Seconds) (6 Hours) Grand Balance Cast Time in a single game, Research D590 & A1325, Druid,Dragon<p>Cost: 25.2 Spvg (2.52e85)<p>Effect: Increase Max Mana based on the amount of Unique Buildings you own.<p>Formula: 4.5 * x^0.85, x is unique buildings owned" coords="547,826,591,869" shape="rect">
<area target="" research="W1275 - For Any - Spell Name: Authority<p>Requirement: (43200 Seconds) (12 Hours) Call to Arms Cast Time in a single game.<p>Cost: 555.1 Dvg (5.551E71)<p>Effect: Increase the production of Non-Unique buildings based on the percentage of trophies you unlocked.<p>Formula: 0.2 * x^2, x is percent of trophies unlocked" coords="659,769,705,814" shape="rect">
<area target="" research="W1375 - For Any - Spell Name: Scavenging<p>Requirement: 86400 Evil Time Spent (1 day)<p>Cost: 651.9 Qavg (6.519E77)<p>Effect: Increase the chance to find Faction Coins based on the amount of assistants you own.<p>Formula: 4 * x^1.4, x is assistants" coords="605,826,649,869" shape="rect">
<area target="" research="W1400 - For Neutral,Dragon - Spell Name: Cataclysm<p>Requirement:  Research W400, A1200, Affiliated Dragon<p>Cost: 21.46 Qivg (2.146E79)<p>Effect: Increase maximum mana based on the amount of clicks made in this game.<p>Formula: floor 65*ln(1+x^4.25), x is clicks (this game)" coords="660,827,706,868" shape="rect">
<area target="" research="Unlocked Upgrade (X): You cannot use this upgrade with the faction you are playing. (There is an option to hide these icons.)" coords="32,878,75,922" shape="rect">
<area target="" research="Locked Upgrade (question mark): You cannot unlock this upgrade with the Faction you are playing." coords="259,878,307,925" shape="rect">
<area target="" research="Locked Upgrade (exclamation mark): You can unlock this upgrade with the Faction you are playing. The Icon tool-tip will show your unlock progress %." coords="144,878,192,927" shape="rect">
</map>

<?php include "../scripts/footer.html"; ?>