<link rel="shortcut icon" href="http://musicfamily.org/realm/Factions/picks/favicon.ico" >
<body>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en">
<?php include "../scripts/header.html"; ?>
<link rel="stylesheet" href="http://musicfamily.org/realm/scripts/rtree.css" /></link>

<p>Everything has a tooltip <b>hover</b> over them to see what they are.
<p><b>Game Window</b>
<p><img src="http://musicfamily.org/realm/Factions/picks/newtestwindow1.png" usemap="#newtestwindow1-map">
<p><b>Options</b>
<p><img src="http://musicfamily.org/realm/Factions/picks/OptionsWindow.png" usemap="#OptionsWindow-map">
<map name="newtestwindow1-map">
    <area target="" research="Excavation / Artifacts<p> Excavation is unlocked once you have over 1B gems, produced over 10 Oc (1E28) coins and bought the Archeology Upgrade.<p>Excavating enables to find Rubies, Faction Coins and at certain thresholds or under certain conditions Artifacts. <p>Specific artifacts are required to unlock the Neutral &amp;amp; Prestige Factions.<p>Note: The numbers in the top right corner show the number of artifacts you could find.<p>Excavation Reset costs 1 Ruby up until 2999 excavations, switching to 2 Rubies at 3000 and above. It will reset the excavation counter to zero, all previously gained Excavation rewards and Rubies will persist and you can not find them again." coords="5,67,62,120" shape="rect">
    <area target="" research="Upgrades<p>This is where you will buy all upgrades including Royal Exchanges and see all purchased Upgrades<p>Note: The numbers in the top right corner equal the amount of upgrades you could purchase.<p>Note: (!) an exclamation mark in the top right corner means that you can Reincarnate." coords="5,9,58,62" shape="rect">
    <area target="_blank" research="Research<p>Enter the Research Facilities to improve your grinding potential. There you will be able to advance your research progress, unlock and buy special upgrades which will boost all your abilities hugely.<p>Starting at R16 you will be able to gain access to the Research Facilities<p>Vanilla Research: Unlock at R16<p>Neutral Research: Unlock at R23<p>Prestige Research: Unlock at R29<p>Neutral Prestige Research: Unlock at R47<p>Mercenary Research: Unlock at R75<p>Note: The numbers in the top right corner will appear when you unlocked a new Research.<p>Click image for more datails." href="http://musicfamily.org/realm/Research/" coords="5,125,60,178" shape="rect">
    <area target="" research="Trophies<p>The Trophy tab will appear when you get your first Trophy, this is where you can see all your trophies.<p>Note: The numbers in the top right corner (if any) tells you how many new trophies you have." coords="5,183,60,233" shape="rect">
    <area target="" research="Challenges<p>Prove your loyalty and dedication to the factions by completing their unique Challenges. You will be rewarded with new perks and upgrades to help in your Realm Grinder progress!<p>Vanilla Faction Challenges: unlock at R2<p>Neutral Faction Challenges: Unlock at R4<p>Prestige Faction Challenges: Unlock at R6<p>Neutral Prestige Challenges: Unlock at R48<p>Note: The numbers in the top right corner will appear when you complete a new Challenge." coords="5,240,61,293" shape="rect">
    <area target="" research="Events: Realm Grinder Events take place at annual festivals such as Thanksgiving, Christmas, Easter etc. <p>Playing during an Event gives the players special one-time Trophies and temporary and/or permanent perks.<p>Note: (!) an exclamation mark in the top right corner appear during Events only." coords="5,298,60,350" shape="rect">
    <area target="" research="Proof of Good Deed<p>You will be required to pick 1 of 3 Deeds before you can pick a Faction<p>Good Factions: Fairy, Elf, and Angel<p>Good Deed Cost: 25,000 coins" coords="74,94,114,132" shape="rect">
    <area target="" research="Proof of Evil Deed<p>You will be required to pick 1 of 3 Deeds before you can pick a Faction<p>Evil Factions: Goblin, Undead, and Demon<p>Evil Deed Cost: 25,000 coins" coords="118,92,158,132" shape="rect">
    <area target="" research="Proof of Neutrality<p>Works the same as Deeds, but allows access to the Neutral Factions<p>Neutral Factoins: Titan, Druid, and Faceless<p>Proof of Neutrality Cost: 10 Qa (1E16)" coords="167,94,202,131" shape="rect">
    <area target="" research="Mercenary First Contract<p>At R3 you will be able to purchase Mercenary after meeting their requirements, (see Mercenary page )<p> Cost: 50 Spd (5e55) coins<p>Once you get Mercenary you will have access to all Faction's Upgrades and combine them to make builds. " coords="210,94,249,132" shape="rect">
    <area target="" research="Bloodline<p>At R7 Bloodline unlocks and allows you to pick 1 from all available Factions" coords="254,93,294,132" shape="rect">
    <area target="" research="Royal Exchange<p>After you choose an Alignment and Faction this icon will appear<p>Cost: Free<p>Increase the production of all buildings progressively. Can be bought multiple times, but the cost increases each time.<p>" href="" coords="298,92,341,133" shape="rect">
    <area target="" research="Abdication<p>Abdicating is the 1st kind of soft reset in Realm Grinder. It allows you to cash in all the gems you have earned in order to boost your production.<p>Abdicating will reset all buildings, upgrades and coins, but you will keep your trophies and be awarded with gems that will boost your production. Otherwise, you may also spend Rubies to gain Gems without resetting!" coords="101,9,227,36" shape="rect">
    <area target="" research="Reincarnation<p><p>At the beginning of the game you will see ???, once you collect enough gems it will switch to Reincarnation.<p>Reincarnation was introduced in the Underworld Expansion. In terms of game-play, it's a second kind of soft reset where players can trade in all of their gems and have most of their stats reset for other bonuses.<p>Reincarnation can only be performed for the first time when the user reaches 1 Oc (1E27) gems. Each subsequent reincarnation costs 1,000 times more gems.<p>This will show you what Reincarnation you are currently in and will show you how many gems needed to Reincarnate to the next level." coords="240,9,362,36" shape="rect">
    <area target="" research="Default Spells<p>Tax Collection and Call to Arms will show for every Alignment, Faction, and every Abdication and Reincarnation.<p>Spells are an active component of the game mechanics that boost production. They require mana to be cast and only work while playing online.<p>Their duration, resource gain, mana-cost, and mana regeneration speed can be altered by getting specific Faction, Heritage, Challenge, or Research upgrades. Different aspects of the spells can also be used in other upgrades (eg: while a spell is active, the number of spell casts, based on mana produced, among other things." coords="447,92,559,160" shape="rect">
    <area target="" research="Alignment Spells<p>Good Alignment: Holy Light<p>Evil Alignment: Blood Freenzy<p>Neutral Alignment: Gem Grinder<p>Spells are an active component of the game mechanics that boost production. They require mana to be cast and only work while playing online.<p>Their duration, resource gain, mana-cost, and mana regeneration speed can be altered by getting specific Faction, Heritage, Challenge, or Research upgrades. Different aspects of the spells can also be used in other upgrades (eg: while a spell is active, the number of spell casts, based on mana produced, among other things." coords="556,198,447,165" shape="rect">
    <area target="" research="Default Spells<p>Starting at R14 Spiritual Surge will be available for every Alignment, Faction, and every Abdication and Reincarnation.<p>Spells are an active component of the game mechanics that boost production. They require mana to be cast and only work while playing online.<p>Their duration, resource gain, mana-cost, and mana regeneration speed can be altered by getting specific Faction, Heritage, Challenge, or Research upgrades. Different aspects of the spells can also be used in other upgrades (eg: while a spell is active, the number of spell casts, based on mana produced, among other things." coords="448,239,560,269" shape="rect">
    <area target="" research="Faction Spells<p>After picking a Faction these Spells appear<p>Good Factions: Fairy = Fairy Chanting, Elf = Moon Blessing, Angel = God's Hand<p>Evil Factions: Goblin = Goblin's Greed, Undead = Night Time, Demon = Hellfire Blast<p>Neutral Factions: Titan = Lightning Strike = Druid = Grand Balance, Faceless = Brainwave<p>Spells are an active component of the game mechanics that boost production. They require mana to be cast and only work while playing online.<p>Their duration, resource gain, mana-cost, and mana regeneration speed can be altered by getting specific Faction, Heritage, Challenge, or Research upgrades. Different aspects of the spells can also be used in other upgrades (eg: while a spell is active, the number of spell casts, based on mana produced, among other things." coords="447,202,574,236" shape="rect">
    <area target="" research="Farm (Alignment: Any)<p>Farms are the 1s of 3 buildings you will be able to buy at the start of the game.<p>First Farm cost 10 and increases 1.15 times the cost of the previous building of that type<p>Base production 2<p> Tier: 1" coords="581,7,732,47" shape="rect">
    <area target="" research="Inn (Alignment: Any)<p>Inns are the 2nd of 3 buildings you will be able to buy at the start of the game.<p>First Inn cost 125 and increases 1.15 times the cost of the previous building of that type.<p>Base production 6<p> Tier: 2" coords="583,50,732,87" shape="rect">
    <area target="" research="Blacksmith (Alignment: Any)<p>Blacksmith are the 3rd of 3 buildings you will be able to buy at the start of the game.<p>First Blacksmith cost 600 and increases 1.15 times the cost of the previous building of that type.<p>Base production 20<p>Tier: 3" coords="582,89,730,127" shape="rect">
    <area target="" research="Warrior Barracks (Good Alignment)<p>Deep Mines (Neutral Alignment)<p>Slave Pens (Evil Alignment) <p>The cost for the first building is 1,800 and increases 1.15 times the cost of the previous building of that type.<p>Base production 65<p>One of these buildings will show up once you affiliate with a Faction and will stay until you Abdicate or Reincarnate <p> Tier: 4" coords="582,131,730,165" shape="rect">
    <area target="" research="Knights Jousts (Good Alignment)<p>Stone Pillars (Neutral Alignment)<p>Orcish Arenas (Evil Alignment) <p>The cost for the first building is 5,600 and increases 1.15 times the cost of the previous building of that type.<p>Base production 200<p>One of these buildings will show up once you affiliate with a Faction and will stay until you Abdicate or Reincarnate <p> Tier: 5" coords="582,169,729,207" shape="rect">
    <area target="" research="Wizard Towers (Good Alignment)<p>Alchemist Labs (Neutral Alignment)<p>Witch Conclaves (Evil Alignment) <p>The cost for the first building is 38,000 and increases 1.15 times the cost of the previous building of that type.<p>Base production 650<p>One of these buildings will show up once you affiliate with a Faction and will stay until you Abdicate or Reincarnate <p> Tier: 6" coords="581,209,731,247" shape="rect">
    <area target="" research="Cathedrals (Good Alignment)<p>Monasteries (Neutral Alignment)<p>Dark Temples (Evil Alignment) <p>The cost for the first building is 441,999 and increases 1.15 times the cost of the previous building of that type.<p>Base production 2,000<p>One of these buildings will show up once you affiliate with a Faction and will stay until you Abdicate or Reincarnate <p> Tier: 7" coords="582,249,731,287" shape="rect">
    <area target="" research="Citadels (Good Alignment)<p>Labyrinths (Neutral Alignment)<p>Necropolises (Evil Alignment) <p>The cost for the first building is 7.3m (7.3e6)and increases 1.15 times the cost of the previous building of that type.<p>Base production 8,500<p>One of these buildings will show up once you affiliate with a Faction and will stay until you Abdicate or Reincarnate <p> Tier: 8" coords="580,287,730,327" shape="rect">
    <area target="" research="Royal Castles (Good Alignment)<p>Iron Strongholds (Neutral Alignment)<p>Evil Fortresses (Evil Alignment) <p>The cost for the first building is 145m (1.45e8) and increases 1.15 times the cost of the previous building of that type.<p>Base production 100,000<p>One of these buildings will show up once you affiliate with a Faction and will stay until you Abdicate or Reincarnate <p> Tier: 9" coords="580,328,730,366" shape="rect">
    <area target="" research="Heaven's Gates (Good Alignment)<p>Ancient Pyramids (Neutral Alignment)<p>Hell Portals (Evil Alignment) <p>The cost for the first building is 3.2b (3.2e9) and increases 1.15 times the cost of the previous building of that type.<p>Base production 1,200,000 (1.2e6)<p>One of these buildings will show up once you affiliate with a Faction and will stay until you Abdicate or Reincarnate <p> Tier: 10" coords="580,367,731,405" shape="rect">
    <area target="" research="Halls of Legends (Any Alignment)<p>The cost for the first building is 200b (2e11) and increases 1.15 times the cost of the previous building of that type.<p>Base production 250,000 per Trophy <p> This building will show up once you affiliate with a Faction and will stay until you Abdicate or Reincarnate <p> Tier: 11" coords="580,409,731,445" shape="rect">
    <area target="" research="Mana Bowl<p>Mana is a magic resource necessary to cast spells. At the beginning of a game, your base mana capacity is 1000, and your base mana regeneration rate is 0.50 per second.<p>There are many ways to increase mana regen or capacity: Faction upgrades, Research upgrades. challenge rewards, Heritages" coords="511,47,35" shape="circle">
    <area target="" research="Shop Tab<p> This is where you can buy Premium Upgrades such as Gifts, Rubies, Gem Conversion, and Timewarps with Kreds or Rubies." coords="449,347,507,406" shape="rect">
    <area target="" research="The Scry Tab<p>The Scrying function enables you to gain an extra boost of your choice in exchange for viewing a video advertisement which will help Divine Games gain some revenue.<p>Three choices<p>+100% production for 4 hours<p>+2 m/s and +10 mana regen for 30 minutes<p> Faction Coins are multiplied by assistants. <p>Formula : (10 + x) ^ 1.1 -> y * ((10 + x) ^ 1.1), where x is FC chance and y is assistants you own.<p>Some countries have more ads then others and players from those countries will be able to scry more often.<p> Some players will be able to scry as much as they want and have both timers running all the time, others may only be able to scry only once or twice per day and will need to be strategic about when to best use it.<p> A few people will not be able to scry at all." coords="513,348,570,406" shape="rect">
    <area target="" research="Buy Button<p>This button is used to select the amount of buildings to buy with each click.<p>You can toggle it to Buy1,Buy10,Buy1000 or BuyMax by clicking on it.<p>You can disable this button in the Options Menu." coords="451,414,571,443" shape="rect">
    <area target="" research="Assistants: Are little helpers that helps gather coins and Faction Coins. They are represented by the little icons around main building. Hover over it to get details.<p>Assistant clicks are not like manual clicks, their income is influenced by clicking reward upgrades, but they will not help to build-up clicking bonus<p>You can buy more Assistants by getting 100 of the same building (max 2 per building)or through Unique Upgrades in later game" coords="409,205,425,218" shape="rect">
    <area target="" research="Coins<p>This shows your current amount of coins and total coins gained" coords="8,452,100,483" shape="rect">
    <area target="" research="Production<p>This shows your total coin production per second by Assistants and by clicking also shows your Offline production" coords="130,452,230,485" shape="rect">
    <area target="" research="Gems<p>Shows you total Gem count<p>Shows how many gems you gain when you Abdicate<p>Shows increase of production after Abdication" coords="267,452,322,482" shape="rect">
    <area target="" research="Rubies<p>You can gain Rubies by excavating, Events or buying them.<p>Rubies are a rare resource which allows you to increase all aspects of your production. Accumulating them will unlock new upgrades and trophies, providing both a permanent passive bonus and the ability to spend them to purchase new perks.<p>Rubies persist through Abdications and Reincarnations." coords="378,452,422,482" shape="rect">
    <area target="" research="Assistants:<p>Shows your total Assistant count and total Assistant production per second<p>Little helpers that auto-click the treasure once every second for 5% of your clicking reward and helps gather coins and Faction Coins. Hover over it to get details.<p>Assistant clicks are not like manual clicks, their income is influenced by clicking reward upgrades, but they will not help to build-up clicking bonus<p>You can buy more Assistants by getting 100 of the same building (max 2 assistants per building set)or through Upgrades" coords="480,452,530,482" shape="rect">
    <area target="" research="Tips and Hints<p> Clicking this will give you tips and hints<p>Also clicking this 100 times in a row will award you with a trophy" coords="647,452,674,483" shape="rect">
    <area target="" research="Stats<p>This will show you most of your game stats." coords="674,452,705,483" shape="rect">
    <area target="" research="Options<p>Here you can set many options<p> This is where you can save you game to cloud or restore from cloud<p> Registering with Cloud will award you with a trophy<p>Here you can import and export your game" coords="705,451,734,483" shape="rect">
    <area target="" research="Clicking this will hide everything(user interface) and only show the background" coords="614,452,645,483" shape="rect">
    <area target="" research="Clicking these Arrows in game will show/hide the Upgrades" coords="362,66,382,85" shape="rect">
    <area target="" research="Clicking these Arrows in game will show/hide the Upgrades" coords="362,140,382,158" shape="rect">
    <area target="" research="Clicking these Arrows in game will show/hide the Upgrades" coords="362,213,382,232" shape="rect">
    <area target="" research="Some Upgrades will be shaded, this means you can not afford them or you have not met the requirements" coords="165,167,205,207" shape="rect">
    <area target="" research="All Highlighted Upgrades can be bought, Shaded Upgrades can not be bought" coords="74,240,385,324" shape="rect">
    <area target="" research="You will have many types of Upgrades, be careful of the ones you buy as they may remove other Upgrades." coords="74,166,159,207" shape="rect">
    <area target="" research="Priority Autocasting<p>Allows you to prioritize the order of spell casting.(Set with Ctrl+Click)<p>Spells with lower priority will be cast only if the higher priority spells are already active. <p>Only while offline, increase your spells cast amount by 1 per minute.<p>Cost: 400 Ud (4E38)" coords="560,145,572,160" shape="rect">
    <area target="" research="Efficient Autocasting<p>Allows you to set spells to work outside of contingency and planned settings. These spells (set with CTRL+SHIFT+Click), or in the spell tooltip,disregard your contingency rules and are casted as soon as you have enough mana for them.<p>Cost: 700 Vg (7E65)<p>Only while offline, increase your mana production by an additional 10% of your mana regeneration per second, and your spells cast amount by an additional 2 per minute." coords="561,254,575,271" shape="rect">
    <area target="" research="Faction Coins<p>When you start the game you will have 6 different types, 1 for each Faction. In later game you will unlock 2 more types for Prestige.<p>After picking a Faction save Faction Coins for that Faction and use the others for Royal Exchanges." href="" coords="67,407,400,447" shape="rect">
    <area target="" research="Planned Autocasting<p>Allows you to set Primary and Secondary spells. Primary spells (Set with Shift+Click) will fire when the mana reaches amount set by the Contingency slidebar. Secondary spells (Set with SHIFT+Click) will fire as soon as there is enough mana, and if ALL the primary spells are active. <p>Only while offline, increase mana produced by an additional 10% of your mana regeneration per second and your spells cast amount by an additional 2 per minute." coords="558,181,574,198" shape="rect">
    <area target="" research="Contingency Autocasting<p>Allows you to set a minimum amount of mana before starting to Autocast. A slide bar will appear on the mana bowl when you CTRL+Click while pointing to the mana bowl<p>By adjusting its height you will set a minimum amount of mana for spells to start casting. Once your mana reaches the threshold, spells will follow the priority rules. The contingency loop will break when there is not enough mana to continue, at which point the cycle will reset.<p>Only while offline, increase your spells cast amount by an additional 2 per minute." coords="528,9,8" shape="circle">
    <area target="" research="Buy All<p>When you start the game this button will not show, It Unlocks at 100 Gems.<p>In Options you can set this to include Royal Exchanges." coords="181,40,274,56" shape="rect">
</map>
<map name="OptionsWindow-map">
    <area target="" research="Use Thousands Separator<p>Putting an X in this box will shows numbers with (,) in them.<p>Examples<p>With X 2,000<p>Without X 2000" coords="48,71,254,92" shape="rect">
    <area target="" research="Don't Group Upgrades by Category<p>Putting an X in this box will group all upgrades together.<p>Without X it will separate upgrades by category. " coords="47,96,305,114" shape="rect">
    <area target="" research="Don't Group Trophies by Category<p>Putting an X in this box will show all trophies in 1 general category.<p>Examples<p>With X 1 category (Trophies Unlocked).<p>Without X 5 categories, Allegiances Trophies, Misc Trophies, Magic Trophies, Building Trophies, and Secret Trophies" coords="48,118,307,138" shape="rect">
    <area target="" research="Don't Consolidate Upgrades<p>Putting an X in this box will show all upgrades you have purchased.<p>Without X you will only see the last upgrade you purchased in that series. " coords="47,142,268,161" shape="rect">
    <area target="" research="Don't Consolidate Trophies<p>Putting an X in this box will show all trophies earned.<p>Without X you will see the last trophy you earned in that series." coords="48,167,261,185" shape="rect">
    <area target="" research="Disable Warning for Ruby Upgrades<p>Putting an X in this box you will not be warned that you are about to spend rubies.<p>Without X you will be warned that you are about to spend rubies.(Recommended)" coords="47,190,318,209" shape="rect">
    <area target="" research="Numbers Format<p>All 3 sets of numbers below are the same amount.<p>Short Notation: 100 No coins<p>Scientific Notation: 1e32 coins (Recommended)<p>Engineering Notation: 100e30 coins" coords="45,39,599,60" shape="rect">
    <area target="" research="Disable Warning for Exchanges<p>Putting an X in this box will stop all warnings that you are about to spend Faction Coins for Royal Exchanges.<p>Without X you will be warned that you are about to spend Faction Coins on Royal Exchanges<p>Note: The warning is only for the Faction Coins of your Faction.<p>Note This has no effect on the Buy All Button." coords="49,214,289,234" shape="rect">
    <area target="" research="Disable Click Particles<p>Putting an X in this box will hide the faction coins you see when the background is clicked." coords="49,239,230,257" shape="rect">
    <area target="" research="Disable Click Text<p>Putting an X in this box will hide all faction coin and income coin text." coords="49,263,201,281" shape="rect">
    <area target="" research="Disable Menu Sliding Animation<p>Putting an X in this box will make the Menu pop out.<p>Without X the Menu will slide out." coords="45,285,296,305" shape="rect">
    <area target="" research="Block Background Clicks<p>Putting an X in this box will block you from doing manual clicks on the background.<p>Without X you can click the background.<p>Note: this does not effect Automatic Clicks." coords="49,310,245,328" shape="rect">
    <area target="" research="Disable Non-Manual Clicks<p>Putting an X in this box will stop all Automatic Clicks.<p>Note: This does not effect Manual Clicks." coords="49,334,263,352" shape="rect">
    <area target="" research="Enable Spell Tooltip Persist<p>Putting an X in this box will allow you to select Spell Tiers and set Autocasting inside the Tooltip.<p>Without X you will need to set Spell Tiers and set Autocasting with the keyboard and clicking the spell." coords="48,358,265,376" shape="rect">
    <area target="" research="Disable Gifts<p>Putting X in any of these boxes will Disable that gift<p>Without X all Gifts are active<p>Note: The Gifts have no effect on any Challenge or Trophy run in a negative way, so no need to disable any of them." href="" coords="49,381,378,401" shape="rect">
    <area target="" research="Disable Cloud Check at Stratup<p>Putting X in this boc will stop Cloud from checking if you have a higher save than the one that is in your current game at Startup.<p>Without X Cloud will check to see if it has a save higher than the current game at startup and offer to load it for you." coords="382,70,625,90" shape="rect">
    <area target="" research="Buy All Exchanges<p>Putting X in this box will allow you to Buy All Royal Exchanges when you click the Buy All button.<p.Without X you will need to buy Royal Exchanges manually." coords="382,95,536,115" shape="rect">
    <area target="" research="Sort Purchased Upgrades by Price<p>Putting X in this box will put all Purchased Upgrades in order by price with the lowest price first.<p>Without X upgrades appear in order that they are purchased." coords="382,119,642,139" shape="rect">
    <area target="" research="Language<p>Here is where you can select your preferred Language.<p>English, Español, Deutsch, Français, Português(Brasil), Pусский, and Italiano<p>Note Changing Language does not lock you to that Language and is just as easy to select another Language." coords="514,317,639,361" shape="rect">
    <area target="" research="Sort Unpurchased Upgrades by Price<p>Putting X in this box will put all Unpurchased Upgrades in order by price with the lowest price first.<p>Without X Unpurchased Upgrades appear in order that they become available." coords="383,144,662,162" shape="rect">
    <area target="" research="Hide Purchased Upgrades<p>Putting X in this box will hide all Purchased Upgrades you have.<p>Without X you will see all Purchased Upgrades." coords="382,166,588,185" shape="rect">
    <area target="" research="Hide Unavailable Researches<p>Putting X in this box will hide all Unavailable Researches.<p>Without X you will see all Researches." coords="382,190,608,210" shape="rect">
    <area target="" research="Disable Multibuy for Upgrade Series<p>Putting X in this box will allow you to buy one Upgrade at a time for each series.<p>Without X you will be able to buy all Upgrades in that series with one click." coords="382,213,658,233" shape="rect">
    <area target="" research="Disable BuyMax Button<p>Putting X in this box will hide the BuyMax button and you will only be able to buy 1 building at a time<p>Without X you will be able to buy 1, 10, 100, 1000, or Maximum amount of buildings depending on what you have it set to buy." coords="383,237,567,257" shape="rect">
    <area target="" research="Skip All Tutorials<p>Putting X in this box will stop most tips, hints, and tutorials from popping up<p>Without X the Tutorial will popup up when you reach some milestones." coords="382,261,534,281" shape="rect">
    <area target="" research="Cloud Options<p>This is where you can see your Kongregate ID number and you saved game information" coords="47,438,580,466" shape="rect">
    <area target="" research="Overwrite<p>If your current game does not match your Cloud Save you can Overwrite the Cloud save to match your current game.<p>When the Overwrite button is clicked a box a box will pop up titled 'Cloud Overwrite' stating 'This will permanently replace your existing cloud save with the current one. Type &quot;OVERWRITE&quot; in the field below to confirm.<p>You will then be required to click Overwrite or Don't Overwrite." coords="48,473,138,502" shape="rect">
    <area target="" research="Restore<p>If your current game does not match your Cloud Save you can use this button to Restore it with the Cloud Save.<p>When you click Restore a box will pop up titled 'Cloud Restore' stating 'Restoring from the cloud will permanently overwrite your current savegame. Type &quot;RESTORE&quot; in the field below to confirm.<p>You will then be required to click Restore or Don't Restore." coords="145,474,234,503" shape="rect">
    <area target="" research="Save Options<p>Save: Clicking this will save your game with cloud (only if it matches the cloud saved game).<p>Export: This will copy to clipboard (the right mouse click used to copy and paste) then you can paste it to a text file to manually save your game.<p>Import: This is where you can paste your saved text file to load it in the game." coords="48,541,331,570" shape="rect">
    <area target="" research="Hard Reset<p>If you want to start over click this button and you will start at the beginning of the game and you will loose most of your previous stats." coords="47,617,139,645" shape="rect">
    <area target="" research="This is the current game version, click it to see the current and previous versions." coords="625,648,676,661" shape="rect">
<?php include "../scripts/footer.html"; ?>
