<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en">
<?php include "../scripts/header.html"; ?>
<link rel="stylesheet" href="http://musicfamily.org/realm/scripts/game.css" />
<p><b>The Game Window</b> (<b>Everything</b> has a <b>tooltip</b>).
<p><img src="http://musicfamily.org/realm/Factions/picks/GameWindow6.png" usemap="#GameWindow6-map">
<font size="3" color="red">
<map name="GameWindow6-map">
    <area target="" alt="Farm (Alignment: Any)<p>Farms are the 1s of 3 buildings you will be able to buy at the start of the game.<p>First Farm cost 10 and increases 1.15 times the cost of the previous building of that type<p>Base production 2<p> Tier: 1" research="Farm (Alignment: Any)<p>Farms are the 1s of 3 buildings you will be able to buy at the start of the game.<p>First Farm cost 10 and increases 1.15 times the cost of the previous building of that type<p>Base production 2<p> Tier: 1" coords="693,10,858,55" shape="rect">
    <area target="" alt="Inn (Alignment: Any)<p>Inns are the 2nd of 3 buildings you will be able to buy at the start of the game.<p>First Inn cost 125 and increases 1.15 times the cost of the previous building of that type.<p>Base production 6<p> Tier: 2" research="Inn (Alignment: Any)<p>Inns are the 2nd of 3 buildings you will be able to buy at the start of the game.<p>First Inn cost 125 and increases 1.15 times the cost of the previous building of that type.<p>Base production 6<p> Tier: 2" coords="694,58,856,102" shape="rect">
    <area target="" alt="Blacksmith (Alignment: Any)<p>Blacksmith are the 3rd of 3 buildings you will be able to buy at the start of the game.<p>First Blacksmith cost 600 and increases 1.15 times the cost of the previous building of that type.<p>Base production<p> 20 Tier: 3" research="Blacksmith (Alignment: Any)<p>Blacksmith are the 3rd of 3 buildings you will be able to buy at the start of the game.<p>First Blacksmith cost 600 and increases 1.15 times the cost of the previous building of that type.<p>Base production 20<p>Tier: 3" coords="693,106,856,148" shape="rect">
    <area target="" alt="Warrior Barracks (Good Alignment)<p>Deep Mines (Neutral Alignment)<p>Slave Pens (Evil Alignment) <p>The cost for the first building is 1,800 and increases 1.15 times the cost of the previous building of that type.<p>Base production 65<p>One of these buildings will show up once you affiliate with a Faction and will stay until you Abdicate or Reincarnate <p> Tier: 4" research="Warrior Barracks (Good Alignment)<p>Deep Mines (Neutral Alignment)<p>Slave Pens (Evil Alignment) <p>The cost for the first building is 1,800 and increases 1.15 times the cost of the previous building of that type.<p>Base production 65<p>One of these buildings will show up once you affiliate with a Faction and will stay until you Abdicate or Reincarnate <p> Tier: 4" coords="694,153,854,194" shape="rect">
    <area target="" alt="Knights Jousts (Good Alignment)<p>Stone Pillars (Neutral Alignment)<p>Orcish Arenas (Evil Alignment) <p>The cost for the first building is 5,600 and increases 1.15 times the cost of the previous building of that type.<p>Base production 200<p>One of these buildings will show up once you affiliate with a Faction and will stay until you Abdicate or Reincarnate <p> Tier: 5" research="Knights Jousts (Good Alignment)<p>Stone Pillars (Neutral Alignment)<p>Orcish Arenas (Evil Alignment) <p>The cost for the first building is 5,600 and increases 1.15 times the cost of the previous building of that type.<p>Base production 200<p>One of these buildings will show up once you affiliate with a Faction and will stay until you Abdicate or Reincarnate <p> Tier: 5" coords="696,197,856,239" shape="rect">
    <area target="" alt="Wizard Towers (Good Alignment)<p>Alchemist Labs (Neutral Alignment)<p>Witch Conclaves (Evil Alignment) <p>The cost for the first building is 38,000 and increases 1.15 times the cost of the previous building of that type.<p>Base production 650<p>One of these buildings will show up once you affiliate with a Faction and will stay until you Abdicate or Reincarnate <p> Tier: 6" research="Wizard Towers (Good Alignment)<p>Alchemist Labs (Neutral Alignment)<p>Witch Conclaves (Evil Alignment) <p>The cost for the first building is 38,000 and increases 1.15 times the cost of the previous building of that type.<p>Base production 650<p>One of these buildings will show up once you affiliate with a Faction and will stay until you Abdicate or Reincarnate <p> Tier: 6" coords="696,244,853,288" shape="rect">
    <area target="" alt="Cathedrals (Good Alignment)<p>Monasteries (Neutral Alignment)<p>Dark Temples (Evil Alignment) <p>The cost for the first building is 441,999 and increases 1.15 times the cost of the previous building of that type.<p>Base production 2,000<p>One of these buildings will show up once you affiliate with a Faction and will stay until you Abdicate or Reincarnate <p> Tier: 7" research="Cathedrals (Good Alignment)<p>Monasteries (Neutral Alignment)<p>Dark Temples (Evil Alignment) <p>The cost for the first building is 441,999 and increases 1.15 times the cost of the previous building of that type.<p>Base production 2,000<p>One of these buildings will show up once you affiliate with a Faction and will stay until you Abdicate or Reincarnate <p> Tier: 7" coords="694,291,854,333" shape="rect">
    <area target="" alt="Citadels (Good Alignment)<p>Labyrinths (Neutral Alignment)<p>Necropolises (Evil Alignment) <p>The cost for the first building is 7.3m (7.3e6)and increases 1.15 times the cost of the previous building of that type.<p>Base production 8,500<p>One of these buildings will show up once you affiliate with a Faction and will stay until you Abdicate or Reincarnate <p> Tier: " research="Citadels (Good Alignment)<p>Labyrinths (Neutral Alignment)<p>Necropolises (Evil Alignment) <p>The cost for the first building is 7.3m (7.3e6)and increases 1.15 times the cost of the previous building of that type.<p>Base production 8,500<p>One of these buildings will show up once you affiliate with a Faction and will stay until you Abdicate or Reincarnate <p> Tier: " coords="694,338,856,378" shape="rect">
    <area target="" alt="Royal Castles (Good Alignment)<p>Iron Strongholds (Neutral Alignment)<p>Evil Fortresses (Evil Alignment) <p>The cost for the first building is 145m (1.45e8) and increases 1.15 times the cost of the previous building of that type.<p>Base production 100,000<p>One of these buildings will show up once you affiliate with a Faction and will stay until you Abdicate or Reincarnate <p> Tier: 9" research="Royal Castles (Good Alignment)<p>Iron Strongholds (Neutral Alignment)<p>Evil Fortresses (Evil Alignment) <p>The cost for the first building is 145m (1.45e8) and increases 1.15 times the cost of the previous building of that type.<p>Base production 100,000<p>One of these buildings will show up once you affiliate with a Faction and will stay until you Abdicate or Reincarnate <p> Tier: 9" coords="696,384,856,426" shape="rect">
    <area target="" alt="Heaven's Gates (Good Alignment)<p>Ancient Pyramids (Neutral Alignment)<p>Hell Portals (Evil Alignment) <p>The cost for the first building is 3.2b (3.2e9) and increases 1.15 times the cost of the previous building of that type.<p>Base production 1,200,000 (1.2e6)<p>One of these buildings will show up once you affiliate with a Faction and will stay until you Abdicate or Reincarnate <p> Tier: 10" research="Heaven's Gates (Good Alignment)<p>Ancient Pyramids (Neutral Alignment)<p>Hell Portals (Evil Alignment) <p>The cost for the first building is 3.2b (3.2e9) and increases 1.15 times the cost of the previous building of that type.<p>Base production 1,200,000 (1.2e6)<p>One of these buildings will show up once you affiliate with a Faction and will stay until you Abdicate or Reincarnate <p> Tier: 10" coords="694,429,856,473" shape="rect">
    <area target="" alt="Halls of Legends (Any Alignment)<p>The cost for the first building is 200b (2e11) and increases 1.15 times the cost of the previous building of that type.<p>Base production 250,000 per Trophy <p> This building will show up once you affiliate with a Faction and will stay until you Abdicate or Reincarnate <p> Tier: 11" research="Halls of Legends (Any Alignment)<p>The cost for the first building is 200b (2e11) and increases 1.15 times the cost of the previous building of that type.<p>Base production 250,000 per Trophy <p> This building will show up once you affiliate with a Faction and will stay until you Abdicate or Reincarnate <p> Tier: 11" coords="693,476,858,519" shape="rect">
    <area target="" alt="Spells are an active component of the game mechanics that enables to boost production. They require mana to be cast, and can also work offline, at a much slower rate, once the autocasting upgrades have been purchased.<p>Their duration, resource gain, mana-cost, and mana regeneration speed can be altered by getting specific Faction, Heritage, Challenge, or Research upgrades. Different aspects of the spells can also be used in other upgrades (eg: while a spell is active, the number of spell casts, based on mana produced, among other things." research="Spells are an active component of the game mechanics that enables to boost production. They require mana to be cast, and can also work offline, at a much slower rate, once the autocasting upgrades have been purchased.<p>Their duration, resource gain, mana-cost, and mana regeneration speed can be altered by getting specific Faction, Heritage, Challenge, or Research upgrades. Different aspects of the spells can also be used in other upgrades (eg: while a spell is active, the number of spell casts, based on mana produced, among other things." coords="549,105,689,318" shape="rect">
    <area target="" alt="Mana Bar<p>Mana is a magic resource necessary to cast spells. At the beginning of a game, your base mana capacity is 1000, and your base mana regeneration rate is 0.50 per second.<p>There are many ways to increase mana regen or capacity: Faction upgrades, Research upgrades. challenge rewards, Heritages" research="Mana Bar<p>Mana is a magic resource necessary to cast spells. At the beginning of a game, your base mana capacity is 1000, and your base mana regeneration rate is 0.50 per second.<p>There are many ways to increase mana regen or capacity: Faction upgrades, Research upgrades. challenge rewards, Heritages" coords="622,55,38" shape="circle">
    <area target="" alt="Shop Tab<p> This is where you can buy Premium Upgrades such Gifts,Rubies,Gem Conversion and Timewarps with Kreds or Rubies." research="Shop Tab<p> This is where you can buy Premium Upgrades such Gifts,Rubies,Gem Conversion and Timewarps with Kreds or Rubies." coords="574,408,627,460" shape="rect">
    <area target="" alt="The Scry Tab<p>The Scrying function enables you to gain an extra boost of your choice in exchange for viewing a video advertisement which will help Divine Games gain some revenue.<p>The choices are: +100% production for 4 hours, +2 m/s and +10 mana regen for 10 minutes, Faction Coins based on your production. <p>Formula: ??? Events can bring additional options.<p>Some countries have more ads then others and players from those countries will be able to scry more often.<p> Some players will be able to scry as much as they want and have both timers running all the time, others may only be able to scry only once or twice per day and will need to be strategic about when to best use it.<p> A few people will not be able to scry at all." research="The Scry Tab<p>The Scrying function enables you to gain an extra boost of your choice in exchange for viewing a video advertisement which will help Divine Games gain some revenue.<p>The choices are: +100% production for 4 hours, +2 m/s and +10 mana regen for 10 minutes,<p> Faction Coins based on your production. <p>Formula :1 + floor(ln(1 + offline gold/s)^1.5).<p>Some countries have more ads then others and players from those countries will be able to scry more often.<p> Some players will be able to scry as much as they want and have both timers running all the time, others may only be able to scry only once or twice per day and will need to be strategic about when to best use it.<p> A few people will not be able to scry at all." coords="633,411,682,460" shape="rect">
    <area target="" alt="This button is used to select the amount of buildings to buy with each click.<p>You can toggle it to Buy1,Buy10,Buy1000 or BuyMax by clicking on it.<p>You can disable this button in the Options Menu." research="This button is used to select the amount of buildings to buy with each click.<p>You can toggle it to Buy1,Buy10,Buy1000 or BuyMax by clicking on it.<p>You can disable this button in the Options Menu." coords="576,468,683,517" shape="rect">
    <area target="" alt="Assistants: Are little helpers that helps gather coins and Faction Coins. They are represented by the little icons around main building. Hover over it to get details.<p>Assistant clicks are not like manual clicks, their income is influenced by clicking reward upgrades, but they will not help to build-up clicking bonus<p>You can buy more Assistants by getting 100 of the same building (max 2 per building)or through Unique Upgrades in later game" research="Assistants: Are little helpers that helps gather coins and Faction Coins. They are represented by the little icons around main building. Hover over it to get details.<p>Assistant clicks are not like manual clicks, their income is influenced by clicking reward upgrades, but they will not help to build-up clicking bonus<p>You can buy more Assistants by getting 100 of the same building (max 2 per building)or through Unique Upgrades in later game" coords="409,218,12" shape="circle">
    <area target="" alt="Assistants: Are little helpers that helps gather coins and Faction Coins. They are represented by the little icons around main building. Hover over it to get details.<p>Assistant clicks are not like manual clicks, their income is influenced by clicking reward upgrades, but they will not help to build-up clicking bonus<p>You can buy more Assistants by getting 100 of the same building (max 2 per building)or through Unique Upgrades in later game." research="&quot;Assistants: Are little helpers that helps gather coins and Faction Coins. They are represented by the little icons around main building. Hover over it to get details.<p>Assistant clicks are not like manual clicks, their income is influenced by clicking reward upgrades, but they will not help to build-up clicking bonus<p>You can buy more Assistants by getting 100 of the same building (max 2 per building)or through Unique Upgrades in later game." coords="438,269,11" shape="circle">
    <area target="" alt="Assistants: Are little helpers that helps gather coins and Faction Coins. They are represented by the little icons around main building. Hover over it to get details.<p>Assistant clicks are not like manual clicks, their income is influenced by clicking reward upgrades, but they will not help to build-up clicking bonus<p>You can buy more Assistants by getting 100 of the same building (max 2 per building)or through Unique Upgrades in later game." research="&quot;Assistants: Are little helpers that helps gather coins and Faction Coins. They are represented by the little icons around main building. Hover over it to get details.<p>Assistant clicks are not like manual clicks, their income is influenced by clicking reward upgrades, but they will not help to build-up clicking bonus<p>You can buy more Assistants by getting 100 of the same building (max 2 per building)or through Unique Upgrades in later game." coords="500,270,11" shape="circle">
    <area target="" alt="This is where you will buy all upgrades and see all purchased Upgrades" research="This is where you will buy all upgrades including Royal Exchanges and see all purchased Upgrades" coords="31,19,90,77" shape="rect">
    <area target="" alt="Excavation / Artifacts<p> Excavation is unlocked once you have over 1B gems, produced over 10 Oc (1E28) coins and bought the Archeology Upgrade.<p>Excavating enables to find Rubies, Faction Coins and at certain thresholds or under certain conditions Artifacts. <p>Specific artifacts are required to unlock the Neutral &amp; Prestige Factions.<p>Excavation Reset  costs 1 Ruby up until 2999 excavations, switching to 2 Rubies at 3000 and above. It will reset the excavation counter to zero, all previously gained Excavation rewards and Rubies will persist and you can not find them again." research="Excavation / Artifacts<p> Excavation is unlocked once you have over 1B gems, produced over 10 Oc (1E28) coins and bought the Archeology Upgrade.<p>Excavating enables to find Rubies, Faction Coins and at certain thresholds or under certain conditions Artifacts. <p>Specific artifacts are required to unlock the Neutral &amp; Prestige Factions.<p>Excavation Reset  costs 1 Ruby up until 2999 excavations, switching to 2 Rubies at 3000 and above. It will reset the excavation counter to zero, all previously gained Excavation rewards and Rubies will persist and you can not find them again." coords="30,89,90,149" shape="rect">
    <area target="" alt="Research: R16+<p>Enter the Research Facilities to improve your grinding potential.<p>A new progress system accessible from R16, overtaking the Mercenaries and boosting the production of the 6 Vanilla Factions.<p>Later, at R23, it also includes the Neutral Factions." research="Research: R16+<p>Enter the Research Facilities to improve your grinding potential.<p>A new progress system accessible from R16, overtaking the Mercenaries and boosting the production of the 6 Vanilla Factions.<p>Later, at R23, it also includes the Neutral Factions." coords="33,163,90,219" shape="rect">
    <area target="" alt="This is where you can see all your trophies." research="This is where you can see all your trophies." coords="31,235,88,288" shape="rect">
    <area target="" alt="Challenges: Prove your loyalty and dedication to the factions by completing their unique Challenges. You will be rewarded with new perks and upgrades to help in your Realm Grinder progress!<p>Vanilla Faction challenges: unlock at R2<p>Neutral Faction challenges: Unlock at R4<p>Prestige Faction challenges: Unlock at R6" research="Challenges: Prove your loyalty and dedication to the factions by completing their unique Challenges. You will be rewarded with new perks and upgrades to help in your Realm Grinder progress!<p>Vanilla Faction challenges: unlock at R2<p>Neutral Faction challenges: Unlock at R4<p>Prestige Faction challenges: Unlock at R6" coords="33,306,90,361" shape="rect">
    <area target="" alt="Events: Realm Grinder Events take place at annual festivals such as Thanksgiving, Christmas, Easter etc. <p>Playing during an Event gives the players special one-time Trophies and temporary and/or permanent perks." research="Events: Realm Grinder Events take place at annual festivals such as Thanksgiving, Christmas, Easter etc. <p>Playing during an Event gives the players special one-time Trophies and temporary and/or permanent perks." coords="31,378,91,435" shape="rect">
    <area target="" alt="Coins<p>This shows your current amount of coins and total coins gained" research="Coins<p>This shows your current amount of coins and total coins gained" coords="11,526,118,562" shape="rect">
    <area target="" alt="Production<p>This shows your total coin production per second by Assistants and by clicking also shows your Offline production" research="Production<p>This shows your total coin production per second by Assistants and by clicking also shows your Offline production" coords="148,528,260,562" shape="rect">
    <area target="" alt="Gems<p>Shows you total Gem count<p>Shows how many gems you gain when you Abdicate<p>Shows increase of production after Abdication" research="Gems<p>Shows you total Gem count<p>Shows how many gems you gain when you Abdicate<p>Shows increase of production after Abdication" coords="309,528,406,562" shape="rect">
    <area target="" alt="Rubies<p>You can gain Rubies by excavating, Events or buying them.<p>Rubies are a rare resource which allows you to increase all aspects of your production. Accumulating them will unlock new upgrades and trophies, providing both a permanent passive bonus and the ability to spend them to purchase new perks.<p>Rubies persist through Abdications and Reincarnations." research="Rubies<p>You can gain Rubies by excavating, Events or buying them.<p>Rubies are a rare resource which allows you to increase all aspects of your production. Accumulating them will unlock new upgrades and trophies, providing both a permanent passive bonus and the ability to spend them to purchase new perks.<p>Rubies persist through Abdications and Reincarnations." coords="442,530,513,562" shape="rect">
    <area target="" alt="Assistants: <p> Shows your total Assistant count and total Assistant production per second<p>Little helpers that auto-click the treasure once every second for 5% of your clicking reward and helps gather coins and Faction Coins. Hover over it to get details.<p>Assistant clicks are not like manual clicks, their income is influenced by clicking reward upgrades, but they will not help to build-up clicking bonus<p>You can buy more Assistants by getting 100 of the same building (max 2 assistants per building set)or through Upgrades" research="Assistants: <p> Shows your total Assistant count and total Assistant production per second<p>Little helpers that auto-click the treasure once every second for 5% of your clicking reward and helps gather coins and Faction Coins. Hover over it to get details.<p>Assistant clicks are not like manual clicks, their income is influenced by clicking reward upgrades, but they will not help to build-up clicking bonus<p>You can buy more Assistants by getting 100 of the same building (max 2 assistants per building set)or through Upgrades" coords="556,528,631,563" shape="rect">
    <area target="" alt="Clicking this will hide everything(user interface) and only show the background" research="Clicking this will hide everything(user interface) and only show the background" coords="719,529,749,561" shape="rect">
    <area target="" alt="Tips and Hints<p> Clicking this will give you tips and hints<p>Also clicking this 100 times in a row will award you with a trophy" research="Tips and Hints<p> Clicking this will give you tips and hints<p>Also clicking this 100 times in a row will award you with a trophy" coords="749,528,782,563" shape="rect">
    <area target="" alt="Stats<p>This will show you some of your game stats<p>To see all your stats click this image" research="Stats<p>This will show you some of your game stats<p>To see all your stats click this image" coords="782,528,820,563" shape="rect">
    <area target="" alt="Options<p>Here you can set many options<p> This is where you can save you game to cloud or restore from cloud<p> Registering with Cloud will award you with a trophy<p>Here you can inport and export your game" research="Options<p>Here you can set many options<p> This is where you can save you game to cloud or restore from cloud<p> Registering with Cloud will award you with a trophy<p>Here you can import and export your game" coords="818,527,853,563" shape="rect">
    <area target="" alt="Priority Autocasting: Allows you to prioritize the order of spell casting. <p>Spells with lower priority will be cast only if the higher priority spells are already active. <p>Only while offline, increase your spells cast amount by 1 per minute.<p>Cost: 400 Ud (4E38)" research="Priority Autocasting: Allows you to prioritize the order of spell casting. <p>Spells with lower priority will be cast only if the higher priority spells are already active. <p>Only while offline, increase your spells cast amount by 1 per minute.<p>Cost: 400 Ud (4E38)" coords="678,305,8" shape="circle">
    <area target="" alt="Planned Autocasting: Allows you to set Primary and Secondary spells. Primary spells (Set with CTRL+Click) will fire when the mana reaches amount set by the Contingency slidebar. <p>Secondary spells (Set with SHIFT+Click) will fire as soon as there is enough mana, and if ALL the primary spells are active.<p>Only while offline, increase mana produced by an additional 10% of your mana regeneration per second and your spells cast amount by an additional 2 per minute.600 Spd (6E56)" research="Planned Autocasting: Allows you to set Primary and Secondary spells. Primary spells (Set with CTRL+Click) will fire when the mana reaches amount set by the Contingency slidebar. <p>Secondary spells (Set with SHIFT+Click) will fire as soon as there is enough mana, and if ALL the primary spells are active.<p>Only while offline, increase mana produced by an additional 10% of your mana regeneration per second and your spells cast amount by an additional 2 per minute.600 Spd (6E56)" coords="678,264,8" shape="circle">
    <area target="" alt="Efficient Autocasting: <p>Allows you to set spells to work outside of contingency and planned settings. These spells (set with CTRL+SHIFT+Click), or in the spell tooltip,disregard your contingency rules and are casted as soon as you have enough mana for them.<p>Cost: 700 Vg (7E65)<p>Only while offline, increase your mana production by an additional 10% of your mana regeneration per second, and your spells cast amount by an additional 2 per minute." research="Efficient Autocasting: <p>Allows you to set spells to work outside of contingency and planned settings. These spells (set with CTRL+SHIFT+Click), or in the spell tooltip,disregard your contingency rules and are casted as soon as you have enough mana for them.<p>Cost: 700 Vg (7E65)<p>Only while offline, increase your mana production by an additional 10% of your mana regeneration per second, and your spells cast amount by an additional 2 per minute." coords="678,220,7" shape="circle">
    <area target="" alt="Tiered Autocasting R42+<p>Allows you to set the maximum tier you wish to autocast each spell to. Set with CTRL+X+Click, or in the spell tooltip, use the diamond icon to change its mode until you get to the desired maximum tier number. Spells will still follow their previous priority rules.cost 800 Vg (8E65)<p>Only while offline, increase mana produced by an additional 10% of your mana regeneration per second and your spells cast amount by an additional 3 per minute." research="Tiered Autocasting R42+<p>Allows you to set the maximum tier you wish to autocast each spell to. Set with CTRL+X+Click, or in the spell tooltip, use the diamond icon to change its mode until you get to the desired maximum tier number. Spells will still follow their previous priority rules.cost 800 Vg (8E65)<p>Only while offline, increase mana produced by an additional 10% of your mana regeneration per second and your spells cast amount by an additional 3 per minute." coords="667,161,8" shape="circle">
</map>
<img src="http://musicfamily.org/realm/Factions/picks/RoyalExchangeTab.png" usemap="#RoyalExchangeTab-map" alt="RoyalExchangeTab" align="top"> 
<map name="RoyalExchangeTab-map">
    <area target="" alt="Royal Exchanges<p>Once an alignment is chosen, a Royal Exchange button will appear in the Upgrades tab, leading to a window where individual Faction Coin Exchanges can be purchased." research="Royal Exchanges<p>Once an alignment is chosen, a Royal Exchange button will appear in the Upgrades tab, leading to a window where individual Faction Coin Exchanges can be purchased." coords="3,4,49,47" shape="rect">
</map>
<img src="http://musicfamily.org/realm/Factions/picks/RoyalExchangeWindow.png" usemap="#RoyalExchangeEachWindow-map">
<map name="RoyalExchangeEachWindow-map">
    <area target="" alt="Click each of these to buy Royal Exchanges" research="Click each of these to buy Royal Exchanges" coords="272,49,310,220" shape="rect">
    <area target="" alt="Click this button to change how many Royal Exchanges you buy at once<p>Can be set to buy 1, 10, 100, 1000 or buy maximum amount" research="Click this button to change how many Royal Exchanges you buy at once<p>Can be set to buy 1, 10, 100, 1000 or buy maximum amount" coords="119,223,235,245" shape="rect">
    <area target="" alt="These are the different Factions and shows how many Royal Exchanges you currently own" research="These are the different Factions and shows how many Royal Exchanges you currently own" coords="39,29,101,216" shape="rect">
    <area target="" alt="This shows your current Royal Xechange Bonus (This number is meaningless and misleading, and should be ignored)" research="This shows your current Royal Exchange Bonus (This number is meaningless and misleading, and should be ignored)" coords="110,31,143,216" shape="rect">
    <area target="" alt="This shows how many Royal Exchanges you can buy and how much it will cost in Faction Coins" research="This shows how many Royal Exchanges you can buy and how much it will cost in Faction Coins" coords="161,34,261,215" shape="rect">


</map>












<?php include "../scripts/footer.html"; ?>