<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en">
<head>
<?php include "../scripts/header.html"; ?>
<h6><img src="http://musicfamily.org/realm/Factions/picks/ChallengesTopPage.png"></h6>
<p><a href="http://musicfamily.org/realm/Fairy/"><b>Fairy</b></a>
<a href="http://musicfamily.org/realm/Elf/"><b>Elf</b></a>
<a href="http://musicfamily.org/realm/Angel/"><b>Angel</b></a>
<a href="http://musicfamily.org/realm/Goblin/"><b>Goblin</b></a>
<a href="http://musicfamily.org/realm/Undead/"><b>Undead</b></a>
<a href="http://musicfamily.org/realm/Demon/"><b>Demon</b></a>
<p><a href="http://musicfamily.org/realm/Titan/"><b>Titan</b></a>
<a href="http://musicfamily.org/realm/Druid/"><b>Druid</b></a>
<a href="http://musicfamily.org/realm/Faceless/"><b>Faceless</b></a>
<a href="http://musicfamily.org/realm/Dwarf/"><b>Dwarf</b></a>
<a href="http://musicfamily.org/realm/Drow/"><b>Drow</b></a>
<a href="http://musicfamily.org/realm/Dragons/"><b>Dragons</b></a>
<p>Prove your loyalty and dedication to the factions by completing their unique Challenges. You will be rewarded with new perks and upgrades to help in your Realm Grinder progress!
<p>Upon reaching R2, a "Challenge" button will appear on the left leading to the Challenge window. There, your first, or next, challenge(s) will be visible, and hovering over the challenge icon will reveal the necessary requirements to unlock it.
<p>There are several Tier challenges for each Faction. The Tiers appear as you advance, and hence can only be completed in order. You can accomplish multiple Tiers on the same run, you just cannot get later Tiers before earlier Tiers.
<p><b>Vanilla Faction challenges</b>: Tier 1 upgrades boost the faction it belongs to. Tier 2 upgrades boosts another Faction. Last Tier upgrades are universal and boost basic perks. Completing all the challenges of a Faction rewards a spell upgrade. The last Tiers and Spell upgrades can be used also with Mercenaries, and their respective Factions, with or without Dwarf or Drow.
<p><b>Neutral Faction challenges</b>: Tier 1 upgrades boost it's own faction, Tier 2 and Tier 3 upgrades boosts each other Neutral Faction, and Tier 4 upgrades are universal.
<p><b>Prestige Faction challenges</b>: Tier 1 upgrades boost Dwarven-Angels or Drow-Demons, Tier 2 upgrades boost Dwarven-Fairies or Drow-Goblins, Tier 3 upgrades boost Dwarven-Elves or Drow-Undead, Tier 4 upgrades boost all Dwarven or all Drow, and Tier 5 upgrades are universal.
<p>Once you have unlocked a challenge, the perks relative to the faction you are playing, being costless, will be turned on by default after the faction's spell upgrade has been purchased. These can be turned on and off by clicking on their respective icon In the Challenge window.
<p><img src="http://musicfamily.org/realm/Factions/picks/AllChallenges.png" usemap="#AllChallenges-map">
<map name="AllChallenges-map">
    <area target="" research="Fairy Challenge Final Reward<p>Name: Fairy Orchestra<p>Effect: Each assistant generates 3 times as many faction coins while Fairy Chanting is active." coords="4,48,63,100" shape="rect">
    <area target="" research="Fairy Challenge 1</b>:  <p><p>Description: The Fairies are small and mighty, they can turn little things in to all you ever need. Speed is paramount and they do not tolerate cheating!<p>Requirements: 2 Reincarnations, Fairy Choir spell upgrade, Play as Fairy<p>Buy only Farms, Inns and Blacksmiths and all Fairy Faction upgrades within 1 minute of a new game.<p>Upgrade: Good for Fairy<p>Effect: You gain a free assistant for every fairy upgrade you have.<p>Tips: Do excavations to quickly get the Fairy Heritage upgrade. Don't forget the Fairy Choir spell upgrade." coords="71,49,126,100" shape="rect">
    <area target="" research="Fairy Challenge 2<p>Name: Donations<p>Description: Our farmers' crops are not growing. Perhaps a little magic can help change that.<p>Requirements: 8 Reincarnations, Fairy Bloodline, Play as Fairy<p>Cast Fairy Chanting within 30 seconds of a new game with over 1000 Farms.<p>Upgrade: Good for Goblin<p>Effect: Tax collections give 10 more seconds worth of coins and Faction Coins.<p>Tips: This is easiest just before you reincarnate, Grab the fairy and dwarf upgrades as quickly as possible, buy 1k farms, and hit the spell.<p>Don't forget to purchase the Bloodline within the time limit." coords="135,47,189,100" shape="rect">
    <area target="" research="Fairy Challenge 3<p>Name: Enchanted Lands<p>Description: The Fairies have developed a taste for honey. Find out quickly if they have a queen!<p>Requirements: 18 Reincarnations and Fairy Unique Building, Play as Fairy<p>Have Swarm of Fairies give 60 Fairy assistants in under a minute of a new game.(8190, total, of Farms, Inns and Blacksmiths and you don't have to buy the upgrade itself.)<p>Upgrade: Good for All<p>Effect: Increase mana regeneration based on the number of buildings you own.<p>Formula: (0.1x)^2.25, where x is your Buildings Owned (This Game) stat.<p>Tip: Use Goblin Bloodline.<p>Note: Tier 3 challenges cannot be done as Drow or Dwarf Factions, because you can't buy the U building." coords="200,47,251,100" shape="rect">
    <area target="" research="Elf Challenge Final Reward<p>Name: Star Blessing<p>Effect: Clicks from the Sun Blessing spell upgrade have a 5% increased chance to trigger Eleven (3,2) Elven Luck." coords="6,151,62,205" shape="rect">
    <area target="" research="Elf Challenge 1<p>Name: Advanced Civilization<p>Description: The Eleven council have asked you to provide proof of your loyalty to their cause. Hopefully you'll be quick and efficient enough to impress them.<p>Requirements: 2 Reincarnations, Sun Blessing Spell upgrade, Play as Elf.<p>Get more than 400,000 Elven Coins in under 1 hour of a new game.<p>Upgrade: good for Elf<p>Effect: Reduces Elven Exchange cost multiplier. Reduces cost multiplier by 0.025; with no other reductions applying, the multiplier will be 1.075 instead of 1.1.<p>Tips: Play as Elf, Don't forget to use excavations." coords="71,151,126,204" shape="rect">
    <area target="" research="Elf Challenge 2<p>Name: Light Collector<p>Description: The elven council has asked you to gather countless stars. Time is essence!<p>Requirements: 8 Reincarnations, Elf Bloodline, Play as Elf<p>Gather 60,000 automatic clicks in less than 2 hours.<p><p>Upgrade: Good for Angel<p>Effect: Increase Holy Light power by 10%.<p>" coords="136,151,189,204" shape="rect">
    <area target="" research="Elf Challenge 3<p>Name: Runic Conversion<p>Description: The elven council intends to use the light you've gathered as a weapon against their corrupt cousins, as soon as they detect weakness.<p>Note: Tier 3 challenges cannot be done as Drow or Dwarf Factions.<p>Requirements: 18 Reincarnations and Elven Unique Building, Play as Elf<p>Buy 150 Royal Exchange of each Faction, having zero Drow Exchanges.(~323,543,367 of each faction coin)</p><p>Upgrade: Good for all<p>Effect: Increase your mana regeneration by +0.85 m/s for every 100 Royal Exchanges purchased.<p>Note: Tier 3 challenges cannot be done as Drow or Dwarf Factions, because you can't buy the U building." coords="200,151,251,204" shape="rect">
    <area target="" research="Angel Challenge Final Reward<p>Name: God's Throne<p>Effect: Mana regeneration is increased by 20% while God's Hand is active." coords="7,255,62,309" shape="rect">
    <area target="" research="Angel Challenge 1<p>Name: Efficient Magic<p>Description: The blazing have entrusted you with a sacred mission: Purify the denizens of the realm with the most holy lights. Hurry up, corruption is spreading fast.<p>Requirements: 2 Reincarnations, God's Rest spell upgrade, Play as Angel<p>Cast 50 Holy Lights during daytime (6am-6pm local time) within 20 minutes of a new game.<p>Upgrade: Good for Angel<p>Effect: Reduce all spell costs by 10% (calculated *after* Angel (2,3) Angelic Wisdom).<p>Tips: Play as Angel, Recommended +1 B (1E9) gems. You will need a min mana regen of 60 m/s get enough Holy Light autocasts. Avoid purchasing Angelic Dominance (3,2). May require the Demon Bloodline.</p>" coords="73,255,126,308" shape="rect">
    <area target="" research="Angel Challenge 2<p>Name: Mana Crypts<p>Description: The archangel leaders have entrusted you on a sacred mission:quickly harvest enough magical power to become a beacon of magical selflessness. Extorting from the poor is forbidden.<p>Requirements: 8 Reincarnations, Angel Bloodline, Play as Angel<p>Generate 500,000 mana in less than 3 hours without casting a single Tax Collection<p>Upgrade: Good for Undead<p>Effect: Increases maximum mana by 25%.<p>Tips: Avoid getting Angelic Wisdom (2,2) and Angelic Dominance (3,2) because they reduce your mana-spent-per-second ability, if you are still finding yourself with a full mana pool, you can also turn off your Angel 1 perk. Tip: Autocast God's Hand with bar at 0. Add in CtA if excess mana builds up. When mana regen gets too high, just put every spell on Gold autocast (Not TC of course)." coords="136,255,187,308" shape="rect">
    <area target="" research="Angel Challenge 3<p>Name: Nephilim's Blessing<p>Description: The fallen nephilim have noticed your abilities and have entrusted you with a secret mission: Spread false hope upon the legends of mortals<p>Requirements: 18 Reincarnations and Angel Unique Building, Play as Angel, Demon Bloodline<p>Have 2000 Halls of Legends, and no good buildings.<p>Upgrade: Good for All<p>Effect: Halls of Legends benefit from any Certificate, Validation, or Affirmation alignment upgrade.<p>Note: Tier 3 challenges cannot be done as Drow or Dwarf Factions, because you can't buy the U building." coords="200,255,251,308" shape="rect">
    <area target="" research="Goblin Final Reward<p>Name: Avarice Drive<p>Effect: Increase Goblin's Greed duration by 5 seconds." coords="7,359,62,413" shape="rect">
    <area target="" research="Goblin Challenge 1<p>Name: Discount Season<p>Description: The goblin king has revealed the secrets to his race's success. Patience and persistence.<p>Requirements: 2 Reincarnations, Greed Drive spell upgrade, Play as Goblin.<p>Have Green Fingers Discount roll more than 1000 seconds worth of production.<p>Note that despite GFD's description saying it works offline, it does not work in the same way. Consequently this challenge cannot be completed offline.<p>Upgrade: Good for Goblin<p>Effect: Goblin (3,3) Green Fingers Discount triggers every 8 minutes instead.<p>Tip 1: While Green Fingers Discount says it works offline, it does not work in the same way as online, and this challenge cannot be completed offline or when coming online based on the offline effect of GFD. The challenge can be attempted in multiple tabs simultaneously, provided the save you load into the tabs does not yet have GFD purchased.<p>Tip 2: Play as Goblin" coords="73,359,126,413" shape="rect">
    <area target="" research="Goblin Challenge 2<p>Name: Elite Warriors<p>Description: Goblin are used to unimaginable wealth. They will work for you after you bribe them generously and show them your worth.<p>Requirements: 8 Reincarnations, Goblin Bloodline, Play as Goblin<p>Buy over 250 upgrades and 17,000 buildings.<p>Upgrade: Good for Demon<p>Effect: 10% of your purchased upgrades are added to your total trophy count for Hellfire Blast and Hall of Legends purposes." coords="137,359,191,413" shape="rect">
    <area target="" research="Goblin Challenge 3<p>Name: Smuggled Jewels<p>Description: The goblin king wants a castle made of jewels all to himself.<p>Requirements: 18 Reincarnations, Goblin Bloodline, Goblin Unique Building, Play as Goblin<p>Have at least 1 Qavg (1E75) gems in the abdication treasury.<p>Upgrade: Good for All<p>Effect: Increase production bonus from Gems by 0.005% for each upgrade purchased.<p>Note: Tier 3 challenges cannot be done as Drow or Dwarf Factions, because you can't buy the U building." coords="200,359,253,411" shape="rect">
    <area target="" research="Undead Final Reward<p>Name: Midnight Time<p>Effect: Increase Night Time assistant bonus based on total time spent offline.Formula: 0.2 * x0.7%, where x is your Time Spent Offline (Total) stat in seconds." coords="9,464,64,515" shape="rect">
    <area target="" research="Undead Challenge 1<p>Name: Deadly Impatience<p>Description: The walking dead aren't very fond of a living being among their kind. Fortunately for you, an army of shambling corpses is slow to both think and move.<p>Requirements: Get 6 assistants via Undead Heritage, True Night spell upgrade, Play as Undead.<p>Note: This takes 11 hours, 6 minutes, 40 seconds and the heritage doesn't really have to be bought.<p>Upgrade: Good for Undead<p>Effect: Undead Heritage works 400% faster.<p>Tips: Play as Undead<p>Awarded if your playtime is at least 11h, 6m, 40s and you have True Night and the Undead Trade Treaty. You do not need to own the heritage or have it unlocked, and no upgrades reduce the time required." coords="71,462,125,516" shape="rect">
    <area target="" research="Undead Challenge 2<p>Name: Experienced Helpers<p>Description: The walking dead, pleased with your newfound strenghs, send you on a mission to reap as many souls as possible under the cover of the Night to bolster their forces.<p>Requirements: 8 Reincarnations, Undead Bloodline, Play as Undead<p>Cast Night Time when you have over 100 assistants.<p>Upgrade: Good for Elf<p>Effect: Assistant production is increased by 10%." coords="133,463,191,518" shape="rect">
    <area target="" research="Undead Challenge 3<p>Name: Death Knights<p>Description: The walking dead are prepared for a zombie invasion.Their last task for you is to loot the local cemeteries for possible equipment.<p>Requirements: 18 Reincarnations, Undead Unique Building, Play as Undead<p>Collect 100M (1E8) Faction coins.<p>Upgrade: Good for All<p><b>Effect</b>: Increase your number of assistants by 10%.<p>Note: Tier 3 challenges cannot be done as Drow or Dwarf Factions, because you can't buy the U building." coords="198,462,254,517" shape="rect">
    <area target="" research="Demon Final Reward<p>Name: Hellfire Burst<p>Effect: Reduces Hellfire Blast mana cost based on the number of trophies you have unlocked.Formula: floor(0.25 * x), where x is the amount of trophies unlocked." coords="9,567,64,621" shape="rect">
    <area target="" research="Demon Challenge 1<p>Name: Trophy Collectors<p>Description: The Prince of Hell wish to test your skills at gathering coins without outside help.<p>Requirements: 2 Reincarnations,Hellfire Blast spell upgrade, Play as Demon.<p>Collect 5000 Demon Coins without using Gem Power, Reincarnation Power, Researches, Challenges nor Excavations. (Only scrying for Faction coins is permitted)<p>Upgrade: Good for Demon<p>Effect: Reduce all Heritage costs, except for the Mercenary Badge, based on the percentage of trophies unlocked.<p>Formula</b>: 1 - (current / max trophies)<p>Tips: Play as Demon<p>Either be very patient, or have a low number of gems to be able purchase the bloodline (Elves bloodline recommended). Ruby power is okay and you can use challenges provided you turn them off at the end to get the reward." coords="73,567,126,620" shape="rect">
    <area target="" research="Demon Challenge 2<p>Name: Legendary Antics<p>Description: The Princes of Hell demand a tribute, unleash the beast by extorting every other faction in this realm. You should perform this task with haste, for they are well known for their impatience.<p>Requirements: 8 Reincarnations, Demon Bloodline, Play as Demon<p>Have exactly 666 Royal Exchanges across all factions, with 0 Demon Exchanges, in under 666 seconds current playtime.<p>Upgrade: Good for Fairy<p>Effect: Increase max mana by 6.66% of your number of Halls of Legends.<p>Tips: High gem and low Excavations (relative). Work up enough coins to excavate 96 REs, until the number says &quot;(96)&quot;, and then buy 1 or 2 more to get exactly 666. Don't buy Demon exchanges. Drow's blackmail upgrade helps the challenge, and the exchanges don't have to be spread evenly." coords="136,567,191,620" shape="rect">
    <area target="" research="Demon Challenge 3<p>Name: Passage to Tartarus<p>Description: The Demon King has ordered you to prove your might to the entire realm.<p>Requirements: 18 Reincarnations, Demon Unique Building, Play as Demon<p>Have at least 2000 Halls of Legends and 333 Trophies.<p>Upgrade: Good for All<p>Effect: Increase the production of all buildings by 0.1% per trophy you have unlocked.<p>Tips: Use Goblin Bloodline, can be easily done around Uvg gems.<p>Note: Tier 3 challenges cannot be done as Drow or Dwarf Factions, because you can't buy the U building." coords="197,567,253,620" shape="rect">
    <area target="" research="Titan Final Reward<p>Name: Thunderstorm<p>Effect: Lightning Strike now grants more Faction Coins based on your Faction Coin find chance.Formula: round(x0.8)%, where x is your current chance to find Faction Coins." coords="7,669,62,725" shape="rect">
    <area target="" research="Titan Challenge 1<p>Name: Rich Followers<p>Description: The mighty titans have decided to give you and a dozen of you most loyal subjects a chance to prove your kingdom's economy is as strong as theirs.<p>Requirements: 4 Reincarnations, Lightning Storm spell upgrade, Angel 1 and Goblin 1 challenges completed, Play as Titan.<p>Have at least 13 assistants and have exactly 13 times that many Royal Exchanges (Total) - Check the total in stats tab.(e.g. 15 assistants = 195 Royal Exchanges)<p>Upgrade: Good for Titan<p>Effect: You gain a free assistant for every 80 Royal Exchanges you bought.<p>Tips: Mostly for R0 and early R# players: Careful of using Ruby power. Avoid Reincarnation power, Undead &amp; Drow bloodline, Undead 3 &amp; Titan 3 challenges. By precaution, don't even get the other assistant upgrades. Once everything is built, buy exactly 13 assistants (careful with the option &quot;MultiBuy upgrade series&quot;) Check your stats, when you get close to the required 169 total REs, switch to buying one by one - careful to not over-buy.<p>Note: You can have more than 13 assistants so long as you have the required 13*(number of assistants) REs. (26 assistants => 338 RE)" coords="71,670,126,725" shape="rect">
    <area target="" research="Titan Challenge 2<p>Name: Balanced Economy<p>Description: The mighty titans wish for you to harness arcane powers through your fingertips.<p>Requirements: 9 Reincarnations, Titan Bloodline, Play as Titan, Angel 2 and Goblin 2 challenges completed, Play as Titan.<p>Click the treasure 80 times while having at least 3 active spells in a single session.<p>Upgrade: Good for Faceless<p>Effect: Faceless' Hive Mind playtime is increased by 10% of the playtime of all the other factions.<p>Tips: This challenge does not need to be done within one spell combo. In addition, due to a bug, it counts one click per second if you have at least one assistant. It's possible to meet the condition without clicking the treasure at all while spells are active by casting 3 spells that last 20 seconds together 4 times." coords="134,670,189,725" shape="rect">
    <area target="" research="Titan Challenge 3<p>Name: Balanced Economy<p>Description: The mighty titans are almost ready to accept you into their pantheon. They request that you gather enough offerings to mark you ascension.<p>Requirements: 19 Reincarnations, 1000 excavations, Angel 3 and Goblin 3 challenges completed, Play as Titan.<p>Generate 1 B (1E9) Faction Coins with the Lightning Strike spell.<p>Upgrade: Good for Druid<p>Effect: Gain additional max mana based on the number of faction coins generated this game.<p>Formula: round(2.5 * log10(1+x))%, where x is your Faction Coins Gained (This Game) stat." coords="198,671,251,725" shape="rect">
    <area target="" research="Titan Challenge 4<p>Name: Storm of Wealth<p>Description: The mighty titans wish to cement their legendary status for perpetuity. You must focus on this task and no other to be able to join them.<p>Requirements: 25 Reincarnations, Titan Unique Building, Play as Titan.<p>Hit Halls of Legends with Lightning Strike 2 times in a row while having all building types and no researches.<p>Upgrade: Good for All<p>Effect: Every 5 minutes you automatically generate Faction Coins based on the amount of Gems you own. <p>Formula: round(0.05 * x), where x is the number of Faction Coins generated by Lightning Strike.<p>Hint: Buy Olympian Hall, generate as much mana per second from non-Research methods (mostly Heritages), set Lightning Strike on bronze (Ctrl+Shift). Wait. On average, it takes 132 strikes to get two in a row on HoLs[1]. The Realm Weather Service can help to forecast." coords="263,671,315,723" shape="rect">
    <area target="" research="Druid Final Reward<p>Name: Primal Balance<p>Effect: Grand Balance now affects extra buildings based on total mana spent.<p>Formula: floor (x0.2 / 10), where x is your Mana Produced (Total) stat.<p><img src=&quot;http://musicfamily.org/realm/Factions/picks/PrimalBalance.png&quot; alt=&quot;Primal Balance&quot; align=&quot;middle&quot;></a>" coords="9,775,64,827" shape="rect">
    <area target="" research="Druid Challenge 1<p>Name: Silent Assistance<p>Description: The ancient druids request evidence that you are a servant of balance before your inclusion to their ranks.<p>Requirements: 4 Reincarnations, Halls of Balance spell upgrade, Elf 1 and Demon 1 challenges completed, Play as Druid.<p>Make the building targeted by Grand Balance surpass 99.9% of your production.<p>Upgrade: Good for Druid<p>Effect: Animal Companions (1,2) works faster.<p>Formula: floor((sqrt(1 + 16 * x) - 1) / 2), where x is your Playtime (This Game) stat in hours.<p>Tips: Make sure your least-producing building still makes up a large proportion of your production (2% and up). This will necessarily balance the production of each of your other buildings around 9.09% (= 1/11). Upgrade buildings only as required to balance them. Building more Farms, Inns and Blacksmiths will increase the multiplier of the final cast of Grand Balance." coords="71,774,126,829" shape="rect">
    <area target="" research="Druid Challenge 2<p>Name: Balanced Current<p>Description: Our sorcerers are desperately trying to stabilize the balance of the realm, this is your opportunity to gain their favor - and live another day.<p>Requirements: 9 Reincarnations, Druid Bloodline, Play as Druid, Elf 2 and Demon 2 challenges completed.<p>Have exactly 1600 of each building types, for 16 full Grand Balance casts. (The 16 casts only counts after you have all the 1600 buildings).<p>Upgrade: Good for Titan<p>Effect: Mana regeneration is increased by 1% for every 200 Stone Pillars you own" coords="135,775,191,829" shape="rect">
    <area target="" research="Druid Challenge 3<p>Name: Eldritch Architecture<p>Description: Pleased with your efforts, the elder druids assigned you with an important task; empower our obelisks, sacred churches and sarcophaguses.<p>Requirements: 19 Reincarnations, 1000 excavations, Elf 3 and Demon 3 challenges completed, Play as Druid.<p>Have Grand Balance target Stone Pillars, Monasteries and Ancient Pyramids in that order, for 3 casts of the Grand Balance spell.<p>Upgrade: Good for Faceless<p>Effect: You gain 1.25 additional max mana for every 4 Labyrinths owned.<p>Tips: Now that Grand Balance affects 0 buildings, it will target the next building down the list:<p>1.Buy Max Everything except Stone Pillars, Monasteries and Ancient Pyramids > Cast Grand Balance<p>2.Buy Max Stone Pillars > Cast Grand Balance<p>3.Buy Max Monasteries  > Cast Grand Balance." coords="198,773,254,827" shape="rect">
    <area target="" research="Druid Challenge 4<p>Name: Overflowing Mana<p>Description: The Druids need more spell power, but they are worried about outside influences throwing off their balance.<p>Requirements: 25 Reincarnations, Druid Unique Building, Play as Druid.<p>Cast 13 Grand Balances in the first 5 minutes of a playthrough with 0 non-Druid researches.<p>Upgrade: Good for All<p>Effect: All spell durations increased by 1% for every 1,500 max mana.<p>Tips: Halls of Balance is required to complete the challenge; however, as it increases the spell duration, you should refrain from buying it until the end of the five minutes. Make sure you have some excavations to buy the Heritages. (Angel Heritage and Angel 1 challenge both boost your m/s.) To achive this, you need a min. of 50 m/s with Grand Balance continuously casting during 13 full casts. Reward given at 5 minute mark regardless of when achieved." coords="262,774,317,827" shape="rect">
    <area target="" research="Faceless Challenge Final Reward<p>Name: Focused Thoughts<p>Effect: Give Brainwave a headstart based on its activity time in this game, with a minimum of 1 minute, then grows up to maximum.<p>Formula: +1 second per 5 minutes Active Time (This Game)." coords="9,878,63,932" shape="rect">
    <area target="" research="Faceless Challenge 1<p>Name: Recruitment<p>Description: You are always growing - but what to do when you can only start from a single cell with no means of survival?<p>Requirements: 4 Reincarnations, All Faceless Faction upgrades, Fairy 1 and Undead 1 challenges completed, Play as Faceless.<p>Only have assistants from Faceless (2,2) Mitosis.<p>(Do not have any other upgrades giving assistants: Reincarnation Power, Undead Heritage, Undead &amp; Titan 3 challenges etc.)<p><b>Upgrade: Good for Faceless<p>Effect: Gain an extra assistant every minute, resets every hour<p>Tips: Beware of using Ruby or Reincarnation power. Also make sure to disable the Undead 3 Challenge bonus.<p>Tips: Buy only the first Faceless upgrades and none of the other upgrades then buy Mitosis last" coords="71,878,126,932" shape="rect">
    <area target="" research="Faceless Challenge 2<p>Name: Mystic Maze<p>Description: Your hive superiors have ordered you to setup a base without alerting any nearby enemies.<p>Requirements: 9 Reincarnations, Faceless Bloodline, Play as Faceless, Fairy 2 and Undead 2 challenges completed, Play as Faceless.<p>Get 1000 Labyrinths (Sunken Cities) using Faceless (1,1) Territorial Expanse and not buying any at all.<p>Note: Buy every building except Labyrinth<p>Upgrade: Good for Druid<p>Effect: You gain +10 max mana for every 20 labyrinths built" coords="135,878,191,931" shape="rect">
    <area target="" research="Faceless Challenge 3<p>Name: Cyclopean Army<p>Description: Our enemies, the Outer Gods, have returned. Use mind control to enhance our forces and repel this threat.<p>Requirements: 19 Reincarnations, 1000 excavations, Fairy 3 and Undead 3 challenges completed, Play as Faceless.<p>Cast Call to Arms, Gem Grinder and Spiritual Surge during last 20 seconds of Brainwave.<p>Upgrade: Good for Titan<p>Effect: Gain extra assistants based on your royal exchange bonus.<p>Formula: floor(2 * x0.5), where x is your Royal Exchange Bonus." coords="198,878,253,931" shape="rect">
    <area target="" research="Faceless Challenge 4<p>Name: Omnipresence<p>Description: We are suffering attacks from another Hive. It's time to remind them the power of our master.<p>Requirements: 25 Reincarnations, Faceless Unique Building, Play as Faceless.<p>Get Hive Mind (3,3) bonus to at least 1890%.<p>Upgrade: Good for All<p>Effect: All factions receive 5% of your Hive Mind bonus.<p>Tips: This is the equivalent of about 8.5 days of time spent allied with Faceless. Getting the Titan Tier 2 challenge Harmony of Thoughts will help increase your Faceless playtime." coords="263,878,317,932" shape="rect">
    <area target="" research="Dwarf Challenge Final Reward<p>Name: Iron Grip<p>Effect: Increase Diamond Pickaxe duration by 8 seconds, and its bonus to Faction Coin find chance is passively applied as a multiplier to excavations Faction Coin rewards." coords="7,981,62,1036" shape="rect">
    <area target="" research="Dwarf Challenge 1<p>Name: Enchanted Crystals<p>Description: The dwarven lords have asked you to enchant their pickaxes.<p>Requirements: 6 Reincarnations,Minedwarf spell upgrade, Elven 1, Angel 1, and Fairy 1 challenges completed, Play as Angel/Dwarf.<p>Cast 20 Tax Collections while having at least 4 spells active.<p>Upgrade: Good for Angel-Dwarf<p>Effect: Reduce all spells' cost based on the amount of gems you own.<p>Formula: \frac {\ln {(1 + G^{1 + {\frac A {10} } }) } } {20}%; where G is the number of gems you own and A is the number of times you ascended." coords="71,982,126,1036" shape="rect">
    <area target="" research="Dwarf Challenge 2<p>Name: Biased Architeture<p>Description: The dwarven lords have asked you to provide their people with ale. Hurry up, the dwarves are getting thirsty!<p>Requirements:11 Reincarnations, Dwarven Bloodline,Play as Good Faction and Dwarf, Elven 2, Angel 2, Fairy 2, and Dwarven 1 challenges completed, Play as Fairy/Dwarf.<p>Build 2,750 Inns within 2 minutes of a new game.<p>Upgrade: Good for Fairy-Dwarf<p>Effect: Reduce Inn and Blacksmith cost multipliers.<p>Reduces cost multiplier by 0.01; with no other reductions applying, the multiplier will be 1.14 instead of 1.15." coords="135,980,189,1035" shape="rect">
    <area target="" research="Dwarf Challenge 3<p>Name: Rich Miners<p>Description: The dwarven lords have asked you to help them collect trade supplies for all the factions of the realm.<p>Requirements: 21 Reincarnations, 1750 excavations, Elven 3, Angel 3, Fairy 3, and Dwarven 2 challenges completed, Play as Elf/Dwarf.<p>Collect at least 100,000 Faction Coins with a single Tax Collection.<p>Upgrade: Good for Elven-Dwarf<p>Effect: Increase your Faction Coin find chance by 100% for each active spell." coords="197,981,253,1035" shape="rect">
    <area target="" research="Dwarf Challenge 4<p>Name: Paladins<p>Description: The dwarven lords are interested in training the troops into pious warriors. Begin the initiation as soon as possible.<p>Requirements: 27 Reincarnations, 2000 excavations, Dwarven Challenge 3 complete.<p>Have at least 3,500 Knights Jousts and as many Wizard Towers, Play as Dwarf.<p>Upgrade: Good for Dwarf<p>Effect: Increase Holy Light bonus based on the combined amount of Knights Jousts and Wizard Towers you own.<p>Formula: 50x0.35%p, where x is the number of Knight Jousts and Wizard Towers you own." coords="264,982,316,1035" shape="rect">
    <area target="" research="Dwarf Challenge 5<p>Name: Underground Foundations<p>Description: The dwarven lords have asked you to create underground tunnels connecting the allied factions.<p>Requirements: 33 Reincarnations, Dwarven Unique Building<p>Have 3250 (or 2500 if ascended) Excavations.<p>Upgrade: Good for All<p>Effect: All buildings count 20% more for all purposes." coords="326,982,380,1036" shape="rect">
    <area target="" research="Drow Challenge Final Reward<p>Name: Versatile Combo<p>Effect: Increase Combo Strike counter based on the amount of spells cast in this game, not including Tax Collection.<p>New Combo Strike Counter<p>Formula: C - Ctax, where C is your Spells Cast (This Game) stat and Ctax is your Tax Collection Cast This Game." coords="6,1082,65,1140" shape="rect">
    <area target="" research="Drow Challenge 1<p><img src=&quot;http://musicfamily.org/realm/Factions/picks/OrganizedCrimeChallenges.png&quot; alt=&quot;Organized Crime&quot; align=&quot;middle&quot;> Organized Crime<p>Description: The mysterious drow wish for you to prove your murderous honor to them.<p>Requirements: 6 Reincarnations, Perfect Combo spell upgrade, Goblin 1, Demon 1, and Undead 1 challenges completed, Play as Demon/Drow<p>Have Honor Among Killers, at least 1000 Royal Exchanges, and 500 trophies.<p>Upgrade: Good for Demon-Drow<p>Effect: Increase Royal Exchange bonus by 0.03% per trophy you own." coords="71,1085,127,1140" shape="rect">
    <area target="" research="Drow Challenge 2<p>Name: Dark Elegance<p>Description: The Spider Queen is not pleased with some of her worshippers. You must weed out the weak and sacrifice them at the temple altar.<p>Requirements: 11 Reincarnations, Drow Bloodline, Play as Evil Faction and Drow, Goblin 2, Demon 2, Undead 2, and Drow 1 challenges completed, Play as Goblin/Drow<p>Build 2000 Spider Sanctuaries (Dark Temples).<p>Upgrade: Good for Goblin-Drow<p>Effect: Increase the production of all buildings based on faction coins earned this game.<p>Formula: log2(1 + x), where x is your Faction Coins Gained (This Game) stat." coords="134,1085,191,1140" shape="rect">
    <area target="" research="Drow Challenge 3<p>Name: Sorcerer's Pact<p>Description: A legion of interlopers have invaded our sanctuaries. Work yourselves into a rage and tear them apart.<p>Requirements: 21 Reincarnations, 1750 excavations, Goblin 3, Demon 3, Undead 3, and Drow 2 challenges completed, Play as Undead/Drow.<p>Have at least 2 hours of activity time for both Blood Frenzy and Combo Strike(1 Hour for each).<p>Upgrade: Good for Undead-Drow<p>Effect: Online Time (This game) is added to Offline Time (This game)." coords="197,1086,254,1140" shape="rect">
    <area target="" research="Drow Challenge 4<p>Name: Trained Assassins<p>Description: There is a civil war between 2 Spider Gods. Bolster our forces and wipe the weaklings off the face of the realm.<p>Requirements: 27 Reincarnations, 2000 excavations, Drow Challenge 3 complete, Play as Drow.<p>Cast Call to Arms with at least 35,000 buildings.<p>Upgrade: Good for Drow<p>Effect: Increase your Offline Time (This Game) by 1 second for every 10 spells cast in this game." coords="262,1084,317,1140" shape="rect">
    <area target="" research="Drow Challenge 5<p>Name: Shadow Mirage<p>Description: It is time to emerge from the shadows. Our warriors will demonstrate their hard work and lead us to domination of the realm.<p>5 Requirements: 33 Reincarnations, Drow Unique Building, Play as Drow.<p>Have at least 2 hours offline (This Game) and at least 360 charges of Combo Strike.<p>Upgrade: Good for All<p>Effect: A fraction of your alignment spell bonus is applied passively.<p> Note: &quot;Fraction&quot; is equal to 5%." coords="325,1084,380,1140" shape="rect">
    <area target="" research="<p><b>In-Game Challenge Final Reward</b></p> <p><img src=&quot;http://musicfamily.org/realm/Factions/picks/PrismaticBreathChallenges.png&quot; alt=&quot;Prismatic Breath&quot; align=&quot;middle&quot;> <b>Prismatic Breath</b></p> <p><b>Effect</b>: While all 5 breaths are active, Reincarnations count double for all purposes. <p><b>Faction</b>: Dragon" coords="7,1189,63,1242" shape="rect">
    <area target="" research="<p><b>Dragon Challenge 1</b>:  <p><img src=&quot;http://musicfamily.org/realm/Factions/picks/SkyMonarchChallenges.png&quot; alt=&quot;Sky Monarch&quot; align=&quot;middle&quot;> <b>Sky Monarch</b></p> <p>&quot;The Titan leader has approached you with an offer you cannot refuse: Use the help of your Draconic allies to guard his domain and lightning itself will enchant your riches.&quot; <p>Have 18000 Halls of Legends.  <p><b>Requirements</b>: Reincarnations 48, Dragon's Roar upgrade, Completion of Titan, Druid, Faceless, Dwarven and Drow Challenge 1, Play as Titan/Dragon <p><b>Effect</b>: Mutiplicatively increase faction coin chance by 10% per Lightning Strike tier bought. <p><b>Effect</b>: Also increase Post-Ascension bonuses for Titan Drill and Titan Sized Walls. <p><b>Formula</b>: (250000^2)% and (25000^2) <p><b>Upgrade</b>: Good for Titan/Dragon" coords="71,1189,127,1242" shape="rect">
    <area target="" research="<p><b>Dragon Challenge 2</b>:  <p><img src=&quot;http://musicfamily.org/realm/Factions/picks/BarkscalesChallenges.png&quot; alt=&quot;Barkscales&quot; align=&quot;middle&quot;> <b>Barkscales</b></p> <p>&quot;Unstable power flows through your workforce. Prove to the Dragonlords you can sustain and control every sip of it.&quot; <p>Have Grand Balance affect 11 buildings.  <p><b>Requirements</b>: Reincarnation 51, Dragon Bloodline, Completion of Titan, Druid, Faceless, Dwarven and Drow Challenge 2, Completion Dragon Challenge 1, Play as Druid/Dragon, Generate at least 1e10 mana in this game. <p><b>Effect</b>: Increase Stone Pillars production by 2500% for each Grand Balance target. <p><b>Effect</b>: Also reduces all Spell Tier upgrade costs based on Grand Balance activity time in this game. <p><b>Formula</b>: max(0, (1-t/28)^9) t is Grand Balance activity time in days. <p><b>Upgrade</b>: Good for Druid/Dragon" coords="135,1189,191,1243" shape="rect">
    <area target="" research="<p><b>Dragon Challenge 3</b>:  <p><img src=&quot;http://musicfamily.org/realm/Factions/picks/SerpentQuellerChallenges.png&quot; alt=&quot;Serpent Queller&quot; align=&quot;middle&quot;> <b>Serpent Queller</b></p> <p>&quot;Legends tell of a terrible sea monster destroying ships and harbors. With your dragon and faceless allies you can finally form a powerful army to raid its underwater lair. Slaying the levaithan will not only earn your kingdom eternal glory, but will make the overseae emporium flourish once more.&quot; <p>Have 5500 Excavations. <p><b>Requirements</b>: Reincarnation 54, Completion of Titan, Druid, Faceless, Dwarven and Drow Challenge 3, Completion Dragon Challenge 2, Have a combined total of 40 days played as faceless and dragons with a minimum of 10 days as each one, Play as Faceles/Dragon <p><b>Effect</b>: Removes Deep Memory ascension penalty. <p><b>Effect</b>: Faction Coin find chance from Evolutive Mutation becomes multiplicative with increased effect.<p><b>Formula</b>: (3 * x^0.95)%, where x is your amount of Sunken Cities. <p><b>Upgrade</b>: Good for Faceless/Dragon" coords="200,1189,254,1242" shape="rect">
    <area target="" research="<p><b>Dragon Challenge 4</b>:  <p><img src=&quot;http://musicfamily.org/realm/Factions/picks/DraconstellationChallenges.png&quot; alt=&quot;Draconstellation&quot; align=&quot;middle&quot;> <b>Draconstellation</b></p> <p>&quot;Centuries ago, the Dragon race managed to stockpile the absolute pinnacle of wealth. Scattered in the stars, help them establish a stronger connection with the void between the realms.&quot; <p>Have 20,000 Iron Strongholds and have at least 4 Dragon's Breaths active at the same time. <p><b>Requirements</b>: Reincarnation 57, 46 Artifacts, Completion of Titan, Druid, Faceless, Dwarven and Drow challenge 4, Completion of Dragon challenge 3 <p><b>Effect</b>: Faction coins from excavations are increased based on the amount of artifacts you own.<p>Formula: x ^ 4.5 (%), where x is number of artifacts.<p><b>Upgrade</b>: Good for Dragon" coords="263,1186,320,1242" shape="rect">
    <area target="" research="<p><b>Dragon Challenge 5</b>:  <p><img src=&quot;http://musicfamily.org/realm/Factions/picks/AncientIncantationChallenges.png&quot; alt=&quot;Ancient Incantation&quot; align=&quot;middle&quot;> <b>Ancient Incantation</b></p> <p>&quot;You have affiliated with many magical races in the past, but none as potent as the dragons, whose very breath is among the strongest of forces. There might be some way for your wizards to exploit thi.&quot; <p>Have 5 spells active at tier 5. <p><b>Requirements</b>: Reincarnation 60, Dragon Unique Building, Completion of Dwarven and Drow challenge 5, Completion of Dragon challenge 4 <p><b>Effect</b>: Tax Collections are 20% more powerful for every spell tier you have active. <p><b>Upgrade</b>: Good for Any Prestige" coords="326,1189,384,1242" shape="rect">
    <area target="" research="<p><b>Dragon Challenge 6</b>:  <p><img src=&quot;http://musicfamily.org/realm/Factions/picks/DracometVaultChallenges.png&quot; alt=&quot;Dracomet Vault&quot; align=&quot;middle&quot;> <b>Dracomet Vault</b></p> <p>&quot;This backwater world has been conquered. The Dragonlords strive for greater riches. Follow the Dragon King, soar through the heavens and claim the energy of the cosmose.&quot; <p>Gather 2.5e18 faction coins, 1e141 diamond coins, 150,000 buildings, 2e10 mana produced, 7500 excavations, 6000 assistants, 300,000 max mana and 200,000 mana regen. <p><b>Requirements</b>: Reincarnation 63, Completion of Dragon challenge 5, 12,000 research points spent across all facilities <p><b>Effect</b>: Gem production is passively increased over time based on the amount of artifacts you own. Resets on Abdications. <p><b>Formula</b>: 0.001 * t^0.8 * a (t is playtime this game in minutes, a is artifacts found) <p><b>Upgrade</b>: Good for Any" coords="389,1189,447,1244" shape="rect">
</map>
<?php include "../scripts/footer.html"; ?>



