<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en">
<head>
<?php include "../scripts/header.html"; ?>
<br/><br/>
<b><center><font size="5">Historic Page, outdated and no longer worked on!</font></center></b>
<br/>
<p><b>Useful Tables</b></p>
<br/>
<br style="clear: both"/><hr>
    <a id="Companions"></a>
    <table class="numtable" align="left" >
        <thead>
        <tbody>
        <tr>
            <th colspan="2">Animal Companions (outdated)</th>
        </tr>
        <tr>
            <td>Hour of Playtime</td>
            <th>Assistants</th>
        </tr>
        <tbody>
        <tr>
            <td><center>0</td>
            <td><center>3</td>
        </tr>
        <tr>
            <td><center>1</td>
            <td><center>4</td>
        </tr>
        <tr>
            <td><center>2</td>
            <td><center>5</td>
        </tr>
        <tr>
            <td><center>3</td>
            <td><center>5</td>
        </tr>
        <tr>
            <td><center>4</td>
            <td><center>6</td>
        </tr>
        <tr>
            <td><center>5</td>
            <td><center>6</td>
        </tr>
        <tr>
            <td><center>6</td>
            <td><center>6</td>
        </tr>
        </tbody>
        <tr>
            <td><center>12</td>
            <td><center>8</td>
        </tr>
        </tbody>
        <tr>
           <td><center>18</td>
           <td><center>9</td>
        </tr>
        </tbody>
        <tr>
            <td><center>24</td>
            <td><center>11</td>
        </tr>
        <tr>
            <td><center>36</td>
            <td><center>12</td>
        </tr>
        <tr>
            <td><center>48</td>
            <td><center>14</td>
        </tr>
        <tr>
            <td><center>60</td>
            <td><center>15</td>
        </tr>
        <tr>
            <td><center>72</td>
            <td><center>17</td>
        </tr>
        </tbody>
        </thead>
    </table>
    <a id="TC3"></a>
    <table class="numtable" align="center" >
        <thead>
        <tr>
            <th colspan="3">God's Finger Time Table (outdated)</th>
        </tr>
        <tr>
            <th>Clicks Per Sec</th>
            <th>Days</th>
            <th>Hours</th>
        </tr>
        </thead>
        <tbody>
         <tr>
            <td><center>100</td>
            <td><center>11</td>
            <td><center>13</td>
        </tr>
         <tr>
            <td><center>200</td>
            <td><center>5</td>
            <td><center>18</td>
        </tr>
         <tr>
            <td><center>300</td>
            <td><center>3</td>
            <td><center>20</td>
        </tr>
         <tr>
            <td><center>400</td>
            <td><center>2</td>
            <td><center>21</td>
        </tr>
         <tr>
            <td><center>500</td>
            <td><center>2</td>
            <td><center>7</td>
        </tr>
         <tr>
            <td><center>600</td>
            <td><center>1</td>
            <td><center>22</td>
        </tr>
         <tr>
            <td><center>700</td>
            <td><center>1</td>
            <td><center>15</td>
        </tr>
         <tr>
            <td><center>800</td>
            <td><center>1</td>
            <td><center>10</td>
        </tr>
         <tr>
            <td><center>900</td>
            <td><center>1</td>
            <td><center>6</td>
        </tr>
         <tr>
            <td><center>1000</td>
            <td><center>1</td>
            <td><center>3</td>
        </tr>
         <tr>
            <td><center>1158</td>
            <td colspan="2"><center>Under 1 day</td>
        </tr>
        <tr>
            <th colspan="3">By Aramil Nailo</th>
        </tr>
       </tbody>
    </table>
    <br style="clear: both"/>
<hr>
    <a id="Primal Balance"></a>
    <center><table class="numtable" >
        <thead>
        <tr>
            <th colspan="6">Primal Balance (GB +10)</th>
        </tr>
        <tr>
            <th>Targets</th>
            <th>A0</th>
            <th>A1</th>
            <th>A2</th>
            <th>A3</th>
            <th>A4</th>
        </tr>
        </thead>
        <tbody>
        <tr>
            <td>1</td>
            <td>0</td>
            <td>0</td>
            <td>0</td>
            <td>0</td>
            <td>0</td>
        </tr>
        <tr>
            <td>+1</td>
            <td>1e5</td>
            <td>1e5</td>
            <td>1e5</td>
            <td>1e5</td>
            <td>1e5</td>
        </tr>
        <tr>
            <td>+2</td>
            <td>3.2e6</td>
            <td>5.250e6</td>
            <td>1.016e7</td>
            <td>2.560e7</td>
            <td>1.024e8</td>
        </tr>
        <tr>

            <td>+3</td>
            <td>2.430e7</td>
            <td>5.326e7</td>
            <td>1.516e8</td>
            <td>6.561e8</td>
            <td>5.905e9</td>
        </tr>
        <tr>
            <td>+4</td>
            <td>1.024e8</td>
            <td>2.756e8</td>
            <td>1.032e9</td>
            <td>6.554e9</td>
            <td>1.049e11</td>
        </tr>
        <tr>
            <td>+5</td>
            <td>3.125e8</td>
            <td>9.865e8</td>
            <td>4.569e9</td>
            <td>3.906e10</td>
            <td>9.766e11</td>
        </tr>
        <tr>
            <td>+6</td>
            <td>7.776e8</td>
            <td>2.796e9</td>
            <td>1.541e10</td>
            <td>1.680e11</td>
            <td>6.047e12</td>
        </tr>
        <tr>
            <td>+7</td>
            <td>1.681e9</td>
            <td>6.747e9</td>
            <td>4.305e10</td>
            <td>5.765e11</td>
            <td>2.825e13</td>
        </tr>
        <tr>
            <td>+8</td>
            <td>3.277e9</td>
            <td>1.447e10</td>
            <td>1.049e11</td>
            <td>1.678e12</td>
            <td>1.074e14</td>
        </tr>
        <tr>
            <td>+9</td>
            <td>5.905e9</td>
            <td>2.837e10</td>
            <td>2.299e11</td>
            <td>4.305e12</td>
            <td>3.487e14</td>
        </tr>
        <tr>
            <td>+10</td>
            <td>1e10</td>
            <td>5.179e10</td>
            <td>4.642e11</td>
            <td>1e13</td>
            <td>1e15</td>
        </tr>
        </tbody>
    </table></center>
<br style="clear: both"/>
<hr>
<?php include "../scripts/footer.html"; ?>
