<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en">
<head>
<?php include "../scripts/header.html"; ?>
<h6><img src="http://musicfamily.org/realm/Factions/picks/ExcavationTopPage.png"></h6>
<p><b>There are two kinds of artifacts</b></p>
<p><a href="/realm/QuestArtifacts" title="Quest Artifacts"><b>Quest Artifacts</b></a> and
<a href="/realm/LoreArtifacts" title="Lore Artifacts"><b>Lore Artifacts</b></a></p>
<p><b><font color="red">Artifact Sets at bottom</font></b></p>
<p><b>In-game description</b>
<p>Enter the Archeology Association to control the progress of your Excavations. There you will be able to fund more excavations to find Faction Coins, the rare Rubies and ancient Artifacts from the civilizations of the old.</p>
<p>Archaeology was first implemented in the "Ancient Races" expansion for introducing the Neutral Factions.</p>
<p>Excavating enables to find Rubies (See the <b><a target="_blank" href="http://musicfamily.org/realm/Rubies/">Ruby</a></b> page), with luck: Faction Coins, and at certain thresholds or under certain conditions: Artifacts. Specific artifacts are required to unlock the Neutral & Prestige Factions.</p>
<p>Some artifacts will reward direct bonuses and the amount of discovered artifacts take part in some Research upgrades.</p>
<p><b>Requirements</b>
<p>Archaeology is unlocked once you have over 1B gems, produced over 10 Oc (1E28) coins and bought the</p>
<p><b><img src="http://musicfamily.org/realm/Factions/picks/Archeology-upgrade.png" alt="Smiley face" align="middle"> Archeology Upgrade</b>.</p>
<p><b>Cost</b>: 100 Oc (1e29)</p>
<p>An "Excavation" button will then appear on the top left of the Upgrades tab and you may commence excavations.</p>
<p>The chance to find <b>Lore Artifacts</b> requires the</p>
<p><img src="http://musicfamily.org/realm/Factions/picks/SurveyEquipment.png" alt="Smiley face" align="middle"><b> Survey Equipment Upgrade</b>
<p><b>Requirements</b>: which requires 100 excavations and <b>
<p><b>Cost</b>: 1e35 (100 Dc)</b>. To be bought once throughout the entire game and does not show up as bought upgrade.
<p><b>Cost & Faction Coins</b></p>
<p><b>Excavation</b>: The first excavation costs 1 Oc (1E27) coins, and each subsequent excavation costs 20% more than the last.</p>
<p><b>Formula</b>: 1e27 ^ (0.75 ^ A) * (1 + (0.2 - 0.025 (if E290) - 0.025 (if Ancient Egg)) / 5A) ^ x where A is number of ascensions and x is number of excavations.
<p><b>Faction Coins</b>: 35% (40% with That Excavated Quickly upgrade) per excavation</p>
<p><b>Formula</b>: floor(2 * ln(1 + (5000000 * 1.15^x))^3), where x is the number of excavations you have (not including the one just purchased).</p>
<p><b>Excavation Reset</b></p>
<p><b>Cost</b>: floor(x / 3000) + 1 rubies where x is number of excavations.
<p><b>Note</b>: Free reset if enough times excavated this R (R40+ to afford reset amount)
<p><b>Formula</b>: 2000 + 50 * R + 500 * x here x is amount of resets this R.
<p><b>Note</b>: It will reset the excavation counter to zero, all previously gained Excavation rewards and Rubies will persist and you can not find them again.</p>
<p><img src="http://musicfamily.org/realm/Factions/picks/AllArtifacts.png" usemap="#AllArtifacts-map">
<map name="AllArtifacts-map">
    <area target="" research="<img src=&quot;http://musicfamily.org/realm/Factions/picks/AncientStoneSlab1.png&quot; alt=&quot;Artifacts&quot; align=&quot;middle&quot;><b> Ancient Stone Slab 1</b></p> <p><b>Clues</b>: We discovered an ancient stone slab written in old scriptures. It appears to say something about Halls of Legends.</p><p><b>Effect</b>: 1st clue required to unlock the Titan Alliance.</p> <p><b>Requirements</b>: 5th Excavation</p>" coords="6,47,62,103" shape="rect">
    <area target="" research="<img src=&quot;http://musicfamily.org/realm/Factions/picks/FossilizedPieceofBark1.png&quot; alt=&quot;Artifacts&quot; align=&quot;middle&quot;><b> Fossilized Piece of Bark 1</b></p> <p><b>Clues</b>: We discovered a fossilized piece of Bark with the image of a Faction Coin carved into it.</p><p><b>Effect</b>: 1st clue required to unlock the Druid Alliance.</p> <p><b>Requirements</b>: 10th Excavation</p>" coords="69,48,126,103" shape="rect">
    <area target="" research="<img src=&quot;http://musicfamily.org/realm/Factions/picks/BoneFragment1.png&quot; alt=&quot;Artifacts&quot; align=&quot;middle&quot;><b> Bone Fragment 1</b></p> <p><b>Clues</b>: We discovered a sundial shaped artefact, probably made of animal bones.</p><p><b>Effect</b>: 1st clue required to unlock the Faceless Alliance.</p> <p><b>Requirements</b>: 15th Excavation</p>" coords="133,48,189,103" shape="rect">
    <area target="" research="<img src=&quot;http://musicfamily.org/realm/Factions/picks/AncientStoneSlab2.png&quot; alt=&quot;Artifacts&quot; align=&quot;middle&quot;><b> Ancient Stone Slab 2</b></p> <p><b>Clues</b>: We discovered an ancient stone slab written in old scriptures.We can recognize the number 300.</p><p><b>Effect</b>: 2nd clue required to unlock the Titan Alliance.</p> <p><b>Requirements</b>: 20th Excavation</p>" coords="198,48,253,102" shape="rect">
    <area target="" research="<img src=&quot;http://musicfamily.org/realm/Factions/picks/FossilizedPieceofBark2.png&quot; alt=&quot;Artifacts&quot; align=&quot;middle&quot;><b> Fossilized Piece of Bark 2</b></p> <p><b>Clues</b>: We discovered a fossilized piece of Bark with the symbol of One Million.</p><p><b>Effect</b>: 2nd clue required to unlock the Druid Alliance.</p> <p><b>Requirements</b>: 25th Excavation</p>" coords="260,48,317,102" shape="rect">
    <area target="" research="<img src=&quot;http://musicfamily.org/realm/Factions/picks/BoneFragment2.png&quot; alt=&quot;Artifacts&quot; align=&quot;middle&quot;><b> Bone Fragment 2</b></p> <p><b>Clues</b>: We discovered an artefact shaped like the number 36, probably made of animal bones.</p><p><b>Effect</b>: 2nd clue required to unlock the Faceless Alliance.</p> <p><b>Requirements</b>: 30th Excavation</p>" coords="326,48,382,103" shape="rect">
    <area target="" research="<img src=&quot;http://musicfamily.org/realm/Factions/picks/KeytotheLostCity.png&quot; alt=&quot;Artifacts&quot; align=&quot;middle&quot;><b> Key to the Lost City</b></p> <p><b>Clues</b>: Despite being thousands of years old, it's still shiny.</p><p><b>Effect</b>: Neutral Research</p> <p><b>Requirements</b>: 1500th Excavation (total) + R23</p>" coords="389,48,446,103" shape="rect">
    <area target="" research="<img src=&quot;http://musicfamily.org/realm/Factions/picks/AncientDevice.png&quot; alt=&quot;Artifacts&quot; align=&quot;middle&quot;><b> Ancient Device</b></p> <p><b>Clues</b>: This strange Device seems to react to the Ancient Races magical capabilities. We may channel its power to increase their research potential!</p><p><b>Effect</b>: Provides 2 additional slots: 1 for each related Neutral Faction Facility you are playing.</p> <p><b>Requirements</b>: Play a Neutral Faction and have over 2,000 excavations. <p><b>Chance</b>: 0.2% per excavation (multi-buy or not) <p><b>Cost</b>: 100 QiSxg (1E200) <p><b>Alignment</b>: Neutral<p><b>Note</b>: Has no effect R100+/A2" coords="6,111,63,167" shape="rect">
    <area target="" research="<img src=&quot;http://musicfamily.org/realm/Factions/picks/EarthCore.png&quot; alt=&quot;Earth Core&quot; align=&quot;middle&quot;><b> Earth Core</b></p> <p><b>Clues</b>: This piece of rock is continuously shifting its shape, responding to mysterious enery sources.</p><p><b>Effect</b>: Part of the Prestige research quest</p> <p><b>Requirements</b>: 2750th Excavation</p>" coords="69,111,125,167" shape="rect">
    <area target="" research="<img src=&quot;http://musicfamily.org/realm/Factions/picks/HornoftheKings.png&quot; alt=&quot;Horn of the Kings&quot; align=&quot;middle&quot;><b> Horn of the Kings</b></p> <p><b>Clues</b>: It is said that when this horn is blown, the voices of past Dwarven Kings can be heard in the Wind.</p><p><b>Effect</b>: Unlocks Legacy of the Kings upgrade that adds 2 extra slots: 2 for Craftsmanship and 1 to the faction's facility you are playing</p> <p><b>Requirements</b>: have Dwarven Forges, 3250+ Excavations (as Dwarf) Chance: 0.5%</p> <p><b>Cost</b>: 10 SxSpg (1E232) and 10m Dwarven Coins <p><b>Alignment</b>: Dwarf" coords="134,111,189,167" shape="rect">
    <area target="" research="<img src=&quot;http://musicfamily.org/realm/Factions/picks/FlameofBondelnar.png&quot; alt=&quot;Flame of Bondelnar&quot; align=&quot;middle&quot;><b> Flame of Bondelnar</b></p> <p><b>Clues</b>: </p><p><b>Effect</b>: Unlocks the upgrade The Dark Light of Bondelnar that adds 2 extra slots: 2 for Warfare and 1 to the faction's facility you are playing</p> <p><b>Requirements</b>: Have Spider Sanctuaries (as Drow) Excavations: 3250+ Chance: 0.5%</p> <p><b>Cost</b>: 10 SxSpg (1E232), 10m Drow Coins <p><b>Alignment</b>: Drow" coords="198,112,253,167" shape="rect">
    <area target="" research="<img src=&quot;http://musicfamily.org/realm/Factions/picks/SpikyRoughEggArtifact.png&quot; alt=&quot;Flame of Bondelnar&quot; align=&quot;middle&quot;><b> Spiky Rough Egg</b></p> <p><b>Clues</b>: What a weird egg... it looks ages old, yet something alive is inside. Perhaps if you wait long enough, something will hatch?</p><p><b>Effect</b>: Unlocks the Hatch! Egg</p> <p><b>Requirements</b>: R46+, 1500, Excavations (Chance: 2%)</p>" coords="262,112,316,167" shape="rect">
    <area target="" research="<img src=&quot;http://musicfamily.org/realm/Factions/picks/RoughStone.png&quot; alt=&quot;Artifact&quot; align=&quot;middle&quot;><b> Rough Stone</b></p> <p><b>Description</b>: A common, totally uninteresting stone.</p><p><b>Effect</b>: Unlocks Research D290</p> <p><b>Requirement</b>: Chance: 2% On the first excavation of a run, after abdication or reincarnation.</p>" coords="6,217,62,271" shape="rect">
    <area target="" research="<img src=&quot;http://musicfamily.org/realm/Factions/picks/ScarabofFortune.png&quot; alt=&quot;Scarab of Fortune&quot; align=&quot;middle&quot;><b> Scarab of Fortune</b></p> <p><b>Description</b>: You found the rarest of relics. This golden scarab will grant you 7 days of good luck, starting from now. Make good use of it.</p> <p><b>Rewards</b>:  Awards an upgrade of the same name that increases the production of all buildings by 0.1% for each trophy you unlocked.</p> <p><b>Chance</b>: (#Ancient Pyramids)% / 1000.</p> <p><b>Cost</b>: 7 Td (7E42) <p><b>Alignment</b>: Any" coords="69,216,125,271" shape="rect">
    <area target="" research="<img src=&quot;http://musicfamily.org/realm/Factions/picks/ChocolateCookie.png&quot; alt=&quot;Chocolate Cookie&quot; align=&quot;middle&quot;><b> Chocolate Cookie</b></p> <p><b>Description</b>: Found in a wasteland made of cakes and sweets, snatched from the hands of an old woman.</p> <p><b>Chance</b>: (# excavations / 50) %</p>" coords="134,216,189,271" shape="rect">
    <area target="" research="<img src=&quot;http://musicfamily.org/realm/Factions/picks/FossilizedRodent.png&quot; alt=&quot;Fossilized Rodent&quot; align=&quot;middle&quot;><b> Fossilized Rodent</b></p> <p><b>Description</b>: What's this, a prehistoric mouse...?</p> <p><b>Rewards</b>: Awards an upgrade of the same name that increases click reward by 10% per artifact you discovered.</p> <p><b>Chance</b>: (# Treasure clicks this R / 5,000,000) %</p> <p><b>Cost</b>: 100 Qid (1E50) <p><b>Alignment</b>: Any" coords="198,216,253,271" shape="rect">
    <area target="" research="<img src=&quot;http://musicfamily.org/realm/Factions/picks/PowerOrb.png&quot; alt=&quot;Power Orb&quot; align=&quot;middle&quot;><b> Power Orb</b></p> <p><b>Description</b>: Throbbing with Arcane Power</p> <p><b>Rewards</b>: Increases mana regeneration by 2.5%.</p> <p><b>Requirement</b>: +3000 max mana</p> <p><b>Chance</b>: (max mana / 15,000) %</p> <p><b>Cost</b>: 1 QaVg (1E75) <p><b>Alignment</b>: Any" coords="262,216,316,271" shape="rect">
    <area target="" research="<img src=&quot;http://musicfamily.org/realm/Factions/picks/PinkCarrot.png&quot; alt=&quot;Smiley face&quot; align=&quot;middle&quot;><b> Pink Carrot</b></p> <p><b>Description</b>: The main product of properly nurtured Farms.</p> <p><b>Requirement</b>: Play as Fairy (Not Dwarf)</p> <p><b>Chance</b>: (# Farms / 5,000) %</p>" coords="324,216,382,272" shape="rect">
    <area target="" research="<img src=&quot;http://musicfamily.org/realm/Factions/picks/BottledVoice.png&quot; alt=&quot;Smiley face&quot; align=&quot;middle&quot;><b> Bottled Voice</b></p> <p><b>Description</b>: The essence of a melodic Fairy voice.</p> <p><b>Requirement</b>: Play as Fairy (Not Dwarf)</p> <p><b>Chance</b>: (Fairy Chanting casts this game / 40,000) %</p>" coords="389,216,446,271" shape="rect">
    <area target="" research="<img src=&quot;http://musicfamily.org/realm/Factions/picks/LuckyClover.png&quot; alt=&quot;Smiley face&quot; align=&quot;middle&quot;><b> Lucky Clover</b></p> <p><b>Description</b>: A perfectly shaped four leaf clover. Each leaf is almost unnaturally identical to the other three.</p> <p><b>Requirement</b>: Play as Elven (Not Dwarf)</p> <p><b>Chance</b>: (Highest # of consecutive Elven Luck-1) * 50)%</p>" coords="4,280,62,334" shape="rect">
    <area target="" research="<img src=&quot;http://musicfamily.org/realm/Factions/picks/Mini-treasure.png&quot; alt=&quot;Smiley face&quot; align=&quot;middle&quot;><b> Mini-treasure</b></p> <p><b>Description</b>: It's a small perfect replica of our gold-filled treasure.</p> <p><b>Requirement</b>: Play as Elven (Not Dwarf)</p> <p><b>Chance</b>: (# Clicks this game / 3,000,000)%</p>" coords="69,278,126,336" shape="rect">
    <area target="" research="<img src=&quot;http://musicfamily.org/realm/Factions/picks/Pillarfragment.png&quot; alt=&quot;Smiley face&quot; align=&quot;middle&quot;><b> Pillar Fragment</b></p> <p><b>Description</b>: A tiny piece of the legendary pillars which sustain all the Heavens.</p> <p><b>Requirement</b>: Play as Angel (Not Dwarf)</p> <p><b>Chance</b>: (# Heaven's Gate / 3,750) %</p>" coords="135,279,189,335" shape="rect">
    <area target="" research="<img src=&quot;http://musicfamily.org/realm/Factions/picks/DivineSword.png&quot; alt=&quot;Smiley face&quot; align=&quot;middle&quot;><b> Divine Sword</b></p> <p><b>Description</b>: The shining golden sword of an Archangel. Its hilt feels pleasantly warm to the pure of heart and burning hot for the villain.</p> <p><b>Requirement</b>: Play as Angel (Not Dwarf)+3 consecutive Angels runs (This R). Even just buying the Angels Trade Treaty counts towards this artifact.</p> <p><b>Chance</b>: (Consecutive times allied with Angels this R / 60) %</p>" coords="198,280,253,336" shape="rect">
    <area target="" research="<img src=&quot;http://musicfamily.org/realm/Factions/picks/AncientCoinPiece.png&quot; alt=&quot;Artifacts&quot; align=&quot;middle&quot;><b> Ancient Coin Piece</b></p> <p><b>Description</b>: A common goblin lucky charm. The older it is, the luckier you are, or so they say.</p> <p><b>Requirement</b>: Play as Goblin (Not Drow)</p> <p><b>Chance</b>: (#Faction Coins this R# / 50'000'000) %</p>" coords="262,281,316,335" shape="rect">
    <area target="" research="<img src=&quot;http://musicfamily.org/realm/Factions/picks/GoblinPurse.png&quot; alt=&quot;Artifacts&quot; align=&quot;middle&quot;><b> Goblin Purse</b></p> <p><b>Description</b>: Heavy and roomy. Definitely too big for just pocket change.</p> <p><b>Requirement</b>: Play as Goblin (Not Drow)</p> <p><b>Chance</b>: (Tax collection casts this game / 300'000) %</p>" coords="326,280,380,334" shape="rect">
    <area target="" research="<img src=&quot;http://musicfamily.org/realm/Factions/picks/RottenOrgan.png&quot; alt=&quot;Artifacts&quot; align=&quot;middle&quot;><b> Rotten Organ</b></p> <p><b>Description</b>: Ew... disgusting. It still pulses.</p> <p><b>Requirement</b>: Play as Undead (Not Drow)</p> <p><b>Chance</b>: (# Assistants / 500) %</p>" coords="391,281,449,334" shape="rect">
    <area target="" research="<img src=&quot;http://musicfamily.org/realm/Factions/picks/JawBone.png&quot; alt=&quot;Artifacts&quot; align=&quot;middle&quot;><b> Jaw Bone</b></p> <p><b>Description</b>: A jaw, missing more than half of its teeth.</p> <p><b>Requirement</b>: Play as Undead (Not Drow) +24h offline (This R)</p> <p><b>Chance</b>: (Offline playtime this R / 10d)%</p>" coords="5,342,62,399" shape="rect">
    <area target="" research="<img src=&quot;http://musicfamily.org/realm/Factions/picks/DemonicFigurine.png&quot; alt=&quot;Artifacts&quot; align=&quot;middle&quot;><b> Demonic Figurine</b></p> <p><b>Description</b>: An intricate figurine representing the evil face of a lesser demon.</p> <p><b>Requirement</b>: Play as Demon (Not Drow) 666 Trophies unlocked.</p> <p><b>Chance</b>: 1%</p>" coords="69,344,125,399" shape="rect">
    <area target="" research="<img src=&quot;http://musicfamily.org/realm/Factions/picks/DemonHorn.png&quot; alt=&quot;Artifacts&quot; align=&quot;middle&quot;><b> Demon Horn</b></p> <p><b>Description</b>: Still blazing with the flames of Hell. Handle with care.</p> <p><b>Requirement</b>: Play as Demon (Not Drow) +3 consecutive Demon runs (This R). Even just buying the Demons Trade Treaty counts towards this artifact.</p> <p><b>Chance</b>: (Consecutive times allied with Demon this R / 60)%</p>" coords="134,343,189,399" shape="rect">
    <area target="" research="<img src=&quot;http://musicfamily.org/realm/Factions/picks/HugeTitanStatue.png&quot; alt=&quot;Artifacts&quot; align=&quot;middle&quot;><b> Huge Titan Statue</b></p> <p><b>Description</b>: The granite representation of a giant wielding a lightning bolt in its fist. A foot appears to be missing.</p> <p><b>Requirement</b>: Play as Titan (Not Dragon)</p> <p><b>Chance</b>: (Lightning Strike Casts this game / 1000)%</p>" coords="197,342,253,399" shape="rect">
    <area target="" research="<img src=&quot;http://musicfamily.org/realm/Factions/picks/TitanShield.png&quot; alt=&quot;Artifacts&quot; align=&quot;middle&quot;><b> Titan Shield</b></p> <p><b>Description</b>: A gargantuan metal shield, twice as tall as a common human.</p> <p><b>Requirement</b>: Play as Titan (Not Dragon) +10h playtime (This game)</p> <p><b>Chance</b>: (Playtime this game / 50h)%</p>" coords="262,342,317,398" shape="rect">
    <area target="" research="<img src=&quot;http://musicfamily.org/realm/Factions/picks/GlyphTable.png&quot; alt=&quot;Artifacts&quot; align=&quot;middle&quot;><b> Glyph Table</b></p> <p><b>Description</b>: Contains all the secrets of the Druidic Alphabet.</p> <p><b>Requirement</b>: Play as Druid (Not Dragon) +Same amount of each Neutral building.</p> <p><b>Chance</b>: 2%</p>" coords="325,343,380,398" shape="rect">
    <area target="" research="<img src=&quot;http://musicfamily.org/realm/Factions/picks/StoneOfBalance.png&quot; alt=&quot;Artifacts&quot; align=&quot;middle&quot;><b> Stone of Balance</b></p> <p><b>Description</b>: A carved stone hovering above its pedestal.</p> <p><b>Requirement</b>: Play as Druid (Not Dragon)</p> <p><b>Chance</b>: (Grand Balance Casts this game / 30,000)%</p>" coords="389,342,445,398" shape="rect">
    <area target="" research="<img src=&quot;http://musicfamily.org/realm/Factions/picks/TranslucentGoo.png&quot; alt=&quot;Artifacts&quot; align=&quot;middle&quot;><b> Translucent Goo</b></p> <p><b>Description</b>: A completely odorless sticky substance with a diaphanous, unsettling glow.</p> <p><b>Requirement</b>: Play as Faceless (Not Dragon)</p> <p><b>Chance</b>: (Brainwave casts this game / 400)%</p>" coords="5,407,62,462" shape="rect">
    <area target="" research="<img src=&quot;http://musicfamily.org/realm/Factions/picks/Octopus-shapedHelmet.png&quot; alt=&quot;Artifacts&quot; align=&quot;middle&quot;><b> Octopus-shaped Helmet</b></p> <p><b>Description</b>: A large helmet with empty metal prongs to accomodate tentacular appendages.</p> <p><b>Requirement</b>: Play as Faceless (Not Dragon)</p> <p><b>Chance</b>: (# Labyrinths / 2000)%</p>" coords="69,406,126,463" shape="rect">
    <area target="" research="<img src=&quot;http://musicfamily.org/realm/Factions/picks/DwarvenBow.png&quot; alt=&quot;Artifacts&quot; align=&quot;middle&quot;><b> Dwarven Bow</b></p> <p><b>Description</b>: Actually a heavy throwing hammer.</p> <p><b>Requirement</b>: Play as Dwarves</p> <p><b>Chance</b>: (# clicks this game / 25,000)%</p>" coords="133,407,189,462" shape="rect">
    <area target="" research="<img src=&quot;http://musicfamily.org/realm/Factions/picks/StoneTankard.png&quot; alt=&quot;Artifacts&quot; align=&quot;middle&quot;><b> Stone Tankard</b></p> <p><b>Description</b>: A very heavy mug for drinking the heaviest beers.</p> <p><b>Requirement</b>: Play as Dwarves</p> <p><b>Chance</b>: (# Inns / 25,000)%</p>" coords="198,405,254,462" shape="rect">
    <area target="" research="<img src=&quot;http://musicfamily.org/realm/Factions/picks/CeremonialDagger.png&quot; alt=&quot;Artifacts&quot; align=&quot;middle&quot;><b> Ceremonial Dagger</b></p> <p><b>Description</b>: Its blade is unnaturally keen and sharp.</p> <p><b>Requirement</b>: Play as Drow +0 Treasure clicks (This includes automatic clicke)(This Game)</p> <p><b>Chance</b>: 2%</p>" coords="262,408,317,462" shape="rect">
    <area target="" research="<img src=&quot;http://musicfamily.org/realm/Factions/picks/ArachnidFigurine.png&quot; alt=&quot;Arachnid Figurine&quot; align=&quot;middle&quot;><b> Arachnid Figurine</b></p> <p><b>Description</b>: If you are afraid of spiders, Drow aren't your faction.</p> <p><b>Requirement</b>: Play as Drow +24h Evil Playtime (All-time)</p> <p><b>Chance</b>: (All-time Evil playtime / 50d)%</p>" coords="325,406,382,463" shape="rect">
    <area target="" research="<img src=&quot;http://musicfamily.org/realm/Factions/picks/SteelPlate.png&quot; alt=&quot;Steel Plate&quot; align=&quot;middle&quot;><b> Steel Plate</b></p> <p><b>Description</b>: A full plate made of hardened steel.</p> <p><b>Requirement</b>: Play as Mercenaries +R5</p> <p><b>Chance</b>: (#R / 50)%</p>" coords="389,405,445,461" shape="rect">
    <area target="" research="<img src=&quot;http://musicfamily.org/realm/Factions/picks/BlackSword.png&quot; alt=&quot;Black Sword&quot; align=&quot;middle&quot;><b> Black Sword</b></p> <p><b>Description</b>: A long sword with an extremely sharp blade made of dark metal.</p> <p><b>Requirement</b>: Play as Mercenaries +100 Merc affiliations (All-time)</p> <p><b>Chance</b>: (All-time Mercenary playtime / 16h 40m)%</p>" coords="6,470,63,525" shape="rect">
    <area target="" research="<img src=&quot;http://musicfamily.org/realm/Factions/picks/DragonFangArtifact.png&quot; alt=&quot;Dragon Fang&quot; align=&quot;middle&quot;><b> Dragon Fang</b></p> <p><b>Description</b>: This huge fang can barely fit in the hands of a Titan.</p> <p><b>Requirement</b>: R50+, play as Dragons <p><b>Chance</b>: Excavate (# Iron Strongholds / 400,000)%</p> <p><b>Alignment</b>: Neutral faction, Dragons" coords="69,469,125,525" shape="rect">
    <area target="" research="<img src=&quot;http://musicfamily.org/realm/Factions/picks/DragonSoulArtifact.png&quot; alt=&quot;Dragon Soul&quot; align=&quot;middle&quot;><b> Dragon Soul</b></p> <p><b>Description</b>: The extracted soul from an ancient dragon, wields the power to end the world in an instant. Also makes a good soup ingredient.</p> <p><b>Requirement</b>: R50+, play as Dragons, have 5 different Dragon Breath effects active simultaneously.</p> <p><b>Chance</b>: Excavate (# Dragon Breath casts this game / 200,000)% <p><b>Alignment</b>: Neutral faction, Dragons" coords="134,469,189,525" shape="rect">
    <area target="" research="<img src=&quot;http://musicfamily.org/realm/Factions/picks/VanillaFlavorJuice.png&quot; alt=&quot;Smiley face&quot; align=&quot;middle&quot;><b> Vanilla Flavor Juice</b></p> <p><b>Description</b>: An essence from extremely savory vanilla beans.</p> <p><b>Rewards</b>: Increase the production of all buildings by 25,000% for the first 15 minutes of the game (this game) for all Vanilla factions. Doesn't work while offline.</p> <p><b>Note</b>: Effect is canceled if you Prestige.</p> <p><b>Requirement</b>: +R16</p> <p><b>Chance</b>: 20% in the first 5m of a game</p> <p><b>Cost</b>: 1 coin <p><b>Alignment</b>: Vanilla faction" coords="198,469,254,525" shape="rect">
    <area target="" research="<img src=&quot;http://musicfamily.org/realm/Factions/picks/ObsidianShardArtifact.png&quot; alt=&quot;Obsidian Shard&quot; align=&quot;middle&quot;><b> Obsidian Shard</b><p><b>Description</b>: Extremely hard and black as darkness itself, this material cannot apparently be carved or melted. It is a mystery how you can make this thing into a sword.<p><b>Effect</b>: Unlocks Secrets of the Warriors <p>Requirement: 8000 Excavations any Faction, R75+" coords="325,111,380,165" shape="rect">
    <area target="" research="<img src=&quot;http://musicfamily.org/realm/Factions/picks/AncientCocoaBeanArtifacts.png&quot; align=&quot;middle&quot;><b> Ancient Cocoa Bean</b><p>Discription: Despite being centuries old, it still smells like top-quality cocoa.<p>Requirement: Neutral, R22+, Must be Neutral Faction to buy upgrade<p>Effect: Gives an upgrade named Chocolate Flavored Juice<P>Upgrade Effect: Increase the production of all buildings by 5.68% for the first 15 minutes of the game for all Neutral factions. Does not work while offline.<p>Chance: 10%" coords="260,470,318,527" shape="rect">
    <area target="" research="<img src=&quot;http://musicfamily.org/realm/Factions/picks/KnowYourEnemyPartI.png&quot; align=&quot;middle&quot;><b> Know Your Enemy, Part I</b></p> <p><b>Description</b>: All the knowledge you need, stored in a handy book.</p> <p><b>Rewards</b>: Awards an upgrade of the same name that increases the production of all buildings based on time spent as Non-Mercenary. (&amp;quot;Time allied with...&amp;quot; in the stats) <p><b>Formula</b>: (0.5 * x^0.75)%, where x is amount of time spent as non-mercenary factions (in seconds). <p><b>Requirement</b>: Play as Mercenaries, have upgrades from each 11 factions. +R12</p> <p><b>Chance</b>: 10%</p> <p><b>Cost</b>: 100 Vg (1E65) <p><b>Alignment</b>: Mercenary" coords="327,470,382,528" shape="rect">
    <area target="" research="<img src=&quot;http://musicfamily.org/realm/Factions/picks/VoodooDoll.png&quot; align=&quot;middle&quot;><b> Voodoo Doll</b></p> <p><b>Description</b>: You are now CURSED! And you feel a sting in your lower rear.</p> <p><b>Rewards</b>: Increase the production of all building by 0.1% for each trophy you have unlocked</p> <p><b>Requirement</b>: Play as Evil (Only required to get Witch Conclaves)</p> <p><b>Cost</b>: 20 Qig (2E154) <p><b>Chance</b>: (number of Witch Conclaves / 10000)%</p> <p><b>Alignment</b>: Any" coords="391,470,447,526" shape="rect">
    <area target="" research="<img src=&quot;http://musicfamily.org/realm/Factions/picks/WallFragment.png&quot; align=&quot;middle&quot;><b> Wall Fragment</b></p> <p><b>Description</b>: A fragment of an utterly and completely unbreakable wall. Enjoy your paradox.</p> <p><b>Rewards</b>: Increase the production of all buildings based on their tier.</p> <p><b>Formula</b>: (2.5*x^2), where x is the building tier, starting at 1 for Halls of Legends and increasing to 11 for Farms. <p><b>Requirement</b>: At least 1 Ascension <p><b>Chance</b>: 10%</p> <p><b>Cost</b>: 1 M (1E6) <p><b>Alignment</b>: Any" coords="5,534,60,590" shape="rect">
    <area target="" research="<img src=&quot;http://musicfamily.org/realm/Factions/picks/FortuntTellerMachineArtifact.png&quot; align=&quot;middle&quot;><b> Fortune Teller Machine</b></p><p><b>Requirement</b>: Excavate (Chance 0.1%)</p> <p><b>Alignment</b>: Any (No Faction) <p><b>Description</b>: Will tell you 1 of 24 statements at random.<p>Upgrade Requirement: R42+<p>Cost: R42+ 1 No (1e32)<p>Cost: Post A2 Free<p>Effect: Increase the production of Non-Unique buildings bassed on total time spent. (Time in seconds this R)<p>Formula: 6.5 * x ^ 0.65, where x is time this R</p>" coords="69,534,127,592" shape="rect">
    <area target="" research="<img src=&quot;http://musicfamily.org/realm/Factions/picks/DawnstoneArtifact.png&quot; align=&quot;middle&quot;><b> Dawnstone</b></p><p><b>Description</b>: Only found during sunrise hours. Emits a faint glow.</p> <p><b>Rewards</b>: With Both the Duskstone and Dawnstone artifacts, awards the Sun Force upgrade, which grants different effects based on time of the day.</p> <p><b>Requirement</b>: Excavate between 5:00am and 8:00am (Your local time)<p><b>Chance</b>: (Excavation count / 10,000)%</p><p>Click image for details" href="http://musicfamily.org/realm/SunForce/" coords="134,535,189,592" shape="rect">
    <area target="" research="<img src=&quot;http://musicfamily.org/realm/Factions/picks/DuskstoneArtifact.png&quot; align=&quot;middle&quot;><b> Duskstone</b></p><p><b>Description</b>: Only found during sunset hours. Absorbs light in a small radius.</p> <p><b>Rewards</b>: With Both the Dawnstone and Duskstone artifacts, awards the Sun Force upgrade, which grants different effects based on time of the day.</p> <p><b>Requirement</b>: Excavate between 6:00pm and 9:00pm (Your local time)<p><b>Chance</b>: (Excavation count / 10,000)%</p><p>Click image for details" href="http://musicfamily.org/realm/SunForce/" coords="196,534,254,590" shape="rect">
    <area target="" research="<img src=&quot;http://musicfamily.org/realm/Factions/picks/AncientHeirloomTrophy.png&quot; align=&quot;middle&quot;><b> Ancient Heirloom</b></p><p><b>Requirements</b>: Have at least 1 Lineage level purchased. <p><b>Chance</b>: (Total Lineage levels/20)% <p><b>Effect</b>: Reduces the cost multiplier of Lineage by 10%, (Except for the highest one) (Instead of 10x more per level it is  9x more per level) <p><b>Formula</b>: Without Ancient Heirloom 25 * 10^(15+lineages) <p>Formula: With Ancient Heirloom (25 * 10^(15+lineages))^0.9<p><b>Cost</b>: 10 Dtg (1e100)" coords="262,535,320,590" shape="rect">
    <area target="" research="<img src=&quot;http://musicfamily.org/realm/Factions/picks/KnowYourEnemyPart2.png&quot; align=&quot;middle&quot;><b> Know Your Enemy, Part 2</b></p><p><b>Description</b>: Much more knowledge than you need, stored in a handy book.<p><b>Reward</b>: Awards an upgrade of the same name that Increase the production of all buildings based on time spent as Non-Mercenaries.<p><b>Note</b>: Only available to Mercenaries<p><b>Formula</b>: 0.065 * x^0.65 where x is amount of time spent as non-mercenary factions (in seconds).<p><b>Requirement</b>: R76, Upgrade from all 12 Factions<p><b>Secret Upgrade Cost</b>: 100 Noqag (1e152)" coords="324,534,382,590" shape="rect">
    <area target="" research="<img src=&quot;http://musicfamily.org/realm/Factions/picks/VeteranFigurineArtifact.png&quot; align=&quot;middle&quot;><b> Veteran Figurine</b></p><p><b>Discription</b>: The warrior of a thousand battles, ultimate champion of the Realms.<p><b>Requirement</b>: R90+<p>Chance: (x/1,000,000)%, where x is seconds this game.<p><b>Effect</b>: Passive effect: allows Mercenaries to benefit from all challenges." coords="391,536,447,590" shape="rect">
    <area target="" research="<img src=&quot;http://musicfamily.org/realm/Factions/picks/WallChunckArtifact.png&quot; align=&quot;middle&quot;><b> Wall Chunk</b></p><p><b>Discription</b>: A bigger piece of the infamous Ascension Wall.<p><b>Requirement</b>: R100+ <p><b>Chance</b>: 10%</p> <p><b>Effect</b>: Increase the production of all buildings based on their tier<p><b>Cost</b>: 1 Sx (1e21)<p><b>Formula</b>: 30000 * (11-x) ^ 3.5, where x is building tier." coords="4,597,62,655" shape="rect">
    <area target="" research="<img src=&quot;http://musicfamily.org/realm/Factions/picks/ExcavatedMirageArtifact.png&quot; align=&quot;middle&quot;><b> Excavated Mirage</b></p><p><b>Discription</b>: You know all too well this does not exist, yet it fills you with hope and optimism.<p><b>Requirement </b>: Ascension 2<p><b>Effect</b>: Increase Faction Coin find chance by a multiplicative 1000%<p><b>Cost</b>: 1 Sx (1e21)<p>Formula: (log(x) / 100)% where x is FC chance" coords="69,596,125,653" shape="rect">
    <area target="" research="<img src=&quot;http://musicfamily.org/realm/Factions/picks/AncestralHourglassArtifact.png&quot; align=&quot;middle&quot;><b> Ancestral Hourglass</b></p><p>Description: The silver sands contained within seem to never stop flowing.<p>Requirement:  R100+<p>Upgrade Cost: (1e90)<p>Effect: Lower cost of Lineage level based on time spent this game. FC cost is reset when you purchase a new lineage level.<p>Formula: (floor(x ^ (1 - 0.01 * ((y ^ 1.1) - z / 5))) / 10), where x is hours this game (reset when upgrading lineage), y is lineage level and z is reincarnations.<p>Lineage Cost Formula: (25 * 10 ^ (15 + level - hourglass.formula)) ^ 0.9 (if ancient heirloom).<p>Chance: (x / 10000000000000000 (10 QA))%, where x is FC chance." coords="131,595,189,653" shape="rect">
    <area target="" research="<img src=&quot;http://musicfamily.org/realm/Factions/picks/SilkClothArtifact.png&quot; align=&quot;middle&quot;><b> Silk Cloth</b></p><p>Description: The purest silk made for Fairies, by Fairies, of Fairies.<p>Requirement:  R100+, 3000+ Excavations<p>Effect: Unlocks Fairy Set.<p>Note: You need all 3 faction artifacts to unlock set.<p>Chance: ((x - 10000) / 200000)%, where x is Wizard Towers built (Building count multipliers do NOT count)." coords="197,596,253,652" shape="rect">
    <area target="" research="<img src=&quot;http://musicfamily.org/realm/Factions/picks/RawEmeraldArtifact.png&quot; align=&quot;middle&quot;><b> Raw Emerald</b></p><p>Description: Just slightly less precious than a raw Ruby.<p>Requirement:  R100+, 3000+ Excavations<p>Effect: Unlocks Elven Set.<p>Note: You need all 3 faction artifacts to unlock set.<p>Chance: ((2 * x ^ 4.5) / 10000)%, where x is non-ruby excavation resets (this game)." coords="262,597,319,652" shape="rect">
    <area target="" research="<img src=&quot;http://musicfamily.org/realm/Factions/picks/FossilizedWingArtifact.png&quot; align=&quot;middle&quot;><b> Fossilized Wing</b></p><p>Description: The remains of an Angel fallen to earth.<p>Requirement:  R100+, 3000+ Excavations<p>Effect: Unlocks Angel Set.<p>Note: You need all 3 faction artifacts to unlock set.<p>Chance: (x / 25920000 (300 days))%, where x is angel time (all time) in seconds." coords="325,595,383,652" shape="rect">
    <area target="" research="<img src=&quot;http://musicfamily.org/realm/Factions/picks/SpikedWhipArtifact.png&quot; align=&quot;middle&quot;><b> Spiked Whip</b></p><p>Description: Use with caution. You do not want to exterminate all your slaves.<p>Requirement:  R100+, 3000+ Excavations<p>Effect: Unlocks Goblin Set.<p>Note: You need all 3 faction artifacts to unlock set.<p>Chance: ((x - 10000) / 300000)%, where x is Slave Pens (Building count multipliers do NOT count)." coords="391,597,445,652" shape="rect">
    <area target="" research="<img src=&quot;http://musicfamily.org/realm/Factions/picks/DustyCoffinArtifact.png&quot; align=&quot;middle&quot;><b> DustyCoffin</b></p><p>Description: Sealed since forever, yet you can hear a strange noise from within.<p>Requirement:  R100+, 3000+ Excavations<p>Effect: Unlocks Undead Set.<p>Note: You need all 3 faction artifacts to unlock set.<p>Chance: ((1 / (30 + x ^ 1.5))%, where x is time this game in seconds." coords="3,659,61,716" shape="rect">
    <area target="" research="<img src=&quot;http://musicfamily.org/realm/Factions/picks/CrystallizedLavaArtifact.png&quot; align=&quot;middle&quot;><b> CrystallizedLava</b></p><p>Description: Incandescent but still. Can be used efficiently as a desk lamp.<p>Requirement:  R100+, 3000+ Excavations<p>Effect: Unlocks Demon Set.<p>Note: You need all 3 faction artifacts to unlock set.<p>Chance: ((x - 10000) / 200000)%, where x is Hall of Legends (Building count multipliers do NOT count)." coords="67,660,127,717" shape="rect">
    <area target="" research="<img src=&quot;http://musicfamily.org/realm/Factions/picks/TitanHelmetArtifact.png&quot; align=&quot;middle&quot;><b> Titan Helmet</b></p><p>Description: Made of enough metal to craft a human-sized full plate.<p>Requirement:  R100+, 3000+ Excavations<p>Effect: Unlocks Titan Set.<p>Note: You need all 3 faction artifacts to unlock set.<p>Chance: ((x ^ 2) / 5000000000 (5B))%, where x is Royal Exchanges (Royal Exchange count multipliers DO count)." coords="133,660,190,714" shape="rect">
    <area target="" research="<img src=&quot;http://musicfamily.org/realm/Factions/picks/BranchoftheLifeTreeArtifact.png&quot; align=&quot;middle&quot;><b> Branch of the Life Tree</b><p>Description: Despite being torn from its source tree, it keeps growing buds and leaves.<p>Requirement: R100+, 3000+ Excavations<p>Effect: Unlocks Druid Set.<p>Note: You need all 3 faction artifacts to unlock set.<p>Chance:  ((x ^ 3) / 2000000 (2M))%, where x is level of druid lineage." coords="195,660,253,717" shape="rect">
    <area target="" research="<img src=&quot;http://musicfamily.org/realm/Factions/picks/NightmareFigmentArtifact.png&quot; align=&quot;middle&quot;><b> Nightmare Figment</b><p>Description: An unshaped, ephemeral substance which is politely trying to corrupt your mind.<p>Requirement:  R100+, 3000+ Excavations<p>Effect: Unlocks Faceless Set.<p>Note: You need all 3 faction artifacts to unlock set.<p>Chance: ((x ^ 1.5) / 20000000 (20M))%, where x is headstart time in seconds." coords="262,659,319,716" shape="rect">
</map>
<h6>Artifact Sets</h6>
<p><b>Finding all the faction artifacts for a specific faction</b> will also unlock a new selection of upgrades called "Artifact Sets". You will be able to pick one per game only, similar to Bloodlines and Lineages. Abdicating will reset your choice and allow to pick another.
<p><b>Requires all artifacts related to the faction to use its set.</b>
<h6><center><img src="http://musicfamily.org/realm/Factions/picks/FactionSets.png" usemap="#FactionSets-map"></h6>
<map name="FactionSets-map">
    <area target="" research="<img src=&quot;http://musicfamily.org/realm/Factions/picks/FairySet.png&quot; align=&quot;middle&quot;><b> Fairy Set</b></p><p>Requirement: A2+<p>Artifacts Required: Silk Cloth, Pink Carrot, Bottled Voice<p>Cost: Free<p>Effect: Increase Farm, Inn and Blacksmith production based on number of assistants owned.<p>Formula: (0.75 * x ^ 0.75), where x is number of assistants owned." coords="6,7,54,56" shape="rect">
    <area target="" research="<img src=&quot;http://musicfamily.org/realm/Factions/picks/ElvenSet.png&quot; align=&quot;middle&quot;><b> Elven Set</b></p><p>Requirement: A2+<p>Artifacts Required: Raw Emerald, Lucky Clover, Mini-treasure<p>Cost: Free<p>Effect: Increase all building production based on total amount of Elven Lucks triggered (This R)(since unlock).<p>Formula: (0.66 * x ^ 0.6), where x is amount of Elven Lucks triggered."  coords="59,7,110,57" shape="rect">
    <area target="" research="<img src=&quot;http://musicfamily.org/realm/Factions/picks/AngelSet.png&quot; align=&quot;middle&quot;><b> Angel Set</b></p><p>Requirement: A2+<p>Artifacts Required: Fossilized Wing, Pillar Fragment, DivineSword<p>Cost: Free<p>Effect: Increase mana regen based on spells cast this game.<p>Formula: (0.32 * x ^ 0.32), where x is spells cast." coords="113,7,163,55" shape="rect">
    <area target="" research="<img src=&quot;http://musicfamily.org/realm/Factions/picks/GoblinSet.png&quot; align=&quot;middle&quot;><b> Goblin Set</b></p><p>Requirement: A2+<p>Artifacts Required: Spiked Whip, Ancient Coin Piece, Goblin Purse<p>Cost: Free<p>Effect: Multiplicatively increase gathered faction coins based on time spent this game if they don't match faction or bloodline.<p>Formula: (1 + (0.01 * x ^ 0.7)), where x is seconds.<p>Note: Ingame tooltip is off by one (actual effect is 1 higher)" coords="6,61,54,108" shape="rect">
    <area target="" research="<img src=&quot;http://musicfamily.org/realm/Factions/picks/UndeadSet.png&quot; align=&quot;middle&quot;><b> Undead Set</b></p><p>Requirement: A2+<p>Artifacts Required: Dusty Coffin, Rotten Organ, JawBone<p>Cost: Free<p>Effect: Additively Increase max mana based on offline bonus.<p>Formula: (35 * log(1 + x) ^ 3.25), where x is offline Multiplier." coords="60,61,109,109" shape="rect">
    <area target="" research="<img src=&quot;http://musicfamily.org/realm/Factions/picks/DemonSet.png&quot; align=&quot;middle&quot;><b> Demon Set</b></p><p>Requirement: A2+<p>Artifacts Required: Crystallized Lava, Demonic Figurine, Demon Horn<p>Cost: Free<p>Effect: Increase non unique building production based on the sum of your faction spells activity time. (This R)<p>Formula: (0.75 * x ^ 0.75), where x is faction spell activity time." coords="113,59,164,109" shape="rect">
    <area target="" research="<img src=&quot;http://musicfamily.org/realm/Factions/picks/TitanSet.png&quot; align=&quot;middle&quot;><b> Titan Set</b></p><p>Requirement: A2+<p>Artifacts Required: Titan Helmet, Huge Titan Statue, Titan Shield<p>Cost: Free<p>Effect: Increase Unique building production based on time spent this game.<p>Formula: (0.07 * x ^ 0.7), where x is seconds."coords="6,114,54,163" shape="rect">
    <area target="" research="<img src=&quot;http://musicfamily.org/realm/Factions/picks/DruidSet.png&quot; align=&quot;middle&quot;><b> Druid Set</b></p><p>Requirement: A2+<p>Artifacts Required: Branch of the Life Tree, Glyph Table, Stone Of Balance<p>Cost: Free<p>Effect: Increase production of all buildings based on their quantity.<p>Formula: (0.65 * x ^ 0.65), where x is building count." coords="60,113,110,164" shape="rect">
    <area target="" research="<img src=&quot;http://musicfamily.org/realm/Factions/picks/FacelessSet.png&quot; align=&quot;middle&quot;><b> Faceless Set</b></p><p>Requirement: A2+<p>Artifacts Required: Nightmare Figment, Translucent Goo, Octopus-shaped Helmet<p>Cost: Free<p>Effect: Increase production of all buildings based on highest amount of spells cast in a single game.<p>Formula: (0.32 * x ^ 0.32), where x is number of spells cast." coords="114,114,163,164" shape="rect">
</map>
<?php include "../scripts/footer.html"; ?>
