<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en">
<head>
<?php include "../scripts/header.html"; ?>
<h6><img src="http://musicfamily.org/realm/Factions/picks/ExcavationTopPage.png"></h6>
<p><b>There are two kinds of artifacts</b></p>
<p><a href="/realm/QuestArtifacts" title="Quest Artifacts"><b>Quest Artifacts</b></a> and
<a href="/realm/LoreArtifacts" title="Lore Artifacts"><b>Lore Artifacts</b></a></p>
<p><b><font color="red">Artifact Sets at bottom</font></b></p>
<p><b>In-game description</b>
<p>Enter the Archeology Association to control the progress of your Excavations. There you will be able to fund more excavations to find Faction Coins, the rare Rubies and ancient Artifacts from the civilizations of the old.</p>
<p>Archaeology was first implemented in the "Ancient Races" expansion for introducing the Neutral Factions.</p>
<p>Excavating enables to find Rubies (See the <b><a target="_blank" href="http://musicfamily.org/realm/Rubies/">Ruby</a></b> page), with luck: Faction Coins, and at certain thresholds or under certain conditions: Artifacts. Specific artifacts are required to unlock the Neutral & Prestige Factions.</p>
<p>Some artifacts will reward direct bonuses and the amount of discovered artifacts take part in some Research upgrades.</p>
<p><b>Requirements</b>
<p>Archaeology is unlocked once you have over 1B gems, produced over 10 Oc (1E28) coins and bought the</p>
<p><b><img src="http://musicfamily.org/realm/Factions/picks/Archeology-upgrade.png" alt="Smiley face" align="middle"> Archeology Upgrade</b>.</p>
<p><b>Cost</b>: 100 Oc (1e29)</p>
<p>An "Excavation" button will then appear on the top left of the Upgrades tab and you may commence excavations.</p>
<p>The chance to find <b>Lore Artifacts</b> requires the</p>
<p><img src="http://musicfamily.org/realm/Factions/picks/SurveyEquipment.png" alt="Smiley face" align="middle"><b> Survey Equipment Upgrade</b>
<p><b>Requirements</b>: which requires 100 excavations and <b>
<p><b>Cost</b>: 1e35 (100 Dc)</b>. To be bought once throughout the entire game and does not show up as bought upgrade.
<p><b>Cost & Faction Coins</b></p>
<p><b>Excavation</b>: The first excavation costs 1 Oc (1E27) coins, and each subsequent excavation costs 20% more than the last.</p>
<p><b>Formula</b>: 1e27 ^ (0.75 ^ A) * (1 + (0.2 - 0.025 (if E290) - 0.025 (if Ancient Egg)) / 5A) ^ x where A is number of ascensions and x is number of excavations.
<p><b>Faction Coins</b>: 35% (40% with That Excavated Quickly upgrade) per excavation</p>
<p><b>Formula</b>: 1500 + 0.05 * x ^ 2.75, where x is the number of excavations you have (not including the one just purchased).</p>
<p><b>Excavation Reset</b></p>
<p><b>Cost</b>: floor(x / 3000) + 1 rubies where x is number of excavations.
<p><b>Note</b>: Free reset if enough times excavated this R (R40+ to afford reset amount)
<p><b>Formula</b>: 2000 + 50 * R + 500 * x here x is amount of resets this R.
<p><b>Note</b>: It will reset the excavation counter to zero, all previously gained Excavation rewards and Rubies will persist and you can not find them again.</p>

<p><img src="http://musicfamily.org/realm/Factions/picks/QuestArtifacts.png" usemap="#QuestArtifacts-map">
<map name="QuestArtifacts-map">
    <area target="" research="<img src=http://musicfamily.org/realm/Factions/picks/AncientStoneSlab1.png alt=Artifacts align=middle><b> Ancient Stone Slab 1</b></p> <p><b>Clues</b>: We discovered an ancient stone slab written in old scriptures. It appears to say something about Halls of Legends.</p><p><b>Effect</b>: 1st clue required to unlock the Titan Alliance.</p> <p><b>Requirements</b>: 5th Excavation" coords="5,45,61,100" shape="rect">
    <area target="" research="<img src=http://musicfamily.org/realm/Factions/picks/FossilizedPieceofBark1.png alt=Artifacts align=middle><b> Fossilized Piece of Bark 1</b></p> <p><b>Clues</b>: We discovered a fossilized piece of Bark with the image of a Faction Coin carved into it.</p><p><b>Effect</b>: 1st clue required to unlock the Druid Alliance.</p> <p><b>Requirements</b>: 10th Excavation" coords="69,45,126,101" shape="0">
    <area target="" research="<img src=http://musicfamily.org/realm/Factions/picks/BoneFragment1.png alt=Artifacts align=middle><b> Bone Fragment 1</b></p> <p><b>Clues</b>: We discovered a sundial shaped artefact, probably made of animal bones.</p><p><b>Effect</b>: 1st clue required to unlock the Faceless Alliance.</p> <p><b>Requirements</b>: 15th Excavation" coords="133,44,191,101" shape="0">
    <area target="" research="<img src=http://musicfamily.org/realm/Factions/picks/AncientStoneSlab2.png alt=Artifacts align=middle><b> Ancient Stone Slab 2</b></p> <p><b>Clues</b>: We discovered an ancient stone slab written in old scriptures.We can recognize the number 300.</p><p><b>Effect</b>: 2nd clue required to unlock the Titan Alliance.</p> <p><b>Requirements</b>: 20th Excavation" coords="197,45,253,101" shape="0">
    <area target="" research="<img src=http://musicfamily.org/realm/Factions/picks/FossilizedPieceofBark2.png alt=Artifacts align=middle><b> Fossilized Piece of Bark 2</b></p> <p><b>Clues</b>: We discovered a fossilized piece of Bark with the symbol of One Million.</p><p><b>Effect</b>: 2nd clue required to unlock the Druid Alliance.</p> <p><b>Requirements</b>: 25th Excavation" coords="261,43,318,100" shape="0">
    <area target="" research="<img src=http://musicfamily.org/realm/Factions/picks/BoneFragment2.png alt=Artifacts align=middle><b> Bone Fragment 2</b></p> <p><b>Clues</b>: We discovered an artefact shaped like the number 36, probably made of animal bones.</p><p><b>Effect</b>: 2nd clue required to unlock the Faceless Alliance.</p> <p><b>Requirements</b>: 30th Excavation" coords="325,44,382,101" shape="0">
    <area target="" research="<img src=http://musicfamily.org/realm/Factions/picks/KeytotheLostCity.png alt=Artifacts align=middle><b> Key to the Lost City</b></p> <p><b>Clues</b>: Despite being thousands of years old, it's still shiny.</p><p><b>Effect</b>: Neutral Research</p> <p><b>Requirements</b>: 1500th Excavation (total), R23+" coords="389,44,446,101" shape="0">
    <area target="" research="<img src=http://musicfamily.org/realm/Factions/picks/AncientDevice.png alt=Artifacts align=middle><b> Ancient Device</b></p> <p><b>Clues</b>: This strange Device seems to react to the Ancient Races magical capabilities. We may channel its power to increase their research potential!</p><p><b>Effect</b>: Provides 2 additional slots: 1 for each related Neutral Faction Facility you are playing.</p> <p><b>Requirements</b>: Play a Neutral Faction and have over 2,000 excavations, Unique Building. <p><b>Chance</b>: 0.2%<p><b>Cost</b>: 100 QiSxg (1E200) <p><b>Alignment</b>: Neutral<p><b>Note</b>: Has no effect R100+/A2" coords="6,109,62,165" shape="0">
    <area target="" research="<img src=http://musicfamily.org/realm/Factions/picks/EarthCore.png alt=Earth Core align=middle><b> Earth Core</b></p> <p><b>Clues</b>: This piece of rock is continuously shifting its shape, responding to mysterious enery sources.</p><p><b>Effect</b>: Part of the Prestige research quest</p> <p><b>Requirements</b>: 2750th Excavation, R29+" coords="70,109,127,165" shape="0">
    <area target="" research="<img src=http://musicfamily.org/realm/Factions/picks/HornoftheKings.png alt=Horn of the Kings align=middle><b> Horn of the Kings</b></p> <p><b>Clues</b>: It is said that when this horn is blown, the voices of past Dwarven Kings can be heard in the Wind.</p><p><b>Effect</b>: Unlocks Legacy of the Kings upgrade that adds 2 extra slots: 2 for Craftsmanship and 1 to the faction's facility you are playing</p> <p><b>Requirements</b>: have Dwarven Forges, 3250+ Excavations (as Dwarf) Chance: 0.5%</p> <p><b>Cost</b>: 10 SxSpg (1E232) and 10m Dwarven Coins <p><b>Alignment</b>: Dwarf" coords="132,107,190,166" shape="0">
    <area target="" research="<img src=http://musicfamily.org/realm/Factions/picks/FlameofBondelnar.png alt=Flame of Bondelnar align=middle><b> Flame of Bondelnar</b></p> <p><b>Clues</b>: </p><p><b>Effect</b>: Unlocks the upgrade The Dark Light of Bondelnar that adds 2 extra slots: 2 for Warfare and 1 to the faction's facility you are playing</p> <p><b>Requirements</b>: Have Spider Sanctuaries (as Drow) Excavations: 3250+ Chance: 0.5%</p> <p><b>Cost</b>: 10 SxSpg (1E232), 10m Drow Coins <p><b>Alignment</b>: Drow" coords="197,108,253,166" shape="0">
    <area target="" research="<img src=http://musicfamily.org/realm/Factions/picks/SpikyRoughEggArtifact.png alt=Flame of Bondelnar align=middle><b> Spiky Rough Egg</b></p> <p><b>Clues</b>: What a weird egg... it looks ages old, yet something alive is inside. Perhaps if you wait long enough, something will hatch?</p><p><b>Effect</b>: Unlocks the Hatch! Egg</p> <p><b>Requirements</b>: R46+, 1500 Excavations (Chance: 2%)" coords="261,109,318,165" shape="0">
    <area target="" research="<img src=http://musicfamily.org/realm/Factions/picks/ObsidianShardArtifact.png alt=Obsidian Shard align=middle><b> Obsidian Shard</b><p><b>Description</b>: Extremely hard and black as darkness itself, this material cannot apparently be carved or melted. It is a mystery how you can make this thing into a sword.<p><b>Effect</b>: Unlocks Secrets of the Warriors <p>Requirement: 8000 Excavations any Faction, R75+" coords="324,108,382,165" shape="0">
    <area target="" research="<img src=http://musicfamily.org/realm/Factions/picks/FirstIronFragment.png align=middle> First Iron Fragment<p>Clue: This one seems to require a lot of magical renewance.<p>Description: It looks like a piece of an iron object. It's broken off on two sides.<p>Requirements: R125, 12,500+ Excavations, Play as Angel<p>Chance: (log10(1 + x) ^ 3 / 100000 (100K))%, where x is mana regen." coords="388,109,446,165" shape="0">
    <area target="" research="<img src=http://musicfamily.org/realm/Factions/picks/SecondIronFragment.png align=middle> Second Iron Fragment<p>Clue: Found via extensive Royal Trading mandates.<p>Description: It looks like a piece of an iron object. It's broken off on two sides.<p>Requirements: R125, 12,500+ Excavations, Play as Titan<p>Chance: (x ^ 3 / 5000000000 (5B))%, where x is individual royal exchange bonus." coords="5,172,62,229" shape="0">
    <area target="" research="<img src=http://musicfamily.org/realm/Factions/picks/ThirdIronFragment.png align=middle> Third Iron Fragment<p>Clue: Chances to find increase while not actively searching.<p>Description: It looks like a piece of an iron object. It's broken off on two sides.<p>Requirements: R125, 12,500+ Excavations, Play as Undead<p>Chance: (log10(1 + x) ^ 3 / 1000000 (1M))%, where x is offline bonus multiplier." coords="69,172,125,229" shape="0">
    <area target="" research="<img src=http://musicfamily.org/realm/Factions/picks/FirstCrystalFragment.png align=middle> First Crystal Fragment<p>Clue: Assistants will lead the way.<p>Description: A strange, glass-like material that appears to have been shattered into three pieces. <p>Requirements: R125, 12,500+ Excavations, Play as Fairy<p>Chance: (x / 100000000000 (100B))%, where x is assistant count." coords="133,173,190,228" shape="0">
    <area target="" research="<img src=http://musicfamily.org/realm/Factions/picks/SecondCrystalFragment.png align=middle> Second Crystal Fragment<p>Clue: Are Faction Coins attracted to glass?<p>Description: A strange, glass-like material that appears to have been shattered into three pieces.<p>Requirements: R125, 12,500+ Excavations, Play as Faceless<p>Chance: (log10(1 + x) ^ 3 / 5000000 (5M))%, where x is faction coins this game." coords="197,172,254,229" shape="0">
    <area target="" research="<img src=http://musicfamily.org/realm/Factions/picks/ThirdCrystalFragment.png align=middle> Third Crystal Fragment<p>Clue: Also acts as a spell catalyst.<p>Description: A strange, glass-like material that appears to have been shattered into three pieces.<p>Requirements: R125, 12,500+ Excavations, Play as Demon<p>Chance: (x / 50000000 (50M))%, where x is evil spells this R." coords="261,173,317,228" shape="0">
    <area target="" research="<img src=http://musicfamily.org/realm/Factions/picks/FirstStoneFragment.png align=middle> First Stone Fragment<p>Clue: Click to Carve.<p>Description: Made from stone so ancient it is unknown to the current world. Two parts seem to be missing.<p>Requirements: R125, 12,500+ Excavations, Play as Elf<p>Chance: (log10(1 + x) ^ 3) / 20000 (20K))%, where x is clicks this game" coords="325,172,383,229" shape="0">
    <area target="" research="<img src=http://musicfamily.org/realm/Factions/picks/SecondStoneFragment.png align=middle> Second Stone Fragment<p>Clue: Stone to stone, buildings to buildings.<p>Description: Made from stone so ancient it is unknown to the current world. Two parts seem to be missing.<p>Requirements: R125, 12,500+ Excavations, Play as Druid<p>Chance: (x / 20000000 (20M))%, where x is amount of buildings." coords="388,172,446,229" shape="0">
    <area target="" research="<img src=http://musicfamily.org/realm/Factions/picks/ThirdStoneFragment.png align=middle> Third Stone Fragment<p>Clue: Might be collected with taxes.<p>Description: Made from stone so ancient it is unknown to the current world. Two parts seem to be missing.<p>Requirements: R125, 12,500+ Excavations, Play as Goblin<p>Chance: (log10(1 + x) ^ 3) / 125000 (125K))%, where x is Tax Collections this game." coords="5,236,62,293" shape="0">
</map>
<p><img src="http://musicfamily.org/realm/Factions/picks/LoreArtifacts.png" usemap="#LoreArtifacts-map">
<map name="LoreArtifacts-map">
    <area target="" research="<img src=http://musicfamily.org/realm/Factions/picks/RoughStone.png alt=Artifact align=middle><b> Rough Stone</b></p><p>Clue: A first-time only discovery.<p><b>Description</b>: A common, totally uninteresting stone.</p><p><b>Effect</b>: Unlocks Research D290</p> <p><b>Requirement</b>: Chance: 2% On the first excavation of a run, after abdication or reincarnation." coords="5,44,61,101" shape="rect">
    <area target="" research="<img src=http://musicfamily.org/realm/Factions/picks/ScarabofFortune.png alt=Scarab of Fortune align=middle><b> Scarab of Fortune</b></p><p>Clue: Rarely found in the pyramids of old.<p><b>Description</b>: You found the rarest of relics. This golden scarab will grant you 7 days of good luck, starting from now. Make good use of it.</p> <p><b>Rewards</b>:  Awards an upgrade of the same name that increases the production of all buildings by 0.1% for each trophy you unlocked.</p> <p><b>Chance</b>: (#Ancient Pyramids)% / 1000.</p> <p><b>Cost</b>: 7 Td (7E42) <p><b>Alignment</b>: Any" coords="68,44,125,100" shape="0">
    <area target="" research="<img src=http://musicfamily.org/realm/Factions/picks/ChocolateCookie.png alt=Chocolate Cookie align=middle><b> Chocolate Cookie</b></p><p>Clue: Excavated commonly in all areas.<p><b>Description</b>: Found in a wasteland made of cakes and sweets, snatched from the hands of an old woman.</p> <p><b>Chance</b>: (# excavations / 50)%" coords="131,44,188,100" shape="0">
    <area target="" research="<img src=http://musicfamily.org/realm/Factions/picks/FossilizedRodent.png alt=Fossilized Rodent align=middle><b> Fossilized Rodent</b></p><p>Clue: Hello, mouse.<p><b>Description</b>: What's this, a prehistoric mouse...?</p> <p><b>Rewards</b>: Awards an upgrade of the same name, Increase clicking reward based on the amount of artifacts you discovered.</p> <p><b>Chance</b>: (# Treasure clicks this R / 5,000,000)%</p> <p><b>Cost</b>: 100 Qid (1E50) <p><b>Alignment</b>: Any" coords="196,45,253,100" shape="0">
    <area target="" research="<img src=http://musicfamily.org/realm/Factions/picks/PowerOrb.png alt=Power Orb align=middle><b> Power Orb</b></p><p>Clue: Attracted by massive concentration of mana.<p><b>Description</b>: Throbbing with Arcane Power</p> <p><b>Rewards</b>: Increases mana regeneration by 2.5%.</p> <p><b>Requirement</b>: +3000 max mana</p> <p><b>Chance</b>: (max mana / 15,000) %</p> <p><b>Cost</b>: 1 QaVg (1E75), A1+: Free</p> <p><b>Alignment</b>: Any" coords="260,45,317,100" shape="0">
    <area target="" research="<img src=http://musicfamily.org/realm/Factions/picks/PinkCarrot.png alt=Smiley face align=middle><b> Pink Carrot</b></p><p>Clue: Found randomly in the Farms.<p><b>Description</b>: The main product of properly nurtured Farms.</p> <p><b>Requirement</b>: Play as Fairy (Not Dwarf)</p> <p><b>Chance</b>: (# Farms / 5,000)%" coords="324,45,382,100" shape="0">
    <area target="" research="<img src=http://musicfamily.org/realm/Factions/picks/BottledVoice.png alt=Smiley face align=middle><b> Bottled Voice</b></p><p>Clue: Can be captured when Chanting.<p><b>Description</b>: The essence of a melodic Fairy voice.</p> <p><b>Requirement</b>: Play as Fairy (Not Dwarf)</p> <p><b>Chance</b>: (Fairy Chanting casts this game / 40,000)%" coords="388,45,443,100" shape="0">
    <area target="" research="<img src=http://musicfamily.org/realm/Factions/picks/LuckyClover.png alt=Smiley face align=middle><b> Lucky Clover</b></p><p>Clue: Requires extreme amounts of luck!<p><b>Description</b>: A perfectly shaped four leaf clover. Each leaf is almost unnaturally identical to the other three.</p> <p><b>Requirement</b>: Play as Elven (Not Dwarf)</p> <p><b>Chance</b>: (Highest # of consecutive Elven Luck-1) * 50)%" coords="5,107,61,165" shape="0">
    <area target="" research="<img src=http://musicfamily.org/realm/Factions/picks/Mini-treasure.png alt=Smiley face align=middle><b> Mini-treasure</b></p><p>Clue: Click your way to the treasure!<p><b>Description</b>: It's a small perfect replica of our gold-filled treasure.</p> <p><b>Requirement</b>: Play as Elven (Not Dwarf)</p> <p><b>Chance</b>: (# Clicks this game / 3,000,000)%" coords="68,108,124,165" shape="0">
    <area target="" research="<img src=http://musicfamily.org/realm/Factions/picks/Pillarfragment.png alt=Smiley face align=middle><b> Pillar Fragment</b></p><p>Clue: May fall from the Heavens.<p><b>Description</b>: A tiny piece of the legendary pillars which sustain all the Heavens.</p> <p><b>Requirement</b>: Play as Angel (Not Dwarf)</p> <p><b>Chance</b>: (# Heaven's Gate / 3,750)%" coords="132,108,189,165" shape="0">
    <area target="" research="<img src=http://musicfamily.org/realm/Factions/picks/DivineSword.png alt=Smiley face align=middle><b> Divine Sword</b></p><p>Clue: Only found by dedicated Angel allies.<p><b>Description</b>: The shining golden sword of an Archangel. Its hilt feels pleasantly warm to the pure of heart and burning hot for the villain.</p> <p><b>Requirement</b>: Play as Angel (Not Dwarf)+3 consecutive Angels runs (This R). Even just buying the Angels Trade Treaty counts towards this artifact.</p> <p><b>Chance</b>: (Consecutive times allied with Angels this R / 60)%" coords="196,108,253,164" shape="0">
    <area target="" research="<img src=http://musicfamily.org/realm/Factions/picks/AncientCoinPiece.png alt=Artifacts align=middle><b> Ancient Coin Piece</b></p><p>Clue: Rarely found among other special coins.<p><b>Description</b>: A common goblin lucky charm. The older it is, the luckier you are, or so they say.</p> <p><b>Requirement</b>: Play as Goblin (Not Drow)</p> <p><b>Chance</b>: (#Faction Coins this R# / 50,000,000)%" coords="260,108,316,165" shape="0">
    <area target="" research="<img src=http://musicfamily.org/realm/Factions/picks/GoblinPurse.png alt=Artifacts align=middle><b> Goblin Purse</b></p><p>Clue: Fill your pockets with extorted money.<p><b>Description</b>: Heavy and roomy. Definitely too big for just pocket change.</p> <p><b>Requirement</b>: Play as Goblin (Not Drow)</p> <p><b>Chance</b>: (Tax collection casts this game / 300,000)%" coords="323,107,380,165" shape="0">
    <area target="" research="<img src=http://musicfamily.org/realm/Factions/picks/RottenOrgan.png alt=Artifacts align=middle><b> Rotten Organ</b></p><p>Clue: Found among large masses of dead bodies.<p><b>Description</b>: Ew... disgusting. It still pulses.</p> <p><b>Requirement</b>: Play as Undead (Not Drow)</p> <p><b>Chance</b>: (# Assistants / 500)%" coords="387,107,444,165" shape="0">
    <area target="" research="<img src=http://musicfamily.org/realm/Factions/picks/JawBone.png alt=Artifacts align=middle><b> Jaw Bone</b></p><p>Clue: Needs some time off.<p><b>Description</b>: A jaw, missing more than half of its teeth.</p> <p><b>Requirement</b>: Play as Undead (Not Drow) +24h offline (This R)</p> <p><b>Chance</b>: (Offline playtime this R / 10d)%" coords="5,171,61,229" shape="0">
    <area target="" research="<img src=http://musicfamily.org/realm/Factions/picks/DemonicFigurine.png alt=Artifacts align=middle><b> Demonic Figurine</b></p><p>Clue: Look for the trophies of the beast.<p><b>Description</b>: An intricate figurine representing the evil face of a lesser demon.</p> <p><b>Requirement</b>: Play as Demon (Not Drow) 666 Trophies unlocked.</p> <p><b>Chance</b>: 1%" coords="67,173,124,229" shape="0">
    <area target="" research="<img src=http://musicfamily.org/realm/Factions/picks/DemonHorn.png alt=Artifacts align=middle><b> Demon Horn</b></p><p>Clue: Only found by dedicated Demon allies.<p><b>Description</b>: Still blazing with the flames of Hell. Handle with care.</p> <p><b>Requirement</b>: Play as Demon (Not Drow) +3 consecutive Demon runs (This R). Even just buying the Demons Trade Treaty counts towards this artifact.</p> <p><b>Chance</b>: (Consecutive times allied with Demon this R / 60)%" coords="132,172,189,228" shape="0">
    <area target="" research="<img src=http://musicfamily.org/realm/Factions/picks/HugeTitanStatue.png alt=Artifacts align=middle><b> Huge Titan Statue</b></p><p>Clue: Struck by the lightning.<p><b>Description</b>: The granite representation of a giant wielding a lightning bolt in its fist. A foot appears to be missing.</p> <p><b>Requirement</b>: Play as Titan (Not Dragon)</p> <p><b>Chance</b>: (Lightning Strike Casts this game / 1000)%" coords="196,170,253,228" shape="0">
    <area target="" research="<img src=http://musicfamily.org/realm/Factions/picks/TitanShield.png alt=Artifacts align=middle><b> Titan Shield</b></p><p>Clue: Don't fret it.<p><b>Description</b>: A gargantuan metal shield, twice as tall as a common human.</p> <p><b>Requirement</b>: Play as Titan (Not Dragon) +10h playtime (This game)</p> <p><b>Chance</b>: (Playtime this game / 50h)%" coords="259,173,317,228" shape="0">
    <area target="" research="<img src=http://musicfamily.org/realm/Factions/picks/GlyphTable.png alt=Artifacts align=middle><b> Glyph Table</b></p><p>Clue: Balance your buildings.<p><b>Description</b>: Contains all the secrets of the Druidic Alphabet.</p> <p><b>Requirement</b>: Play as Druid (Not Dragon) +Same amount of each Neutral building.</p> <p><b>Chance</b>: 2%" coords="324,172,380,228" shape="0">
    <area target="" research="<img src=http://musicfamily.org/realm/Factions/picks/StoneOfBalance.png alt=Artifacts align=middle><b> Stone of Balance</b></p><p>Clue: A Grand Balance performance.<p><b>Description</b>: A carved stone hovering above its pedestal.</p> <p><b>Requirement</b>: Play as Druid (Not Dragon)</p> <p><b>Chance</b>: (Grand Balance Casts this game / 30,000)%" coords="387,172,445,230" shape="0">
    <area target="" research="<img src=http://musicfamily.org/realm/Factions/picks/TranslucentGoo.png alt=Artifacts align=middle><b> Translucent Goo</b></p><p>Clue: Byproduct of the Brain.<p><b>Description</b>: A completely odorless sticky substance with a diaphanous, unsettling glow.</p> <p><b>Requirement</b>: Play as Faceless (Not Dragon)</p> <p><b>Chance</b>: (Brainwave casts this game / 400)%" coords="5,235,62,294" shape="0">
    <area target="" research="<img src=http://musicfamily.org/realm/Factions/picks/Octopus-shapedHelmet.png alt=Artifacts align=middle><b> Octopus-shaped Helmet</b></p><p>Clue: Found in the Labyrinths.<p><b>Description</b>: A large helmet with empty metal prongs to accomodate tentacular appendages.</p> <p><b>Requirement</b>: Play as Faceless (Not Dragon)</p> <p><b>Chance</b>: (# Labyrinths / 2000)%" coords="68,236,124,292" shape="0">
    <area target="" research="<img src=http://musicfamily.org/realm/Factions/picks/DwarvenBow.png alt=Artifacts align=middle><b> Dwarven Bow</b></p><p>Clue: Click to throw.<p><b>Description</b>: Actually a heavy throwing hammer.</p> <p><b>Requirement</b>: Play as Dwarves</p> <p><b>Chance</b>: (# clicks this game / 25,000)%" coords="132,235,188,292" shape="0">
    <area target="" research="<img src=http://musicfamily.org/realm/Factions/picks/StoneTankard.png alt=Artifacts align=middle><b> Stone Tankard</b></p><p>Clue: Found in the Inns.<p><b>Description</b>: A very heavy mug for drinking the heaviest beers.</p> <p><b>Requirement</b>: Play as Dwarves</p> <p><b>Chance</b>: (# Inns / 25,000)%" coords="196,235,252,292" shape="0">
    <area target="" research="<img src=http://musicfamily.org/realm/Factions/picks/CeremonialDagger.png alt=Artifacts align=middle><b> Ceremonial Dagger</b></p><p>Clue: Avoid hurting your fingers.<p><b>Description</b>: Its blade is unnaturally keen and sharp.</p> <p><b>Requirement</b>: Play as Drow, 0 Treasure clicks (This Game) (This includes automatic clicks)</p> <p><b>Chance</b>: 2%" coords="259,236,317,292" shape="0">
    <area target="" research="<img src=http://musicfamily.org/realm/Factions/picks/ArachnidFigurine.png alt=Arachnid Figurine align=middle><b> Arachnid Figurine</b></p><p>Clue: Embrace Evil. For a while.<p><b>Description</b>: If you are afraid of spiders, Drow aren't your faction.</p> <p><b>Requirement</b>: Play as Drow +24h Evil Playtime (All-time)</p> <p><b>Chance</b>: (All-time Evil playtime / 50d)%" coords="324,235,381,292" shape="0">
    <area target="" research="<img src=http://musicfamily.org/realm/Factions/picks/SteelPlate.png alt=Steel Plate align=middle><b> Steel Plate</b></p><p>Clue: Legacy from 50 generations ago.<p><b>Description</b>: A full plate made of hardened steel.</p> <p><b>Requirement</b>: Play as Mercenaries +R5</p> <p><b>Chance</b>: (#R / 50)%" coords="387,236,445,292" shape="0">
    <area target="" research="<img src=http://musicfamily.org/realm/Factions/picks/BlackSword.png alt=Black Sword align=middle><b> Black Sword</b></p><p>Clue: Only found by really, really dedicated Mercenary allies.<p><b>Description</b>: A long sword with an extremely sharp blade made of dark metal.</p> <p><b>Requirement</b>: Play as Mercenaries +100 Merc affiliations (All-time)</p> <p><b>Chance</b>: (All-time Mercenary playtime / 16h 40m)%" coords="3,298,62,356" shape="0">
    <area target="" research="<img src=http://musicfamily.org/realm/Factions/picks/DragonFangArtifact.png alt=Dragon Fang align=middle><b> Dragon Fang</b></p><p>Clue: Found in the Wyrm Dens.<p><b>Description</b>: This huge fang can barely fit in the hands of a Titan.</p> <p><b>Requirement</b>: R50+, play as Dragons <p><b>Chance</b>: Excavate (# Iron Strongholds / 400,000)%</p> <p><b>Alignment</b>: Neutral faction, Dragons" coords="68,299,125,356" shape="0">
    <area target="" research="<img src=http://musicfamily.org/realm/Factions/picks/DragonSoulArtifact.png alt=Dragon Soul align=middle><b> Dragon Soul</b></p><p>Clue: Take five deep breaths.<p><b>Description</b>: The extracted soul from an ancient dragon, wields the power to end the world in an instant. Also makes a good soup ingredient.</p> <p><b>Requirement</b>: R50+, play as Dragons, have 5 different Dragon Breath effects active simultaneously.</p> <p><b>Chance</b>: Excavate (# Dragon Breath casts this game / 200,000)% <p><b>Alignment</b>: Neutral faction, Dragons" coords="132,300,188,356" shape="0">
    <area target="" research="<img src=http://musicfamily.org/realm/Factions/picks/VanillaFlavorJuice.png alt=Smiley face align=middle><b> Vanilla Flavor Juice</b></p><p>Clue: Quickly!<p><b>Description</b>: An essence from extremely savory vanilla beans.</p> <p><b>Rewards</b>: Increase the production of all buildings by 25,000% for the first 25 minutes of the game (this game) for all Vanilla factions. Doesn't work while offline.</p> <p><b>Note</b>: Effect is canceled if you Prestige.</p> <p><b>Requirement</b>: +R16</p> <p><b>Chance</b>: 20% in the first 5m of a game</p> <p><b>Cost</b>: 1 coin <p><b>Alignment</b>: Vanilla faction" coords="196,300,253,357" shape="0">
    <area target="" research="<img src=http://musicfamily.org/realm/Factions/picks/AncientCocoaBeanArtifacts.png align=middle><b> Ancient Cocoa Bean</b><p>Clue: True Neutral Flavor.<p>Description: Despite being centuries old, it still smells like top-quality cocoa.<p>Requirement: Neutral, R22+, Must be Neutral Faction to buy upgrade<p>Effect: Gives an upgrade named Chocolate Flavored Smoothie<P>Upgrade Effect: Increase the production of all buildings by 25000% for the first 15 minutes of the game for all Neutral factions.<P>Upgrade Effect: A2, Increase the production of all buildings by 5.68% for the first 15 minutes of the game for all Neutral factions. Does not work while offline.<p>Chance: 10%" coords="259,299,317,356" shape="0">
    <area target="" research="<img src=http://musicfamily.org/realm/Factions/picks/KnowYourEnemyPartI.png align=middle><b> Know Your Enemy, Part I</b></p><p>Clue: A true Mercenary should learn by all other cultures.<p><b>Description</b>: All the knowledge you need, stored in a handy book.</p> <p><b>Rewards</b>: Awards an upgrade of the same name that increases the production of all buildings based on time spent as Non-Mercenary. (&amp;amp;quot;Time allied with...&amp;amp;quot; in the stats) <p><b>Formula</b>: (0.75 * x ^ 0.6)%, where x is amount of time spent as non-mercenary factions (in seconds). <p><b>Requirement</b>: Play as Mercenaries, have upgrades from each 11 factions. +R12</p> <p><b>Chance</b>: 10%</p> <p><b>Cost</b>: 100 Vg (1E65) <p><b>Alignment</b>: Mercenary" coords="324,300,381,356" shape="0">
    <area target="" research="<img src=http://musicfamily.org/realm/Factions/picks/VoodooDoll.png align=middle><b> Voodoo Doll</b></p><p>Clue: Found in the Witch Conclaves.<p><b>Description</b>: You are now CURSED! And you feel a sting in your lower rear.</p> <p><b>Rewards</b>: Increase the production of all building by 0.1% for each trophy you have unlocked</p> <p><b>Requirement</b>: Play as Evil (Only required to get Witch Conclaves)</p> <p><b>Cost</b>: 20 Qig (2E154) <p><b>Chance</b>: (number of Witch Conclaves / 10000)%</p> <p><b>Alignment</b>: Any" coords="387,298,445,358" shape="0">
    <area target="" research="<img src=http://musicfamily.org/realm/Factions/picks/WallFragment.png align=middle><b> Wall Fragment</b></p><p>Clue: Ascension...<p><b>Description</b>: A fragment of an utterly and completely unbreakable wall. Enjoy your paradox.</p> <p><b>Rewards</b>: Increase the production of all buildings based on their tier.</p> <p><b>Formula</b>: (2.5*x^2), where x is the building tier, starting at 1 for Halls of Legends and increasing to 11 for Farms. <p><b>Requirement</b>: At least 1 Ascension <p><b>Chance</b>: 10%</p> <p><b>Cost</b>: 1 M (1E6) <p><b>Alignment</b>: Any" coords="4,363,60,421" shape="0">
    <area target="" research="<img src=http://musicfamily.org/realm/Factions/picks/FortuntTellerMachineArtifact.png align=middle><b> Fortune Teller Machine</b></p><p>Clue: Dont choose your allies until you know more.<p><b>Requirement</b>: Excavate (Chance 0.1%)</p> <p><b>Alignment</b>: Any (No Faction) <p><b>Description</b>: Will tell you 1 of 24 statements at random.<p>Upgrade Requirement: R42+<p>Cost: R42+ 1 No (1e32)<p>Cost: Post A2 Free<p>Effect: Increase the production of Non-Unique buildings based on total time spent. (Time in seconds this R)<p>Formula: 6.5 * x ^ 0.65, where x is time this R" coords="67,364,127,421" shape="0">
    <area target="" research="<img src=http://musicfamily.org/realm/Factions/picks/DawnstoneArtifact.png align=middle><b> Dawnstone</b></p><p>Clue: Relic of the Dawn hours.<p><b>Description</b>: Only found during sunrise hours. Emits a faint glow.</p> <p><b>Rewards</b>: With Both the Duskstone and Dawnstone artifacts, awards the Sun Force upgrade, which grants different effects based on time of the day.</p> <p><b>Requirement</b>: Excavate between 5:00am and 8:00am (Your local time)<p><b>Chance</b>: (Excavation count / 10,000)%</p><p>Click image for details" href="http://musicfamily.org/realm/SunForce/" coords="132,363,190,422" shape="0">
    <area target="" research="<img src=http://musicfamily.org/realm/Factions/picks/DuskstoneArtifact.png align=middle><b> Duskstone</b></p><p>Clue: Relic of the Dusk hours.<p><b>Description</b>: Only found during sunset hours. Absorbs light in a small radius.</p> <p><b>Rewards</b>: With Both the Dawnstone and Duskstone artifacts, awards the Sun Force upgrade, which grants different effects based on time of the day.</p> <p><b>Requirement</b>: Excavate between 6:00pm and 9:00pm (Your local time)<p><b>Chance</b>: (Excavation count / 10,000)%</p><p>Click image for details" href="http://musicfamily.org/realm/SunForce/" coords="196,364,253,421" shape="0">
    <area target="" research="<img src=http://musicfamily.org/realm/Factions/picks/AncientHeirloomTrophy.png align=middle><b> Ancient Heirloom</b></p><p>Clue: Relic of the Lineage.<p><b>Requirements</b>: Have at least 1 Lineage level purchased. <p><b>Chance</b>: (Total Lineage levels/20)% <p><b>Effect</b>: Reduces the cost multiplier of Lineage by 10%, (Except for the highest one) (Instead of 10x more per level it is  9x more per level) <p><b>Formula</b>: Without Ancient Heirloom 25 * 10^(15+lineages) <p>Formula: With Ancient Heirloom (25 * 10^(15+lineages))^0.9<p><b>Cost</b>: 10 Dtg (1e100)" coords="260,362,317,421" shape="0">
    <area target="" research="<img src=http://musicfamily.org/realm/Factions/picks/KnowYourEnemyPart2.png align=middle><b> Know Your Enemy, Part 2</b></p><p>Clue: Even an expert Mercenary should learn by all other cultures.<p><b>Description</b>: Much more knowledge than you need, stored in a handy book.<p><b>Reward</b>: Awards an upgrade of the same name that Increase the production of all buildings based on time spent as Non-Mercenaries.<p><b>Note</b>: Only available to Mercenaries<p><b>Formula</b>: 0.065 * x^0.65 where x is amount of time spent as non-mercenary factions (in seconds).<p><b>Requirement</b>: R76+, Upgrade from all 12 Factions<p>Chance: 5%<p><b>Secret Upgrade Cost</b>: 100 Noqag (1e152)" coords="325,364,381,421" shape="0">
    <area target="" research="<img src=http://musicfamily.org/realm/Factions/picks/VeteranFigurineArtifact.png align=middle><b> Veteran Figurine</b></p><p>Clue: A reward for the veteran challenger.<p><b>Description</b>: The warrior of a thousand battles, ultimate champion of the Realms.<p><b>Requirement</b>: R90+<p>Chance: (x/1,000,000)%, where x is seconds this game.<p><b>Effect</b>: Passive effect: allows Mercenaries to benefit from all challenges." coords="387,363,446,422" shape="0">
    <area target="" research="<img src=http://musicfamily.org/realm/Factions/picks/WallChunckArtifact.png align=middle><b> Wall Chunk</b></p><p>Clue: More Ascension...<p><b>Description</b>: A bigger piece of the infamous Ascension Wall.<p><b>Requirement</b>: R100+ <p><b>Chance</b>: 10%</p> <p><b>Effect</b>: Increase the production of all buildings based on their tier<p><b>Cost</b>: 1 Sx (1e21)<p><b>Formula</b>: 30000 * (11-x) ^ 3.5, where x is building tier." coords="4,426,60,485" shape="0">
    <area target="" research="<img src=http://musicfamily.org/realm/Factions/picks/ExcavatedMirageArtifact.png align=middle><b> Excavated Mirage</b></p><p>Clue: Raise your chances.<p><b>Description</b>: You know all too well this does not exist, yet it fills you with hope and optimism.<p><b>Requirement </b>: Ascension 2<p><b>Effect</b>: Increase Faction Coin find chance by a multiplicative 2000%.<p><b>Cost</b>: 1 Sx (1e21)<p>Chance: (log10(x) / 100)%, where x is FC chance" coords="67,427,126,486" shape="0">
    <area target="" research="<img src=http://musicfamily.org/realm/Factions/picks/AncestralHourglassArtifact.png align=middle><b> Ancestral Hourglass</b></p><p>Clue: Really, raise your chances.<p>Description: The silver sands contained within seem to never stop flowing.<p>Requirement:  R100+<p>Upgrade Cost: (1e90)<p>Effect: Lower cost of Lineage level based on time spent this game. FC cost is reset when you purchase a new lineage level.<p>Formula: (x ^ (0.9 - 0.01 * (((y - 20) ^ 1.4) - z / 4)) / 10), where x is hours this game, y is lineage level and z is reincarnations.<p>Lineage Cost Formula: (25 * 10 ^ (15 + level - hourglass.formula)) ^ 0.9 (if ancient heirloom).<p>Chance: (x / 10000000000000000 (10 QA))%, where x is FC chance." coords="132,428,189,486" shape="0">
    <area target="" research="<img src=http://musicfamily.org/realm/Factions/picks/SilkClothArtifact.png align=middle><b> Silk Cloth</b></p><p>Clue: Found in the Swarming Towers.<p>Description: The purest silk made for Fairies, by Fairies, of Fairies.<p>Requirement:  R100+, 3000+ Excavations, Play as Fairy<p>Chance: ((x - 10000) / 200000)%, where x is Wizard Towers built (Building count multipliers do NOT count)." coords="196,428,252,486" shape="0">
    <area target="" research="<img src=http://musicfamily.org/realm/Factions/picks/RawEmeraldArtifact.png align=middle><b> Raw Emerald</b></p><p>Clue: Not found on the first Excavation round.<p>Description: Just slightly less precious than a raw Ruby.<p>Requirement:  R100+, 3000+ Excavations, Play as Elven<p>Chance: (((2 * x) ^ 4.5) / 10000)%, where x is non-ruby excavation resets (this game)." coords="260,429,317,486" shape="0">
    <area target="" research="<img src=http://musicfamily.org/realm/Factions/picks/FossilizedWingArtifact.png align=middle><b> Fossilized Wing</b></p><p>Clue: Angels may fall after a long time.<p>Description: The remains of an Angel fallen to earth.<p>Requirement:  R100+, 3000+ Excavations, Play as Angel<p>Chance: (x / 25920000 (300 days))%, where x is angel time (all time) in seconds." coords="324,428,382,485" shape="0">
    <area target="" research="<img src=http://musicfamily.org/realm/Factions/picks/SpikedWhipArtifact.png align=middle><b> Spiked Whip</b></p><p>Clue: Used by the overseers in the Slave Markets.<p>Description: Use with caution. You do not want to exterminate all your slaves.<p>Requirement:  R100+, 3000+ Excavations, Play as Goblin<p>Chance: ((x - 10000) / 300000)%, where x is Slave Pens (Building count multipliers do NOT count)." coords="387,428,445,485" shape="0">
    <area target="" research="<img src=http://musicfamily.org/realm/Factions/picks/DustyCoffinArtifact.png align=middle><b> Dusty Coffin</b></p><p>Clue: Quick! Quick! You have no time to waste!<p>Description: Sealed since forever, yet you can hear a strange noise from within.<p>Requirement:  R100+, 3000+ Excavations, Play as Undead<p>Chance: (1 / (30 + x ^ 1.5))%, where x is time this game in seconds." coords="4,492,60,550" shape="0">
    <area target="" research="<img src=http://musicfamily.org/realm/Factions/picks/CrystallizedLavaArtifact.png align=middle><b> Crystallized Lava</b></p><p>Clue: Found in the Burning Abysses.<p>Description: Incandescent but still. Can be used efficiently as a desk lamp.<p>Requirement:  R100+, 3000+ Excavations, Play as Demon<p>Chance: ((x - 10000) / 200000)%, where x is Hall of Legends (Building count multipliers do NOT count)." coords="68,492,125,548" shape="0">
    <area target="" research="<img src=http://musicfamily.org/realm/Factions/picks/TitanHelmetArtifact.png align=middle><b> Titan Helmet</b></p><p>Clue: Found in the trade route used for Exchanges.<p>Description: Made of enough metal to craft a human-sized full plate.<p>Requirement:  R100+, 3000+ Excavations, Play as Titan<p>Chance: ((x ^ 2) / 1,500,000,000 (1.5B))%, where x is Royal Exchanges (Royal Exchange count multipliers <b>DO NOT</b> count)." coords="132,491,189,548" shape="0">
    <area target="" research="<img src=http://musicfamily.org/realm/Factions/picks/BranchoftheLifeTreeArtifact.png align=middle><b> Branch of the Life Tree</b><p>Clue: Found in the remains of druidic ancestors.<p>Description: Despite being torn from its source tree, it keeps growing buds and leaves.<p>Requirement: R100+, 3000+ Excavations, Play as Druid<p>Chance:  ((x ^ 3) / 2000000 (2M))%, where x is level of druid lineage." coords="196,490,253,548" shape="0">
    <area target="" research="<img src=http://musicfamily.org/realm/Factions/picks/NightmareFigmentArtifact.png align=middle><b> Nightmare Figment</b><p>Clue: A strong and quick brain is required.<p>Description: An unshaped, ephemeral substance which is politely trying to corrupt your mind.<p>Requirement:  R100+, 3000+ Excavations, Play as Faceless<p>Chance: ((x ^ 1.5) / 20000000 (20M))%, where x is headstart time in seconds." coords="260,491,317,549" shape="0">
    <area target="" research="<img src=http://musicfamily.org/realm/Factions/picks/BeardHair.png align=middle><b> Beard Hair</b></p><b>Clue</b>: It requires a lot of beard samples to get the perfect hair.<p><b>Description</b>: Hopefully coming from a real dwarven beard.</p> <p><b>Requirement</b>: R116+, 3000+ Excavations, Play as Dwarf</p> <p><b>Chance</b>: (x / 100000000 (100M))%, where x is assistant count" coords="323,493,381,551" shape="0">
    <area target="" research="<img src=http://musicfamily.org/realm/Factions/picks/PoisonVial.png align=middle><b> Poison Vial</b></p><b>Clue</b>: Combo your way through.<p><b>Description</b>: One drop of this is enough to fell thousands of non-immune creatures.</p> <p><b>Requirement</b>: R116+, 3000+ Excavations, Play as Drow</p> <p><b>Chance</b>: (x / 10000000 (10M))%, where x is combo strike production bonus (T1, no A-nerf)" coords="388,492,446,550" shape="0">
    <area target="" research="<img src=http://musicfamily.org/realm/Factions/picks/DragonScale.png align=middle><b> Dragon Scale</b></p><p><b>Clue</b>: Usually found when a lot of magic is lingering.<p><b>Description</b>: Very high on the realms' most accurate hardiness rankings.</p> <p><b>Requirement</b>: R116+, 3000+ Excavations, Play as Dragon</p> <p><b>Chance</b>: (x / 2500)%, where x is active spells" coords="4,555,60,613" shape="0">
    <area target="" research="<img src=http://musicfamily.org/realm/Factions/picks/LanternofGuidanceArtifact.png align=middle> Lantern of Guidance</b></p> <p><b>Clue</b>: Massive mana flows can offer guidance.</p> <p><b>Description</b>: Follow the guiding light, o wonderer, for it shall bring you fortune.</p> <p><b>Requirements</b>: R120+, Proof of Order</p> <p><b>Chance</b>: (x / 10,000,000,000 (10B))%, where x is mana regen.</p> <p><b>Effect</b>: Unlocks Tier 2 Temporal Flux" coords="67,555,124,612" shape="0">
    <area target="" research="<img src=http://musicfamily.org/realm/Factions/picks/OilLampArtifact.png align=middle> Oil Lamp</b></p> <p><b>Clue</b>: Chaos magic burns brightly.</p> <p><b>Description</b>: Rub it, polish it. And remember to express your desires precisely, lest you want to face dire consequences.</p> <p><b>Requirements</b>: R120+, Proof of Chaos</p> <p><b>Chance</b>: (min(x, y, z) / 1000 days)%, where x is Fairy Chanting spell activity time, y is Hellfire Blast spell activity time, and z is Brainwave spell activity time (all time).</p> <p><b>Effect</b>: Unlocks Tier 2 Maelstrom" coords="132,557,189,612" shape="0">
    <area target="" research="<img src=http://musicfamily.org/realm/Factions/picks/SparkofLifeArtifact.png align=middle> Spark of Life</b></p> <p><b>Clue</b>: The power of Creation may spark something new.</p> <p><b>Description</b>: The spark of Creation, dimly shining from the bottom of its encasing crystal.</p> <p><b>Requirements</b>: R120+, Proof of Balance</p> <p><b>Chance</b>: (ln(1 + x) ^ 2 / 12000)%, where x is FC collected this game.</p> <p><b>Effect</b>: Unlocks Tier 2 All Creation" coords="196,557,253,613" shape="0">
    <area target="" research="<img src=http://musicfamily.org/realm/Factions/picks/PlanetaryForceArtifact.png align=middle> Planetary Force</p></b> <p><b>Clue</b>: Try every day for better luck! Missing a day is the same as breaking a mirror, you know.</p><p><b>Description</b>: Planets aligning seem to affect your realm in different ways...</p> <p><b>Requirements</b>: R100+</p> <p><b>Chance</b>: ((x ^ 2.5) / 5000)%, where x is amount of consecutive days logged in.</p> <p><b>Note</b>: Restarting the game is required to increase the counter</p> <p><b>Effect</b>: Gives upgrade with the same name</p> <p><b>Upgrade Effect</b>: Activates all Sun Force effects at once.</p> <p><b>Upgrade Cost</b>: 100 Qi (1e20)</p>" coords="259,555,316,612" shape="rect">
</map>
<h6>Artifact Sets</h6>
<p><b>Finding all the faction artifacts for a specific faction</b> will also unlock a new selection of upgrades called "Artifact Sets". You will be able to pick one per game only, similar to Bloodlines and Lineages. Abdicating will reset your choice and allow to pick another.
<p><b>Requires all artifacts related to the faction to use its set.</b>
<h6><center><img src="http://musicfamily.org/realm/Factions/picks/FactionSets.png" usemap="#FactionSets-map"></h6>
<map name="FactionSets-map">
    <area target="" research="<img src=http://musicfamily.org/realm/Factions/picks/FairySet.png align=middle><b> Fairy Set</b></p><p>Requirement: A2+<p>Artifacts Required: Silk Cloth, Pink Carrot, Bottled Voice<p>Cost: Free<p>Effect: Increase Farm, Inn and Blacksmith production based on number of assistants owned.<p>Formula: (0.7 * x ^ 0.7), where x is number of assistants owned." coords="30,22,76,69" shape="rect">
    <area target="" research="<img src=http://musicfamily.org/realm/Factions/picks/ElvenSet.png align=middle><b> Elven Set</b></p><p>Requirement: A2+<p>Artifacts Required: Raw Emerald, Lucky Clover, Mini-treasure<p>Cost: Free<p>Effect: Increase all building production based on total amount of Elven Lucks triggered (This R)(since unlock).<p>Formula: (6 * x ^ 0.6), where x is amount of Elven Lucks triggered." coords="82,22,129,70" shape="rect">
    <area target="" research="<img src=http://musicfamily.org/realm/Factions/picks/AngelSet.png align=middle><b> Angel Set</b></p><p>Requirement: A2+<p>Artifacts Required: Fossilized Wing, Pillar Fragment, Divine Sword<p>Cost: Free<p>Effect: Additively increase Mana Regeneration based on highest amount of spells cast in a single game.<p>Formula: (3 * x ^ 0.3), where x is spells cast in a single game." coords="134,22,182,69" shape="rect">
    <area target="" research="<img src=http://musicfamily.org/realm/Factions/picks/GoblinSet.png align=middle><b> Goblin Set</b></p><p>Requirement: A2+<p>Artifacts Required: Spiked Whip, Ancient Coin Piece, Goblin Purse<p>Cost: Free<p>Effect: Increase Faction Coin find chance additively and multiplicatively based on time spent in this game.<p>Additive Formula: (70 * x ^ 0.7), where x is time spent in this game.<p>Multiplicative Formula: (0.5 * x ^ 0.5), where x is time spent in this game." coords="28,75,77,120" shape="rect">
    <area target="" research="<img src=http://musicfamily.org/realm/Factions/picks/UndeadSet.png align=middle><b> Undead Set</b></p><p>Requirement: A2+<p>Artifacts Required: Dusty Coffin, Rotten Organ, Jaw Bone<p>Cost: Free<p>Effect: Additively Increase max mana based on offline bonus.<p>Formula: (9 * ln(1 + x) ^3), where x is offline Multiplier." coords="81,73,130,124" shape="rect">
    <area target="" research="<img src=http://musicfamily.org/realm/Factions/picks/DemonSet.png align=middle><b> Demon Set</b></p><p>Requirement: A2+<p>Artifacts Required: Crystallized Lava, Demonic Figurine, Demon Horn<p>Cost: Free<p>Effect: Increase non unique building production based on the sum of your faction spells activity time. (This R)<p>Formula: (0.4 * x ^ 0.75), where x is faction spell activity time." coords="133,74,182,121" shape="rect">
    <area target="" research="<img src=http://musicfamily.org/realm/Factions/picks/TitanSet.png align=middle><b> Titan Set</b></p><p>Requirement: A2+<p>Artifacts Required: Titan Helmet, Huge Titan Statue, Titan Shield<p>Cost: Free<p>Effect: Increase Royal Exchange Bonus additively and multiplicatively based on time spent in this game.<p>Aditive Formula: (0.3 * x ^ 0.7), where x is time spent in this game.<p>Multiplicative Formula: (0.45 * x ^ 0.45), where x is time spent in this game." coords="30,127,78,174" shape="rect">
    <area target="" research="<img src=http://musicfamily.org/realm/Factions/picks/DruidSet.png align=middle><b> Druid Set</b></p><p>Requirement: A2+<p>Artifacts Required: Branch of the Life Tree, Glyph Table, Stone Of Balance<p>Cost: Free<p>Effect: Increase production of all buildings based on their quantity.<p>Effect: Also considers building count upgrades.<p>Formula: (0.8 * x ^ 0.7), where x is building count." coords="81,127,130,175" shape="rect">
    <area target="" research="<img src=http://musicfamily.org/realm/Factions/picks/FacelessSet.png align=middle><b> Faceless Set</b></p><p>Requirement: A2+<p>Artifacts Required: Nightmare Figment, Translucent Goo, Octopus-shaped Helmet<p>Cost: Free<p>Effect: Gain assistants based on the highest amount of assistants you had in a previous game.(additively)<p>Formula: (2.5 * x ^ 0.5), where x is the highest amount of assistants you had in a previous game." coords="135,127,183,174" shape="rect">
    <area target="" research="<img src=http://musicfamily.org/realm/Factions/picks/DwarvenSet.png align=middle><b> Dwarven Set</b></p> <p><b>Requirement</b>: R116+</p> <p><b>Artifacts Required</b>: Dwarven Bow, Stone Tankard, Beard Hair</p> <p><b>Cost</b>: Free</p> <p><b>Effect</b>: Increase assistants based on your Royal Exchange bonus.</p> <p><b>Formula</b>: (2.25 * x ^ 0.75), where x is Royal Exchange bonus." coords="28,179,77,225" shape="rect">
    <area target="" research="<img src=http://musicfamily.org/realm/Factions/picks/DrowSet.png align=middle><b> Drow Set</b></p> <p><b>Requirement</b>: R116+</p> <p><b>Artifacts Required</b>: Ceremonial Dagger, Arachnid Figurine, Poison Vial</p> <p><b>Cost</b>: Free</p> <p><b>Effect</b>: Increase the production of Unique Buildings based on Evil spells cast in this Reincarnation.(additive)</p><p><b>Formula</b>: (0.45 * x ^ 0.45), where x is total evil spells cast (this R)." coords="81,178,130,225" shape="rect">
    <area target="" research="<img src=http://musicfamily.org/realm/Factions/picks/DragonSet.png align=middle><b> Dragon Set</b></p> <p><b>Requirement</b>: R116+</p> <p><b>Artifacts Required</b>: Dragon Fang, Dragon Soul, Dragon Scale</p> <p><b>Cost</b>: Free</p> <p><b>Effect</b>: Increase the production of Non-Unique buildings based on Faction Coins found in this game.</p> <p><b>Formula</b>: (16 * log10(1 + x) ^ 2), where x is Faction Coins found." coords="136,180,182,226" shape="rect">
</map>
<?php include "../scripts/footer.html"; ?>
